#+ name: Aantal-Genid-nodes
SELECT (COUNT(DISTINCT ?node) AS ?aantalGenidNodes)
WHERE {
  GRAPH ?g {
    ?node ?p ?o .
    FILTER(STRSTARTS(STR(?node), "https://linkeddata.cultureelerfgoed.nl/.well-known/genid/"))
  }
}
