#+ name: Aantal-triples-per-graph
SELECT (REPLACE(STR(?graph), "^urn:graph:", "") AS ?graphNaam)
       (COUNT(*) AS ?triples)
WHERE { 
  GRAPH ?graph { ?s ?p ?o } 
}
GROUP BY ?graph
ORDER BY DESC(?triples)
