#+ name: aantal-instanties-per-klasse
#+ description: Deze query berekent het aantal instanties per klasse, waarbij de duizendtallen worden weergegeven met een komma voor leesbaarheid. Het maakt gebruik van de prefixes ceo en rdfs om de namespaces te definiëren. De resultaten worden gegroepeerd per klasse en geordend op klasse.
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>  # Definieert het prefix "ceo" voor de namespace URI.
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>  # Definieert het prefix "rdfs" voor de namespace URI.

select ?klasse (replace(count(?instantie),'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?aantalInstanties) {  # Selecteert de klasse en berekent het aantal instanties per klasse.
  GRAPH graph:instanties-rce {

  ?instantie a/rdfs:subClassOf* ?klasse.  # Zoekt naar instanties die behoren tot of ondergeschikt zijn aan een bepaalde klasse.

  filter(strstarts(str(?klasse),str(ceo:))) # Filtert alleen de klassen die zich in de CEO-namespace bevinden.
  }}
group by ?klasse  # Groepeert de resultaten op basis van de klasse.
order by ?klasse  # Sorteert de resultaten op basis van de klasse.
