#+ name: aantal-rijksmonumenten
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ceo:  <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX graph:<https://linkeddata.cultureelerfgoed.nl/graph/>

SELECT (COUNT(?cho) AS ?aantal)
WHERE {
  GRAPH graph:instanties-rce {
    ?cho a ceo:Rijksmonument ;
         ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/2/b2d9a59a-fe1e-4552-9a05-3c2acddff864> ;
         ceo:heeftMonumentAard     <https://data.cultureelerfgoed.nl/term/id/rn/2/fc966a68-8863-4970-a83e-110f96006c21> .
  }
}
