#+ name: aantal-triples-per-eigenschap
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho-acceptance/services/cho-acceptance/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?eigenschap (replace(count(*),'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0,') as ?aantalTriples) {
  graph graph:instanties-rce {
    [] ?eigenschap [].
  }
  #?eigenschap0 rdfs:subPropertyOf* ?eigenschap.
}
group by ?eigenschap
order by ?eigenschap