#+ name: Aantal-Genid-nodes
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/kunstcollecties-kc-2/services/kunstcollecties-kc-2/sparql

SELECT (COUNT(DISTINCT ?node) AS ?aantalGenidNodes)
WHERE {
  GRAPH ?g {
    ?node ?p ?o .
    FILTER(STRSTARTS(STR(?node), "https://linkeddata.cultureelerfgoed.nl/.well-known/genid/"))
  }
}
