#+ name: abr-combinatietermen
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/archeologischbasisregister/sparql

PREFIX abr: <https://data.cultureelerfgoed.nl/id/rnce#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select ?combiterm ?combitermLabel ?materiaal ?materiaalLabel ?combitermScopeNote

where {

  service <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/abr> {

  ?combiterm skos:scopeNote ?combitermScopeNote ;
     skos:prefLabel ?combitermLabel .

  OPTIONAL { ?combiterm abr:hasMaterialAbr ?materiaal .
             ?materiaal skos:prefLabel ?materiaalLabel .}

  FILTER contains (?combitermScopeNote, 'combinatieterm')
}} 