#+ name: Api-rijksmonument-test
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

select *
  


WHERE {
  GRAPH graph:instanties-rce {
    ?rm rdf:type ceo:Rijksmonument ;
        ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864> . ?rm ?p1 ?o1 . 
    optional { ?o1 ?p2 ?o2 . optional { ?o2 ?p3 ?o3 . optional { ?o3 ?p4 ?o4 .  optional { ?o4 ?p5 ?o5 . optional { ?o5 ?p6 ?o6 . optional { ?o5 ?p6 ?o6
      
      
              } } } } } }
 
    
    }
} offset 0 limit 10000