#+ name: Berscgermde-gebedshuizen-in-Nederland
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>

SELECT distinct ?rijksmonument ?naam ?rijksmonumentnummer ?datumInschrijving ?provincieLabel ?label ?type

WHERE 
{
  GRAPH graph:instanties-rce {
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
    OPTIONAL {?rijksmonument ceo:heeftNaam/ceo:naam ?naam.}
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov .
  ?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864>.
  ?functie ceo:heeftFunctieNaam ?uri.

  }
  {  GRAPH graph:owms {
      ?prov skos:prefLabel ?provincie . 
   }  
{
  GRAPH graph:bebouwdeomgeving {
  <https://data.cultureelerfgoed.nl/term/id/rn/1eeb48df-adbb-44b2-bcf1-33e3fe902413> skos:narrower ?narrow.
    ?narrow skos:prefLabel ?label.
  }   
        VALUES (?label ?narrow) {
("Religieuze gebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/25fac0f1-77a2-4587-ab04-dfcb66959dd8>)
      }
     ?narrow skos:narrower+ ?uri.
      ?uri skos:prefLabel ?uriSub.
    bind(replace(?uriSub, "\\s\\(.*\\)|\\(.*\\)", "") AS ?type)
}
   BIND(str(?provincie) as ?provincieLabel)
}
}
order By ?naam 