#+ name: ce48e7d6-e608-48f1-a476-e09537e20ba6
#+ description: Zoeken op functie
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select ?shape ?shapeLabel {
  {
    select
      ?shape
      ?naam
      ?omschrijving
      (group_concat(distinct ?functie;separator=', ') as ?functies)
      (group_concat(distinct concat('<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?nummer),'" target="_blank">',str(?nummer),'</a>'); separator=', ') as ?nummers)
      (group_concat(distinct ?type; separator=', ') as ?types)
    {
      ?monument
        ceo:heeftGeometrie/geo:asWKT ?shape;
        ceo:rijksmonumentnummer ?nummer;
        ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functies .
  #    ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving.
  #    OPTIONAL {?monument ceo:heeftMonumentAard/skos:prefLabel ?aard. }
      OPTIONAL {?monument ceo:heeftNaam/ceo:naam ?naam.}
  #    OPTIONAL {?monument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functie .}
      OPTIONAL {?monument ceo:heeftType/ceo:heeftTypeNaam/skos:prefLabel ?type.}
      OPTIONAL {?monument ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving.}
      FILTER regex(?functies, "Vuurtoren$")
    }
    group by ?shape ?naam ?omschrijving
  }
  bind(strdt(concat(
    '<h3>',coalesce(?naam,'Geen naam in het monumentenregister'),'</h3>',
    '<dl>',
      '<dt>Functie</dt><dd>',?functies,'</dd>',
      '<dt>Nummer</dt><dd>',?nummers,'</dd>',
#      '<dt>Aard</dt><dd>',?aard,'</dd>',
        if(strlen(?omschrijving)>250, concat('<dt>Omschrijving</dt><dd>',substr(str(?omschrijving),1,150),'</dd>'),''),
      if(?types!='',concat('<dt>Type</dt><dd>',?types,'</dd>'),''),
    '</dl>'),rdf:HTML) as ?shapeLabel)
} order by ?naam
 LIMIT 100