#+ name: classes-n-view
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct  WHERE {
  <https://linkeddata.cultureelerfgoed.nl/def/ceo> ?pred ?obj .
}