#+ name: Concepten-zonder-labels-in-het-Nederland
#+ description: Concepten zonder labels (in het Nederlands)
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/cht/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept WHERE {
  ?concept a skos:Concept .
  FILTER NOT EXISTS {
    ?concept skos:prefLabel ?label .
    FILTER (lang(?label) = "nl")
  }
  FILTER NOT EXISTS {
    ?concept skos:altLabel ?alt .
    FILTER (lang(?alt) = "nl")
  }
  FILTER NOT EXISTS {
    ?concept skos:hiddenLabel ?hidden .
    FILTER (lang(?hidden) = "nl")
  }
}
