#+ name: De-periode-waarin-een-artefact-voorkwam
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/patrick-mout/Archeologisch-Basis-Register/services/Archeologisch-Informatie-Systeem---thesa/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rnce: <https://digitaalerfgoed-test.poolparty.biz/def/rnce/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?artefact ?periode
  
WHERE {
  ?artefactUri a rnce:ArtefactAbr ;
               skos:prefLabel ?artefact ;
               rnce:hasEndPeriodAbr ?endPeriodUri ;
               rnce:hasBeginPeriodAbr ?beginPeriodUri . 
  ?beginPeriodUri skos:prefLabel ?beginPeriode .
  ?endPeriodUri skos:prefLabel ?eindPeriode . 
  BIND (IF (?beginPeriode = ?eindPeriode, str(?beginPeriode), CONCAT(str(?beginPeriode), " - ", str(?eindPeriode))) AS ?periode)
}