#+ name: EGM-aantal-RM-30000
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?rijksmonumentnummer  
    (REPLACE(STR(?CBSCodeGemeente), "^0+", "") AS ?CBSCodeGemeente)  
    ?subcat ?bovencat1 ?bovencat2 ?bovencat3 
WHERE {
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer 
; ceo:heeftBasisregistratieRelatie/ceo:heeftGemeente ?gemeente 
; ceo:heeftOorspronkelijkeFunctie ?f_uri . ?f_uri ceo:heeftFunctieNaam ?f_urinaam 
; ceo:hoofdfunctie "1"^^xsd:boolean .
 GRAPH graph:bebouwdeomgeving { 
    ?f_urinaam skos:broader ?broader1 . ?f_urinaam skos:prefLabel ?subcat .?broader1 skos:prefLabel ?bovencat1 .
    OPTIONAL {?broader1 skos:broader ?broader2 . ?broader2 skos:prefLabel ?bovencat2 . }
    OPTIONAL {?broader2 skos:broader ?broader3 . ?broader3 skos:prefLabel ?bovencat3 .}
  } 
  # Minus monumentaard archeologisch
  MINUS {?rijksmonument ceo:heeftMonumentAard <https://data.cultureelerfgoed.nl/term/id/rn/b673c8c1-5d93-496d-8f9e-89133d579d77> .
  }
 #  Minus status voorbeschermd
  MINUS {?rijksmonument ceo:heeftJuridischeStatus 
        <https://data.cultureelerfgoed.nl/term/id/rn/2e93edd1-098f-4f31-ae7e-72cb77f4d2ca>} . 
 #  Minus status geen rijksmonument
  MINUS {?rijksmonument ceo:heeftJuridischeStatus 
        <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>} . 
  GRAPH graph:owms {?gemeente owms:CBSCode ?CBSCodeGemeente
}
} 
OFFSET 20001 LIMIT 10000