#+ name: Epitaal-Tombe-en-Wandmonumenten-over-de-
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?periode (COUNT(?grafsoort) AS ?perTypologieAantal) ?grafsoort

WHERE { 
  OPTIONAL{
   ?grafmonument ceox:heeftGrafmonumentType/rdfs:label ?grafsoort ;
                 ceox:heeftGebeurtenis/ceox:heeftDatering/ceox:heeftBeginDatering ?jaar .}
  

  BIND(xsd:integer(?jaar) AS ?jaarSchatting)
  
BIND(IF(?jaarSchatting < 1200, "voor 1200",
       IF(?jaarSchatting >= 1200 && ?jaarSchatting < 1500, "1200 - 1500", 
        IF(?jaarSchatting >= 1500 && ?jaarSchatting < 1800, "1500 - 1800", 
          IF(?jaarSchatting >= 1800, "na 1800",
            ?jaarSchatting)))) AS ?periode)

  FILTER(?grafsoort = "epitaaf" || ?grafsoort = "tombe" || ?grafsoort = "wandmonument")
 
  } 
GROUP BY ?periode ?grafsoort
ORDER BY ?periode ?grafsoort
