#+ name: first-query
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/thesauri/services/thesauri/sparql

prefix text: <http://jena.apache.org/text#>

select *
where {
  ?s text:query 'kompas'.
}
