#+ name: Gebedshuizen-rijksmuseumdata
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
prefix edm: <http://www.europeana.eu/schemas/edm/>



SELECT  distinct *

WHERE 
    
{
SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/Rijksmuseum/collection/services/collection/sparql>{
	
?item dc:subject ?geoname_rijks .
   filter regex(iri(str(?geoname_rijks)), "http://sws.geonames.org") .
    ?geoname_rijks skos:prefLabel ?label.
    filter (contains(?label, "Nijmegen")).
    ?item dc:description ?beschrijving_rijks.
        [ edm:aggregatedCHO ?item;
    edm:isShownBy ?imageLink;
    edm:provider ?provider ]
  }

    
  ?gebouw_rce ceox:heeftAdresgegevens/ceox:woonplaats ?woonplaats_rce.  
  ?gebouw_rce ceox:heeftNaam/ceox:naam ?naam_rce.
  ?gebouw_rce  ceox:rijksmonumentnummer ?rmnr.
 
  bind (str(?label) as ?woonplaats_rijks) .
  filter (sameTerm(?woonplaats_rijks, ?woonplaats_rce))
  filter(contains(?beschrijving_rijks, "Stevenskerk"))
  filter(contains(?naam_rce, "Stevenskerk"))
  
  bind(strdt(concat(
'<div style="position: relative;">',
  '<a href="https://data.netwerkdigitaalerfgoed.nl/Rijksmuseum/collection/browser?resource=',encode_for_uri(?item),'" target="_blank">',
    '<img src="',str(?imageLink),'" style="max-width: 400px;">',
  '</a>',
  '<h1 style="position: absolute; top: -11px; left: 0; width: 100%; line-height: 0px;">',
    '<span style="color: white; font: bold 12px/24px Helvetica, Sans-Serif; line-height: 1.5em; letter-spacing: -1.05px; background: rgb(0, 0, 0); background: rgba(0, 0, 0, 0.7); padding: 2px;">',str(?naam_rce),'</span>',
  '</h1>',
  '<h2 style="position: absolute; bottom: -11px; left: 0; width: 100%;">',
    '<span style="color: white; font: bold 15px/45px Helvetica, Sans-Serif; letter-spacing: -1.05px; background: rgb(0, 0, 0); background: rgba(0, 0, 0, 0.7); padding: 1px;">',str(?woonplaats_rce),'</span>',
  '</h2>',
'</div>',
       "Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr),'" target="_blank">',str(?rmnr),'</a>'),rdf:HTML)  as ?widget)
  }
 

