#+ name: Geldige-en-vervallen-artefacten
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/patrick-mout/Archeologisch-Basis-Register/services/Archeologisch-Informatie-Systeem---thesa/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (count(distinct ?geldig_artefactUri) as ?geldig) 
       (count(distinct ?vervallen_artefactUri) as ?vervallen)
     
WHERE {  
  {
    <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri . 
    ?artefactUri skos:prefLabel ?artefact    
  }
  UNION
  {
    # Geldige artefacten
    <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?geldig_artefactUri . 
    ?geldig_artefactUri skos:prefLabel ?artefact . MINUS { ?geldig_artefactUri <https://digitaalerfgoed-test.poolparty.biz/def/rnce/hasConceptStatus> <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/a166e634-a679-42ae-8362-d9d9c69177f9> } . MINUS { ?geldig_artefactUri <https://digitaalerfgoed-test.poolparty.biz/def/rnce/hasConceptStatus> <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/d9995dd3-9198-4229-8700-65330be1cbfd> }}
 UNION
  {
    # Vervallen artefacten
    <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?vervallen_artefactUri . 
    ?vervallen_artefactUri skos:prefLabel ?artefact ; <https://digitaalerfgoed-test.poolparty.biz/def/rnce/hasConceptStatus> <https://digitaalerfgoed-test.poolparty.biz/term/id/pre/rn/a166e634-a679-42ae-8362-d9d9c69177f9> .
  }}