#+ name: geoGRietveld-2-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX pqv: <http://www.wikidata.org/prop/qualifier/value/>
PREFIX cidoc: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rel: <http://purl.org/vocab/relationship/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX schema: <https://schema.org/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX thesau: <https://collectiedata.hetnieuweinstituut.nl/model/con/thesau/>

SELECT DISTINCT ?item ?rijksmonumentnummer
WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    {
      SELECT DISTINCT ?item ?rijksmonumentnummer
      WHERE {
        ?item p:P84 ?statement0.
        ?statement0 (ps:P84/(wdt:P279*)) wd:Q160435. # wd:Q160435 = Gerrit Rietveld
        OPTIONAL {
          ?item wdt:P359 ?rijksmonumentnummer .
        }
        FILTER(!BOUND(?rijksmonumentnummer))
      }
    }
    
    # ------------------------------------------gebouwLabel---------------------------------------
    # Naam van het gebouw.
    OPTIONAL {
      ?item (wdt:P1705|rdfs:label) ?gebouwLabel .
      FILTER(LANG(?gebouwLabel) = "nl")
    }
    # --------------------------------------Rijksmonumentnummer---------------------------------

    #----------------------------------------------afbeelding-----------------------------------------
    # filter alleen afbeelding format dat werkt met de tijdlijn visualisatie.
    OPTIONAL {
      ?item wdt:P18 ?afbeelding .
      FILTER(REGEX(str(?afbeelding), "(?i)\\.(jpg|gif|jpeg|png)", "i")) # Let op; geen .tif
    }
    #-----------------------------------------eventStartDate------------------------------------
    OPTIONAL {
      ?item (wdt:P571|wdt:P276/(pqv:P580*)|wdt:P1619|wdt:P1319|ps:P580) ?eventStartDate .
      FILTER(YEAR(?eventStartDate) > 1900) # een extra check op foute invoering in wikidata.
    }
  }
}
