PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?rijksmonumentnummer ?datumInschrijvingInMonumentenregister ?adres ?gemeente ?omschrijving ?denominatie ?opmerkingen

WHERE { SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/gebedshuizen/services/gebedshuizen/sparql> {?gebedshuis ceox:rijksmonumentnummer ?rijksmonumentnummer . OPTIONAL { ?gebedshuis ceox:heeftDenominatie/ceox:heeftDenominatieNaam/skos:prefLabel ?denominatie}
  . OPTIONAL { ?gebedshuis ceox:opmerkingen ?opmerkingen}
  }
  VALUES ?rijksmonumentnummer 
  {"2041" "7032" "7045" "7081" "7635" "7837" "8079" "8153" "8247" "8483"} .
  ?rm a ceo:Rijksmonument ; 
      ceo:datumInschrijvingInMonumentenregister ?datumInschrijvingInMonumentenregister ;
      ceo:rijksmonumentnummer ?rijksmonumentnummer ;
      ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:volledigAdres ?adres ;
      ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:gemeentenaam ?gemeente ;
      ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving . 
  MINUS {?rm ceo:heeftOmschrijving/ceo:formeelStandpunt "0"^^xsd:boolean } . #BIND(?rijksmonumentnummer as ?volgnummer)
} 
order by ?rijksmonumentnummer









