#+ name: Hoeveel-van-een-bepaald-type
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
select ?class (count(distinct ?instance) as ?numberOfInstances) {
  graph ?class {
    ?instance ?p [].
  }
}
group by ?class
order by desc(?numberOfInstances)
