#+ name: identical-preflabels-nonote
#+ description: CHT concepten met hetzelfde prefLabel maar zonder scopenote
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/Cultuurhistorische-Thesaurus-CHT/services/Cultuurhistorische-Thesaurus-CHT/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label (count(?label) as ?n) WHERE {
  
 GRAPH   <https://data.cultureelerfgoed.nl/term/id/cht/thesaurus> {
  
?concept a skos:Concept .
?concept skos:prefLabel ?label .
    FILTER NOT EXISTS{   ?concept skos:scopeNote ?scopenote .}
  
}
} ORDER BY DESC (?n)