#+ name: Iets-anders-dan-kaart
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix gsp: <http://www.opengis.net/ont/geosparql#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?bouwdatum ?bouwjaar_date ?type ?bouwjaar
{ ?choi a ceo:Rijksmonument ;
  ceo:rijksmonumentnummer ?nummer;
  OPTIONAL {?choi ceo:heeftType/ceo:heeftTypeNaam/skos:prefLabel ?type. } 
  ?choi ceo:heeftGebeurtenis ?gebeurtenis .
  ?gebeurtenis ceo:heeftGebeurtenisNaam/skos:prefLabel "vervaardiging" .
 ?gebeurtenis ceo:heeftDatering/ceo:heeftTijdvak/ceo:einddatum ?bouwdatum .
 
  FILTER ( ?bouwdatum >= "1949-12-31"^^xsd:date )
  BIND(year(xsd:dateTime(?bouwdatum)) as ?bouwjaar_date)
  BIND(str(?bouwjaar_date) AS ?bouwjaar)
      }