#+ name: kadaster-2ff
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix sor: <https://data.kkg.kadaster.nl/sor/model/def/>
select distinct * where {

  service <https://api.labs.kadaster.nl/datasets/dst/kkg/sparql> {
    ?nummer sor:ligtAan/skos:prefLabel ?straat;
           sor:huisnummer ?huisnummer;
           sor:postcode ?postcode.
    ?vbo sor:hoofdadres ?nummer;
         sor:maaktDeelUitVan ?gebouw.
  }
}