#+ name: kapotte-query
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX schema: <https://schema.org/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?geometrie  ?geslacht ?geometrieColor
{
     SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql>  
{  
  ?rm ceo:heeftGebeurtenis/ceo:heeftActorEnRol ?actor ;
      ceo:heeftGeometrie/geo:asWKT ?geometrie.
  }
  ?actor schema:gender ?geslacht .
 FILTER (!CONTAINS(?geslacht, "n.v.t."))
  #Filter (regex(str(?geslacht), "v", "i"))

  bind(if(?geslacht = "v", "red", "green") as ?geometrieColor)
  
 }