#+ name: KTT-en-Reliwiki
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/gebedshuizen/services/gebedshuizen/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/joop-van-der-heiden/gebedshuizen/graphs/>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT distinct ?databaseID ?rmnr ?naam ?denominatie ?woonplaats ?rmnrLink ?reliwikiLink  WHERE {

  ?k a ceox:Gebedshuis. 
  ?k ceox:databaseID ?databaseID.
  ?k ceox:heeftDenominatie/ceox:heeftDenominatieNaam/skos:prefLabel ?denominatie.
  ?k ceox:heeftAdresgegevens/ceox:woonplaats ?woonplaats.
  optional {?k ceox:heeftNaam/ceox:naam ?naam}
 ?k ceox:rijksmonumentnummer ?rmnr.

  { select ?rmnr ?reliwiki where { SERVICE <https://query.wikidata.org/sparql> {
        ?item  wdt:P31 wd:Q16970 . 
        ?item wdt:P359  ?rmnr;
             wdt:P8897 ?reliwiki 
        }}
  }
 #bind rmnr als link
  bind(URI(concat('https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr))) as ?rmnrLink)
  #bind reliwiki als link
  bind(URI(concat('https://reliwiki.nl/?curid=',uri(?reliwiki))) as ?reliwikiLink)

      
} Order by ?c