#+ name: mcn-geonames-1
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mcn: <https://digitaalerfgoed-test.poolparty.biz/mobielonto/>

SELECT *

WHERE {
  
  ?event mcn:Heeeft-relatie-met-plaats ?plaats .
  ?event skos:scopeNote ?gebeurtenis .
  ?event mcn:Verhaal-is-gerelateerd-aan ?geralateerd .
  ?geralateerd mcn:picture ?image .
  
  ?plaats skos:exactMatch ?geonames .
  ?geonames geo:asWKT ?wkt .
  
  Bind('''
<p>{{gebeurtenis}}</p>
<img src="{{image}}">
'''^^rdf:HTML as ?wktLabel)
 
 

} LIMIT 100
