#+ name: Meest-verbonden-nodes
SELECT ?node (COUNT(*) AS ?verbindingen)
WHERE {
  GRAPH ?g {
    { ?node ?p ?o }
    UNION
    { ?s ?p ?node }
  }
}
GROUP BY ?node
ORDER BY DESC(?verbindingen)
LIMIT 25

