#+ name: Meest-verbonden-nodes
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/kunstcollecties-kc-2/services/kunstcollecties-kc-2/sparql

SELECT ?node (COUNT(*) AS ?verbindingen)
WHERE {
  GRAPH ?g {
    { ?node ?p ?o }
    UNION
    { ?s ?p ?node }
  }
}
GROUP BY ?node
ORDER BY DESC(?verbindingen)
LIMIT 25

