#+ name: Namespaces-van-properties
SELECT ?namespace (COUNT(*) AS ?gebruik)
  
WHERE {
  GRAPH ?g { ?s ?p ?o }
  BIND(REPLACE(STR(?p), "(.*/).*", "$1") AS ?namespace)
}
GROUP BY ?namespace
ORDER BY DESC(?gebruik)
