#+ name: Namespaces-van-classes
SELECT ?namespace (COUNT(*) AS ?gebruik)
WHERE {
  GRAPH ?g { ?s a ?class }
  BIND(REPLACE(STR(?class), "(.*/).*", "$1") AS ?namespace)
}
GROUP BY ?namespace
ORDER BY DESC(?gebruik)

