#+ name: Namespace-frequentie
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/kunstcollecties-kc-2/services/kunstcollecties-kc-2/sparql

SELECT ?namespace (COUNT(*) AS ?gebruik)
WHERE {
  GRAPH ?g {
    ?s ?p ?o .
    BIND(REPLACE(STR(?p), "(.*/).*", "$1") AS ?namespace)
  }
}
GROUP BY ?namespace
ORDER BY DESC(?gebruik)
