#+ name: ObjectProperties
#+ description: ObjectProperties in de ceo ontology
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql

# CEO objectproperties 156
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?ObjectProperty ?comment where { 
    ?ObjectProperty a owl:ObjectProperty .
    ?ObjectProperty rdfs:comment ?comment.
    FILTER
    (strstarts(str(?ObjectProperty), "https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
} 
