PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>
SELECT * WHERE {
  ?object foaf:depiction ?image ; 
          dct:title ?title ;
          schema:comment ?comment ;
          schema:artform ?artform . 
  bind(
    strdt(
      concat('<h4>', ?title, '</h4>', '<b>', ?artform, '</b>', '<p>', ?comment, '</p>', '<p><a href="', ?object, '"><img style="max-width: 250px; max-height: 250px;" src="', ?image, '"/></a></p>'), rdf:HTML) as ?widget) 
}
LIMIT 6
