#+ name: overige-eigenaren
#+ description: skos:prefLabel
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/tooi/sparql

prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix tooi:  <https://identifier.overheid.nl/tooi/def/ont/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select distinct ?uri ?eigenaar ?uri_subgroep_eigenaar ?subgroep_eigenaar ?hoofdgroep_eigenaar ?uri_hoofdgroep_eigenaar

where {
  graph <https://linkeddata.cultureelerfgoed.nl/rce/tooi/graph/hoofdgroepeigenaren> {
    ?uri a skos:Concept ;
      skos:prefLabel ?eigenaar .

      ?uri skos:broader ?uri_subgroep_eigenaar.
      ?uri_subgroep_eigenaar skos:prefLabel ?subgroep_eigenaar.

      ?uri_subgroep_eigenaar skos:broader ?uri_hoofdgroep_eigenaar.
      ?uri_hoofdgroep_eigenaar skos:prefLabel ?hoofdgroep_eigenaar.

      
 #   filter (lang(?eigenaar) = "nl")
  }
}

