#+ name: PathFindr-data
Prefix schema: <https://schema.org/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select * where {
  ?street a schema:Place ;
          schema:name ?streetName ;
          rdfs:label ?identifier ;
          schema:relatedLink/geo:hasGeometry/geo:asWKT ?multiline ;
          schema:honorificFor ?person .
  ?person schema:image ?image ;
          schema:birthDate ?birthDate ;
          schema:deathDate ?deathDate ;
          schema:gender ?theme ;
          schema:description ?description .
          
  
} limit 10