#+ name: Property-paden-van-lengte-3
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/kunstcollecties/sparql

SELECT ?s ?p1 ?m1 ?p2 ?m2 ?p3 ?o
WHERE {
  GRAPH ?g {
    ?s ?p1 ?m1 .
    ?m1 ?p2 ?m2 .
    ?m2 ?p3 ?o .
  }
}
LIMIT 50

