#+ name: Query-3
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/cht/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT 
  (?childLabel AS ?node)
  (?parentLabel AS ?parent)
  (STR(?scopeNote) AS ?tooltip)
WHERE {

  # Testwaarde (verwijderen in LDV als parameter werkt)
  VALUES ?zoektermlabel { "objecten" }

  # Zoek startconcept
  {
    ?startConcept skos:prefLabel ?label .
    FILTER (lang(?label) = "nl")
    FILTER (CONTAINS(LCASE(STR(?label)), LCASE(STR(?zoektermlabel))))
  }
  UNION
  {
    ?startConcept skos:altLabel ?label .
    FILTER (lang(?label) = "nl")
    FILTER (CONTAINS(LCASE(STR(?label)), LCASE(STR(?zoektermlabel))))
  }

  # Inclusief root zelf
  ?concept skos:broader* ?startConcept .

  # Labels
  ?concept skos:prefLabel ?childLabel .
  FILTER (lang(?childLabel) = "nl")

  OPTIONAL {
    ?concept skos:broader ?parentConcept .
    ?parentConcept skos:prefLabel ?parentLabel .
    FILTER (lang(?parentLabel) = "nl")
  }

  OPTIONAL {
    ?concept skos:scopeNote ?scopeNote .
    FILTER (lang(?scopeNote) = "nl")
  }
}