#+ name: Query-9-7
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/patrick-mout/Archeologisch-Basis-Register/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Artefact ?ABR_code
WHERE {
  <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
  
  ?artefactUri skos:prefLabel ?Artefact ;
               <https://data.cultureelerfgoed.nl/id/rnce#codeAbr> ?ABR_code ;
               <https://data.cultureelerfgoed.nl/id/rnce#beginningOfValidity> ?beginGeldigheid .
  
  FILTER (?beginGeldigheid = "2024-07-11"^^xsd:date)
  FILTER (LANG(?Artefact) = "nl")
} ORDER BY ?Artefact
LIMIT 10