#+ name: Query-18-1-1-3
PREFIX luc: <http://www.ontotext.com/connectors/lucene#>
PREFIX luc-index: <http://www.ontotext.com/connectors/lucene/instance#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
 ?entity a skos:Concept ;
        skos:prefLabel ?plabels ;
        skos:altLabel ?alabels ;
        skos:hiddenLabel ?hlabels ;
        skos:scopeNote ?scopeNote ;
        skos:broader ?broader_uri ;
        skos:narrower ?narrower_uri ;
        skos:related ?related_uri .
    ?broader_uri skos:prefLabel ?broader_prefLabel .
    ?narrower_uri skos:prefLabel ?narrower_prefLabel .
    ?related_uri skos:prefLabel ?related_prefLabel .

}
  WHERE {
  BIND (CONCAT("*", ?term, "*") AS ?searchTerm)
    SERVICE <https://cultureelerfgoed-graphdb.poolparty.biz/repositories/cht> {
    
    ?search a luc-index:cht_kw-fo ;
      luc:query ?searchTerm ;
      luc:entities ?entity .
  ?entity skos:prefLabel ?plabels .
 FILTER (lang(?plabels) = 'nl')

  optional{ ?entity skos:broader ?broader_uri .
      		?broader_uri skos:prefLabel ?broader_label .
      FILTER (lang(?broader_label) = 'nl') }

    optional{ ?entity skos:narrower ?narrower_uri .
      		?narrower_uri skos:prefLabel ?narrower_label .
      FILTER (lang(?narrower_label) = 'nl') }

    optional{ ?entity skos:related ?related_uri .
      		?related_uri skos:prefLabel ?related_label .
      FILTER (lang(?related_label) = 'nl') }


    OPTIONAL {?entity skos:altLabel ?alabels .
      FILTER (lang(?alabels) = 'nl') }
    OPTIONAL {?entity skos:hiddenLabel ?hlabels .
    FILTER (lang(?hlabels) = 'nl')}

    OPTIONAL {?entity skos:scopeNote ?scopeNote .
      FILTER (lang(?scopeNote) = 'nl')}
  }
    }
