#+ name: Query-6-1-1-1-4-1
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>

SELECT*
#?subFunctie ?shape (COUNT(?uri) AS ?labelSub) ?shapeLabel ?provincieLabel  ?uriSubs

WHERE 
{
  GRAPH graph:instanties-rce {
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov .
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}

    OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}
  #  OPTIONAL {?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:woonplaatsnaam ?plaats.}
  ?functie ceo:heeftFunctieNaam ?uri.

 BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
# BIND(year(xsd:dateTime(?jaarInschrijving)) as ?beginJaarInschrijving)
#   BIND(year(xsd:dateTime(?beginInschrijving)) as ?eindJaarInschrijving)
 
  FILTER (?jaarInschrijving >= ?beginJaarInschrijving && ?jaarInschrijving <= ?eindJaarInschrijving)
    bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
    BIND(concat(str(?beginJaarInschrijving)," - ", ?eindJaarInschrijving) AS ?periode)
  }
  {  GRAPH graph:owms {
      ?prov skos:prefLabel ?provincie . 
    }
     # ?prov overheid:CBSCode ?code .
   }  
  GRAPH graph:bebouwdeomgeving {
  {<https://data.cultureelerfgoed.nl/term/id/rn/fea024ba-83a0-4418-afbe-3b7b4588797e> skos:broader ?uri.}
  UNION{  
  {<https://data.cultureelerfgoed.nl/term/id/rn/a3dbebf9-a237-4caa-9ee6-347c9d30dd9e> skos:narrower ?uri . }
      }
     ?uri skos:prefLabel ?uriSub.
     
      bind(replace(?uriSub, "\\s\\(.*\\)|\\(.*\\)", "") AS ?uriSubs) 
    }
    
 
          BIND(str(?provincie) as ?provincieLabel)
 # BIND(concat(str(?uriSubs)," - ",?jaarInschrijving, " - ",?rijksmonumentnummer) AS ?shapeLabel)
  BIND(strdt(concat(?uriSubs, " - ", ?jaarInschrijving, " - ", "Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>'),rdf:HTML) AS ?shapeLabel)
  Bind(concat(str(?uriSubs), " ", ?periode) AS ?subFunctie)
  BIND(if(?uriSubs="Industrie- en poldermolen", "red", if(?uriSubs="Molen", "purple", if(?uriSubs="Molenaarswoning", "maroon", if(?uriSubs="Oliemolen", "black", if(?uriSubs="Molenaarshuis", "orange", if(?uriSubs="Korenmolen", "gray", if(?uriSubs="Papiermolen", "white", if(?uriSubs="Watermolen", "aqua", if(?uriSubs="Ondermolen", "fuchsia", if(?uriSubs="Getijmolen", "teal", if(?uriSubs="Weidemolen", "lime", if(?uriSubs="Boezemmolen", "blue", if(?uriSubs="Bovenmolen", "navy", if(?uriSubs="Roedenloods", "crimson", "darksalmon")))))))))))))) as ?shapeColor)
  
    bind (
    if(?keuze="AHN","https://service.pdok.nl/rws/ahn3/wms/v1_0?request=getcapabilities&service=wms",
    if(?keuze="Luchtfoto","https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?request=GetCapabilities&service=wms",
    if(?keuze="BRT Achtergrondkaart", "https://service.pdok.nl/brt/top10nl/wms/v1_0?service=wms&request=getCapabilities", ""))) as ?mapEndpoint)     
        
  
}

#GROUP BY ?subFunctie ?shape ?shapeLabel ?provincieLabel  ?uriSubs


  

