#+ name: Query-11-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/gebedshuizen/services/gebedshuizen/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX id: <https://hetutrechtsarchief.nl/id/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>


SELECT distinct(strdt(concat(
	'<img style="height:170px;" src="',str(?img),'">',
	'</a></div>',
      concat(str(?naam), ": ", str(?description)),'<br />',
	'</p>', "Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr),'" target="_blank">',str(?rmnr),'</a>'
	),rdf:HTML) as ?widget)

WHERE {
 ?reliGebouw ceox:heeftAdresgegevens/ceox:woonplaats "Utrecht".
  ?reliGebouw ceox:rijksmonumentnummer ?rmnr.
 ?reliGebouw ceox:heeftNaam/ceox:naam ?naam. 

{SELECT distinct   ?naamU ?description ?img
WHERE { SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/hetutrechtsarchief/Beeldbank/services/Beeldbank/sparql>{
  ?cho dct:spatial ?plek.
   ?plek rdfs:label ?naamU.
	?cho edm:isShownBy ?img .
	?cho dc:description ?description .
        Filter regex (?description, ?zoekwoord, "i")
}
    }}
  Filter(contains(?naam,  ?naamU))

}
