#+ name: Query-3-2-2
#+ description: Vul zelf je afstand in, in meters
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/aardbevingen/sparql

#benodigde prefixen
#resultaat is een kaart
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX schema: <http://schema.org/>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX lxr: <https://linkeddata.cultureelerfgoed.nl/def/lxr#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
prefix gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

#selecteer voorlopig alles
SELECT (GROUP_CONCAT(?link; SEPARATOR = ", ") AS ?links) ?event ?eventLabel ?eventStart ?date ?tijd ?shape ?diepte ?magnitude ?plaatsnaam ?rm ?rmn ?eventMedia ?afstand ?new_date ?geoColor ?shapeColor ?shapeLabel
{

#start de service naar de dataset aardbevingen  
SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/aardbeving/services/aardbeving/sparql> {  
  
?event a schema:Event.
?event schema:name ?eventLabel.
?event schema:startDate ?eventStart.
?event schema:date ?date. 
?event schema:startTime ?tijd.
?event gsp:asWKT ?shape.  
?event lxr:diepte ?diepte.
?event lxr:magnitude ?magnitude.
?event ceox:woonplaatsnaam ?plaatsnaam .
  }
#einde service
#vraag nu met ceox:woonplaatsnaam ?plaatsnaam de vergelijkbare monumenten op in de cho database  
?rm a ceo:Rijksmonument.
?rm ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:woonplaatsnaam ?plaatsnaam.
?rm ceo:rijksmonumentnummer ?rmn.
?rm ceo:heeftGeometrie/gsp:asWKT ?geo.

#start een nieuwe service om met de opgehaalde rijkmonumentnummers afbeeldingen op te halen uit wikidata  
    SERVICE <https://query.wikidata.org/sparql>
{
  ?wikirm wdt:P18 ?eventMedia.
  ?wikirm wdt:P359 ?rmn.
  }

#hier volgen enkele binds en filters voor het eindresultaat  
bind(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/",uri(?rmn)) as ?link)
Bind(?afstandinmeters as ?afstand)
FILTER((geof:distance(?geo,?shape, uom:meter)) < ?afstand )
bind ("red" as ?geoColor)
bind ("orange" as ?shapeColor)
#de date is amerikaans dus die zetten we ff om naar "normale" weergave  
BIND(concat(substr(str(?date), 9, 2), "-", substr(str(?date), 6, 2), "-", substr(str(?date), 1, 4)) AS ?new_date)

#dit is de bind om het shapeLabel mogelijk te maken. NB shapeLabel gaat uit van de aardbeving en het monument in de buurt. Monumenten hebben geen shapeLabel.

BIND(strdt(concat('<div style="position: relative;">','<img src="',str(?eventMedia),'" style="max-width: 100px;">','</a>','</p>',"Op ", ?new_date, " om ", ?tijd, " was er een ", ?eventLabel," van magnitude ", ?magnitude, " op een diepte van ", ?diepte, " bij de plaats ", ?plaatsnaam, " op ", ?afstand, " meter van rijksmonument ",'<a href="',str(?links),'" target="_blank">',uri(?rmn),'</a>'),rdf:HTML) as ?shapeLabel)

}
order By ?eventStart
LIMIT 1000
