#+ name: Query-17-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT distinct ?class ?predikaat (count(?object) as ?aantal)  WHERE {
  ?s a ?class ; ?predikaat ?object . FILTER (?class IN (ceo:ArcheologischComplex, ceo:ArcheologischTerrein, ceo:ArcheologischOnderzoeksgebied, ceo:Vondstlocatie, ceo:Vondsten, ceo:Grondsporen)) .
} 
order by ?class ?predikaat