#+ name: Query-12-5
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT ?classOrProperty ?aantal1 ?aantal2 (?aantal1 - ?aantal2 AS ?verschil)
WHERE {
  # Haal het aantal instanties per class/property uit de eerste graph
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-08-23T12-07-06> {
    ?classOrProperty ceo:aantalInstanties ?aantal1 .
  }
  # Haal het aantal instanties per class/property uit de tweede graph
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-08-23T12-11-37> {
    ?classOrProperty ceo:aantalInstanties ?aantal2 .
  }
}
