#+ name: Query-6-1-1-1
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>

SELECT ?subFunctie ?shape (COUNT(?uri) AS ?labelSub) ?shapeLabel ?provincieLabel ?provincie

WHERE 
{
  GRAPH graph:instanties-rce {
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov .
      MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}

    OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}
  ?functie ceo:heeftFunctieNaam ?uri.

 BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
# BIND(year(xsd:dateTime(?jaarInschrijving)) as ?beginJaarInschrijving)
#   BIND(year(xsd:dateTime(?beginInschrijving)) as ?eindJaarInschrijving)
 
  FILTER (?jaarInschrijving >= ?beginJaarInschrijving && ?jaarInschrijving <= ?eindJaarInschrijving)
    bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
    BIND(concat(str(?beginJaarInschrijving)," - ", ?eindJaarInschrijving) AS ?periode)
  }
  {  GRAPH graph:owms {
      ?prov skos:prefLabel ?provincie . 

     # ?prov overheid:CBSCode ?code .
   }  
{
  GRAPH graph:bebouwdeomgeving {
  <https://data.cultureelerfgoed.nl/term/id/rn/1eeb48df-adbb-44b2-bcf1-33e3fe902413> skos:narrower ?narrow.
    ?narrow skos:prefLabel ?label.
     
  VALUES (?label ?narrow) {
    ("Archeologie (N)" <https://data.cultureelerfgoed.nl/term/id/rn/d60159d2-8b55-47b7-8301-5ac82b0f2d7f>)
    ("Bestuursgebouwen, rechtsgebouwen en overheidsgebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/74a847b5-1e0f-4f66-b910-90d2c8d9fa04>)
    ("Boerderijen, molens en bedrijven" <https://data.cultureelerfgoed.nl/term/id/rn/b8077035-db8f-47f1-ae1d-e64f75344fcf>)
("Cultuur, gezondheid en wetenschap" <https://data.cultureelerfgoed.nl/term/id/rn/0be0a6c9-0738-41cc-aaac-550d258c4261>)
("Handelsgebouwen, opslag- en transportgebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/e88ccbf4-e41d-49bf-9876-0f71db0e6646>)
("Kastelen, landhuizen en parken" <https://data.cultureelerfgoed.nl/term/id/rn/b2511baf-3b70-4667-98dd-1b850c7ea53f>)
("N.V.T." <https://data.cultureelerfgoed.nl/term/id/rn/8d4228b6-7f8d-4b78-b870-901879af8c04>)
("Religieuze gebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/25fac0f1-77a2-4587-ab04-dfcb66959dd8>)
("Sport, recreatie, vereniging en horeca" <https://data.cultureelerfgoed.nl/term/id/rn/b797b89c-1e0a-4ce7-869b-817cd98259b0>)
("Uitvaartcentra en begraafplaatsen" <https://data.cultureelerfgoed.nl/term/id/rn/1680dfc0-666a-4a01-9781-59e9af26ec51>)
("Verdedigingswerken en militaire gebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/5013dcbc-1090-42e9-bc22-92de47e43783>)
("Voorwerpen op pleinen en dergelijke" <https://data.cultureelerfgoed.nl/term/id/rn/92cda3e4-8c6a-41dc-9a81-02f8aba88b25>)
("Weg- en waterbouwkundige werken" <https://data.cultureelerfgoed.nl/term/id/rn/11c897ed-d35e-4191-9254-7ab95d9d63bc>)
("Woningen en woningbouwcomplexen" <https://data.cultureelerfgoed.nl/term/id/rn/5b7dd16c-fa8d-4d68-984a-9ec0efc650d4>)

  }   
     ?narrow skos:narrower+ ?uri.
      ?uri skos:prefLabel ?uriSub.
    bind(replace(?uriSub, "\\s\\(.*\\)|\\(.*\\)", "") AS ?uriSubs)
   #   bind (?uriSubs as ?shapeLabel)
      
      
 
}
  
  }
  }
          BIND(str(?provincie) as ?provincieLabel)
 # BIND(concat(str(?uriSubs)," - ",?jaarInschrijving, " - ",?rijksmonumentnummer) AS ?shapeLabel)
  BIND(strdt(concat(?uriSubs, " - ", ?jaarInschrijving, " Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>'),rdf:HTML) AS ?shapeLabel)
  Bind(concat(str(?uriSubs), " ", ?periode) AS ?subFunctie)

}
GROUP BY ?subFunctie ?shape ?shapeLabel ?provincieLabel ?provincie ?prov


  

