#+ name: Query-6-1-1-1-1-1-1-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>

SELECT distinct ?shapeLabel ?mapEndpoint ?plaats ?shape ?ff ?beginPeriode ?ac

WHERE 
{
  ?ao a ceo:ArcheologischOnderzoeksgebied .
  GRAPH graph:instanties-rce {
  ?ao ceo:heeftGeometrie/geo:asWKT ?shape.
  ?ao ceo:bevatObject ?ac.
    FILTER (regex(str(?ac), "archeologischcomplex" , "i "))
    ?ac ceo:heeftType/ceo:heeftTypeNaam ?comp.
    ?comp skos:prefLabel ?complextype.
    ?ac ceo:heeftGebeurtenis/ceo:heeftDatering/ceo:heeftBeginDatering/ceo:heeftPeriode ?perB.
    ?ac ceo:heeftGebeurtenis/ceo:heeftDatering/ceo:heeftEindDatering/ceo:heeftPeriode ?perE.
    ?perB skos:prefLabel ?beginPeriode.
     ?perE skos:prefLabel ?eindPeriode.
   ?ao ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie ?pl.
  ?pl ceo:woonplaatsnaam ?plaats.
    }
    BIND(CONCAT("Plaats: ", ?plaats, " - ", "Complextype: ", ?complextype, " - ", "Periode: ", ?beginPeriode,"-",?eindPeriode) AS ?shapeLabel)

  #kadaster
   # BIND(<https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0?request=getCapabilities> AS ?mapEndpoint)
   BIND(<https://service.pdok.nl/brt/top10nl/wms/v1_0?service=wms&request=getCapabilities> AS ?mapEndpoint)
  }

  


  

