#+ name: Query-6-4
#+ description: Wat is de range van alle properties.
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?property ?range
WHERE
{
?property rdfs:range ?range
FILTER (strstarts(str(?property),"https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}
order by ?property
