#+ name: Query-12-5
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?classOrProperty ?count20240830 ?count20240911 (?count20240830 - ?count20240911 AS ?verschil)

WHERE {
  # Haal het aantal instanties per class/property uit de eerste graph
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-08-30T10-16-54> {
    ?classOrProperty ceo:aantalInstanties ?count20240830 .
  }
  # Haal het aantal instanties per class/property uit de tweede graph
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-09-16T14-33-59> {
    ?classOrProperty ceo:aantalInstanties ?count20240911 . 
  }
}
