#+ name: Query-20-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

select (count(distinct ?afgevoerd_rijksmonument) as ?aantalAfgevoerdeRijksmonumenten)
where {
  graph graph:instanties-rce {
    ?afgevoerd_rijksmonument
      ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/2/3e79bb7c-b459-4998-a9ed-78d91d069227> #9227=afgevoerd.
  }
}
