#+ name: Query-10
#+ description: Telt het voorkomen van de drie verschillende statussen.
#- - rijksmonument
#- - geen rijksmonument
#- - voorbeschermd
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT (Count(distinct ?rm) AS ?rms) ?status ?label
WHERE {
  ?rm a ceo:Rijksmonument .
  ?rm ceo:heeftJuridischeStatus ?status.
  ?status skos:prefLabel ?label.
}
