#+ name: Query-19-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/Archeologisch-Basis-Register/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>

SELECT ?baseUri
       (SUM(?exactCount) AS ?exactMatch)
       (SUM(?closeCount) AS ?closeMatch)
       (SUM(?broadCount) AS ?broadMatch)
       (SUM(?narrowCount) AS ?narrowMatch)
       (SUM(?relatedCount) AS ?relatedMatch)
WHERE {
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
    # Query voor skos:exactMatch
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ; 
                 skos:exactMatch ?exact_Match .

    BIND (
      SUBSTR(
        str(?exact_Match),
        1,
        STRLEN(str(?exact_Match)) - STRLEN(REPLACE(str(?exact_Match), "^.*/", "")) - 1
      ) AS ?baseUri
    )

    BIND(1 AS ?exactCount)
    BIND(0 AS ?closeCount)
    BIND(0 AS ?broadCount)
    BIND(0 AS ?narrowCount)
    BIND(0 AS ?relatedCount)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
    # Query voor skos:closeMatch
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ; 
                 skos:closeMatch ?close_Match .

    BIND (
      SUBSTR(
        str(?close_Match),
        1,
        STRLEN(str(?close_Match)) - STRLEN(REPLACE(str(?close_Match), "^.*/", "")) - 1
      ) AS ?baseUri
    )

    BIND(0 AS ?exactCount)
    BIND(1 AS ?closeCount)
    BIND(0 AS ?broadCount)
    BIND(0 AS ?narrowCount)
    BIND(0 AS ?relatedCount)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
    # Query voor skos:broadMatch
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ; 
                 skos:broadMatch ?broad_Match .

    BIND (
      SUBSTR(
        str(?broad_Match),
        1,
        STRLEN(str(?broad_Match)) - STRLEN(REPLACE(str(?broad_Match), "^.*/", "")) - 1
      ) AS ?baseUri
    )

    BIND(0 AS ?exactCount)
    BIND(0 AS ?closeCount)
    BIND(1 AS ?broadCount)
    BIND(0 AS ?narrowCount)
    BIND(0 AS ?relatedCount)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
    # Query voor skos:narrowMatch
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ; 
                 skos:narrowMatch ?narrow_Match .

    BIND (
      SUBSTR(
        str(?narrow_Match),
        1,
        STRLEN(str(?narrow_Match)) - STRLEN(REPLACE(str(?narrow_Match), "^.*/", "")) - 1
      ) AS ?baseUri
    )

    BIND(0 AS ?exactCount)
    BIND(0 AS ?closeCount)
    BIND(0 AS ?broadCount)
    BIND(1 AS ?narrowCount)
    BIND(0 AS ?relatedCount)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
    # Query voor skos:relatedMatch
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ; 
                 skos:relatedMatch ?related_Match .

    BIND (
      SUBSTR(
        str(?related_Match),
        1,
        STRLEN(str(?related_Match)) - STRLEN(REPLACE(str(?related_Match), "^.*/", "")) - 1
      ) AS ?baseUri
    )

    BIND(0 AS ?exactCount)
    BIND(0 AS ?closeCount)
    BIND(0 AS ?broadCount)
    BIND(0 AS ?narrowCount)
    BIND(1 AS ?relatedCount)
  } }
}
GROUP BY ?baseUri
