#+ name: Query-2-3-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/2/>
prefix schema: <https://schema.org/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix edm: <http://www.europeana.eu/schemas/edm/>

select distinct
  ?rijksmonument
  (iri(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/", ?rijksmonumentnummer)) as ?monumentenregister)
  ?rijksmonumentnummer
  ?monumentaard
  ?provincie
  ?gemeente
  ?adres
  ?postcode
  ?woonplaatsnaam
  ?functie
  ?datumInschrijving
  ?afbeeldingTitel
  ?contentUrl
  ?beeldbank
where {
  graph graph:instanties-rce {
    ?rijksmonument a ceo:Rijksmonument ;
      ceo:rijksmonumentnummer ?rijksmonumentnummer ;
      ceo:datumInschrijvingInMonumentenregister ?datumInschrijving ;
      ceo:heeftJuridischeStatus rn:b2d9a59a-fe1e-4552-9a05-3c2acddff864 ;
      ceo:heeftMonumentAard/skos:prefLabel ?monumentaard ;
      ceo:heeftBasisregistratieRelatie ?basisrel .

    # ?basisrel ceo:heeftProvincie/skos:prefLabel ?provincie ;
    #           ceo:heeftGemeente/skos:prefLabel ?gemeente .

    # BAG gegevens ophalen
    optional {
      ?rijksmonument (ceo:heeftBasisregistratieRelatie|ceo:bevatObject/ceo:heeftBasisregistratieRelatie)/ceo:heeftBAGRelatie ?bagrelatie .
      ?bagrelatie ceo:volledigAdres ?adres ;
                  ceo:postcode ?postcode ;
                  ceo:woonplaatsnaam ?woonplaatsnaam .
    }
    
    # Filter moet hier staan, nadat ?woonplaatsnaam is opgehaald
 FILTER (regex(?woonplaatsnaam, "Amersfoort", "i"))

    optional {
      ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?functies 
      
    }
  }

  optional {
    graph graph:bebouwdeomgeving {
      ?functies skos:prefLabel ?functie_ .
      # We filteren op het label dat eindigt op ' (formeel standpunt)' of vergelijkbaar indien nodig
      bind(replace(?functie_, "\\s\\(.*\\)", "") as ?functie)
    }
  }

  optional {
    service <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/afbeeldingen2/sparql> {
      graph <https://linkeddata.cultureelerfgoed.nl/graph/image> {
        ?image schema:about ?rijksmonument ;
               schema:name ?afbeeldingTitel ;
               schema:contentUrl ?contentUrl ;
               edm:isShownAt ?beeldbank .
      }
    }
  }
}
limit 20000