#+ name: Query-3-10
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/Archeologisch-Basis-Register/sparql

prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rnce: <https://data.cultureelerfgoed.nl/id/rnce#>

SELECT ?matchfix (count(distinct ?artefactUri) as ?aantal)

WHERE {
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ;
                 skos:exactMatch ?match .
    FILTER (LANG(?artefact) = "nl") .
    BIND("exactMatch" as ?matchfix)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ;
                 skos:closeMatch ?match .
    FILTER (LANG(?artefact) = "nl")  .
    BIND("closeMatch" AS ?matchfix)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ;
                 skos:broadMatch ?match .
    FILTER (LANG(?artefact) = "nl")  .
    BIND("broadMatch" AS ?matchfix)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ;
                 skos:narrowMatch ?match .
    FILTER(LANG(?artefact) = "nl")  .
    BIND("narrowMatch" AS ?matchfix)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact ;
                 skos:relatedMatch ?match .
    FILTER(LANG(?artefact) = "nl")  .
    BIND("relatedMatch" AS ?matchfix)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/abr> {
    <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
    ?artefactUri skos:prefLabel ?artefact .
    FILTER NOT EXISTS {
      ?artefactUri skos:exactMatch ?match
    } .
    FILTER NOT EXISTS {
      ?artefactUri skos:closeMatch ?match
    } .
    FILTER NOT EXISTS {
      ?artefactUri skos:broadMatch ?match
    } .
    filter not exists {
      ?artefactUri skos:narrowMatch ?match
    } .
    FILTER NOT EXISTS {
      ?artefactUri skos:relatedMatch ?match
    } .
    FILTER(LANG(?artefact) = "nl")  .
    BIND("geen match" AS ?matchfix)
  } }
} GROUP BY ?matchfix