#+ name: Query-12-5-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?classOrProperty ?count20241017 ?count20241021 (?count20241017 - ?count20241021 as ?verschil)

where {
  # Haal het aantal instanties per class/property uit de eerste graph
  graph <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-10-17T09-16-15> {
    ?classOrProperty ceo:aantalInstanties ?count20241017 .
  }
  # Haal het aantal instanties per class/property uit de tweede graph
  graph <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce/count2024-10-21T15-48-35>
  {
    ?classOrProperty ceo:aantalInstanties ?count20241021 .
  }
}