#+ name: Query-2-3
#+ description: Query gemaakt om in AMR selectie voor ChatGPT de juiste uri's te koppelen aan rijksmonumentnummer
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?rm_uri ?rijksmonumentnummer 
WHERE {
  SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/rn> {
  {<https://data.cultureelerfgoed.nl/term/id/rn/03f70e6e-4cda-4501-8545-a738ba6ee868> skos:broader ?f.}
  UNION{
  <https://data.cultureelerfgoed.nl/term/id/rn/25fac0f1-77a2-4587-ab04-dfcb66959dd8> skos:narrower+ ?f.}}
  ?rm_uri ceo:rijksmonumentnummer ?rijksmonumentnummer ; ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?f .
} 
