#+ name: Query-16-3-1-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT * WHERE {
  {
  graph graph:buitenplaatsen {
  ?complex a ceo:Complex .
  ?complex ceox:RCEBuitenplaats "1"^^xsd:boolean.
  }
   {
 GRAPH graph:instanties-rce { 
  ?complex ceo:complexnummer ?complexnummer.
  ?complex ceo:heeftHoofdobject ?hoofdobject.
  ?complex ceo:heeftKennisregistratie/ceo:naam ?naam.
  ?complex ceo:heeftRijksmonument ?rijksmonument.
  ?hoofdobject ceo:rijksmonumentnummer ?hoofdobjectnummer.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape .
  }

  BIND(strdt(concat("Naam: ", ?naam, " Complexnummer: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?complexnummer),'" target="_blank">',str(?complexnummer),'</a>', " Hoofdobjectnr: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?hoofdobjectnummer),'" target="_blank">',str(?hoofdobjectnummer),'</a>'," Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>'),rdf:HTML) as ?shapeLabel)
  bind( "black" AS ?shapeColor)

    bind (
    if(?keuze="AHN","https://service.pdok.nl/rws/ahn3/wms/v1_0?request=getcapabilities&service=wms",
    if(?keuze="Luchtfoto","https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?request=GetCapabilities&service=wms",
    if(?keuze="BRT Achtergrondkaart", "https://service.pdok.nl/brt/top10nl/wms/v1_0?service=wms&request=getCapabilities", ""))) as ?mapEndpoint)     
        
        
        
 }}}
