#+ name: Query-6
#+ description: Query om te zoeken of er een " ." in een tekst voor komt
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>


SELECT ?rm ?description (COUNT(?s) AS ?count)
WHERE {
  GRAPH graph:instanties-rce {
  ?s ceo:heeftOmschrijving/ceo:omschrijving ?description.
  ?s ceo:rijksmonumentnummer ?rm.

    FILTER (
      REGEX(?description, " \\.$", "i"))
    }
}
GROUP BY ?rm ?description
ORDER BY ?rm
