#+ name: Query-16-1-1-1-1
#+ description: Query waarbij in de gezocht wordt op functie "Winkels" en alles wat er onder hangt
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>

SELECT DISTINCT * FROM NAMED graph:instanties-rce FROM NAMED graph:bebouwdeomgeving FROM NAMED graph:wikirm {
GRAPH ?g { 

  ?rijksmonument a ceo:Rijksmonument .
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer .
#  OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape .}
 # ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?narrow .
  ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:verblijfsobjectIdentificatie ?id .
 # MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>
      
 # {<https://data.cultureelerfgoed.nl/term/id/rn/05606ed7-8375-401d-965d-9300010fc6c1> skos:broader ?narrow.}
 # UNION
 # {<https://data.cultureelerfgoed.nl/term/id/rn/e88ccbf4-e41d-49bf-9876-0f71db0e6646> skos:narrower+ ?narrow .}
 # ?narrow skos:prefLabel ?label .

 # ?wikirm ceo:rijksmonumentnummer ?rijksmonumentnummer . 
 # ?wikirm wdt:P18 ?afbeelding . 
 
 SERVICE <https://api.labs.kadaster.nl/datasets/dst/kkg/services/default/sparql> {
  ?bag bag:identificatie ?id .
 # OPTIONAL {?bag bag:oorspronkelijkBouwjaar ?gebruiksdoel .}
 
    }}}
 LIMIT 1000
