#+ name: Query-7-3
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/Archeologisch-Basis-Register/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?geldigheidArtefact (COUNT(DISTINCT ?abrcode) AS ?aantal)
WHERE {
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/1bfbc515-5bee-4c49-86aa-fb03c8ee3667> {
    <https://data.cultureelerfgoed.nl/term/id/abr/2/7bf0e585-f6ea-4956-b6d0-bbff5fa2521c> skos:narrower/skos:narrower ?abrcode .
    ?abrcode rnce:beginningOfValidity ?beginVal .
    FILTER ( ?beginVal >= "2024-07-01"^^xsd:date )
    BIND("nieuwe artefacten" AS ?geldigheidArtefact)
  } }
  UNION
  { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/1bfbc515-5bee-4c49-86aa-fb03c8ee3667> {
    <https://data.cultureelerfgoed.nl/term/id/abr/2/7bf0e585-f6ea-4956-b6d0-bbff5fa2521c> skos:narrower/skos:narrower ?abrcode .
    ?abrcode rnce:beginningOfValidity ?beginVal .
    FILTER ( ?beginVal < "2024-07-01"^^xsd:date )
    BIND("oude/bestaande artefacten" AS ?geldigheidArtefact)
  } }
}
GROUP BY ?geldigheidArtefact
ORDER BY ?geldigheidArtefact