#+ name: Query-3-3
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/erfgeo/sparql

PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX geo:   <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>
PREFIX lpo:   <http://linkedpasts.org/ontology#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>

CONSTRUCT {

  # Als je de output in een aparte named graph wilt:
  # GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/gemeentegeschiedenis-lpo> {

    # ----- Place -------------------------------------------------
    ?pit  a lpo:Place ;
          lpo:hasTitle          ?title ;
          lpo:sourceId          ?ident ;
          lpo:sourceDataset     "Gemeentegeschiedenis" ;
          lpo:sourceDatasetURI  "https://linkeddata.cultureelerfgoed.nl/graph/gemeentegeschiedenis"^^xsd:anyURI ;
          lpo:hasName           ?prefName ;
          lpo:hasType           ?placeType .

    # Optioneel: alt-namen
    ?pit  lpo:hasName ?altName .

    # Geometrie indien aanwezig
    ?pit  lpo:hasGeom ?geom .

    # Tijd indien aanwezig
    ?pit  lpo:hasWhen ?when .


    # ----- PlaceName (pref) --------------------------------------
    ?prefName a lpo:PlaceName ;
              lpo:toponym  ?title ;
              lpo:language ?titleLang .

    # ----- PlaceName (alt) ---------------------------------------
    ?altName  a lpo:PlaceName ;
              lpo:toponym  ?alt ;
              lpo:language ?altLang .


    # ----- PlaceType ---------------------------------------------
    ?placeType a lpo:PlaceType ;
               lpo:identifier    <http://vocab.getty.edu/aat/300265612> ;
               lpo:typeLabel     "gemeente" ;
               lpo:hasSourceLabel ?srcLabel .

    ?srcLabel a lpo:SourceLabel ;
              lpo:labelValue    "gemeente" ;
              lpo:labelLanguage "nl" .


    # ----- PlaceGeom ---------------------------------------------
    ?geom a lpo:PlaceGeom ;
          lpo:wktValue ?wkt ;
          geo:asWKT    ?wkt .


    # ----- When --------------------------------------------------
    ?when a lpo:When ;
          lpo:start ?startStr ;
          lpo:end   ?endStr .
  # }
}
WHERE {

  GRAPH graph:gemeentegeschiedenis {

    # bron-PIT voor gemeente
    ?pit a <https://rdf.histograph.io/PlaceInTime> ;
         a <http://rdf.histograph.io/Municipality> ;
         dc:identifier ?ident ;
         dc:title      ?title .

    # eventuele alternatieve naam
    OPTIONAL {
      ?pit dct:alternative ?alt .
      BIND( LANG(?alt) AS ?altLang )
      BIND( IRI(CONCAT(STR(?pit), "/name/alt")) AS ?altName )
    }

    # geometrie (asWKT op PIT)
    OPTIONAL {
      ?pit geo:asWKT ?wkt .
      BIND( IRI(CONCAT(STR(?pit), "/geom/1")) AS ?geom )
    }

    # start / end jaar → When
    OPTIONAL {
      ?pit schema:startDate ?startYear .
      ?pit schema:endDate   ?endYear .
      BIND( IRI(CONCAT(STR(?pit), "/when/1")) AS ?when )
      BIND( STR(?startYear) AS ?startStr )
      BIND( STR(?endYear)   AS ?endStr )
    }

    # taal van de hoofdnaam (als aanwezig; hier waarschijnlijk leeg)
    BIND( LANG(?title) AS ?titleLang )
  }

  # afgeleide IRIs (buiten GRAPH-blok)
  BIND( IRI(CONCAT(STR(?pit), "/name/pref"))        AS ?prefName )
  BIND( IRI(CONCAT(STR(?pit), "/type/gemeente"))    AS ?placeType )
  BIND( IRI(CONCAT(STR(?pit), "/sourcelabel/1"))    AS ?srcLabel )
}
