#+ name: Query-6-1-1-1-4-1-1
#+ description: Rechtstreeks uit PoolParty. Graph wegwerken
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>

SELECT DISTINCT * WHERE {
SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/rn> {
  {<https://data.cultureelerfgoed.nl/term/id/rn/fea024ba-83a0-4418-afbe-3b7b4588797e> skos:broader ?narrow.}
  UNION{
  <https://data.cultureelerfgoed.nl/term/id/rn/a3dbebf9-a237-4caa-9ee6-347c9d30dd9e> skos:narrower+ ?narrow.
  }
  }
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov .
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}

    OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}
  ?functie ceo:heeftFunctieNaam ?narrow.

 BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
# BIND(year(xsd:dateTime(?jaarInschrijving)) as ?beginJaarInschrijving)
#   BIND(year(xsd:dateTime(?beginInschrijving)) as ?eindJaarInschrijving)
 
  FILTER (?jaarInschrijving >= ?beginJaarInschrijving && ?jaarInschrijving <= ?eindJaarInschrijving)
    bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
    BIND(concat(str(?beginJaarInschrijving)," - ", ?eindJaarInschrijving) AS ?periode)

SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/koop/owms/services/owms-1/sparql> {
      ?prov skos:prefLabel ?provincie . 
    }
  
  {  GRAPH graph:owms {
      ?prov skos:prefLabel ?provincie . 
    }
}    # ?prov overheid:CBSCode ?code .

  ?narrow skos:prefLabel ?label.
    
      bind(replace(?label, "\\s\\(.*\\)|\\(.*\\)", "") AS ?labels) 
    
          BIND(str(?provincie) as ?provincieLabel)
  BIND(strdt(concat(?labels, " - ", ?jaarInschrijvings, " - ", "Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>'),rdf:HTML) AS ?shapeLabel)

  BIND(if(?labels="Industrie- en poldermolen", "red", if(?labels="Molen", "purple", if(?labels="Molenaarswoning", "maroon", if(?labels="Oliemolen", "black", if(?labels="Molenaarshuis", "orange", if(?labels="Korenmolen", "gray", if(?labels="Papiermolen", "white", if(?labels="Watermolen", "aqua", if(?labels="Ondermolen", "fuchsia", if(?labels="Getijmolen", "teal", if(?labels="Weidemolen", "lime", if(?labels="Boezemmolen", "blue", if(?labels="Bovenmolen", "navy", if(?labels="Roedenloods", "crimson", "darksalmon")))))))))))))) as ?shapeColor)
  
    bind (
    if(?keuze="AHN","https://service.pdok.nl/rws/ahn3/wms/v1_0?request=getcapabilities&service=wms",
    if(?keuze="Luchtfoto","https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?request=GetCapabilities&service=wms",
    if(?keuze="BRT Achtergrondkaart", "https://service.pdok.nl/brt/top10nl/wms/v1_0?service=wms&request=getCapabilities", ""))) as ?mapEndpoint)     
 }
