#+ name: Query-3-8
#+ description: Het rapport geeft informatie over het toegepaste materiaaltechnisch onderzoek en de analysemethode, het schilderijgenre en de ondergrond van het schilderij.
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/Van-Gogh-World-Wide-RCE/services/Van-Gogh-World-Wide-RCE/sparql


prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# Geeft aan op type schilderij waarop technisch rapport betrekking heeft.
prefix crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?technisch_rapport
where {
  ?tr_uri a crm:E33_Linguistic_Object ; 
           crm:P67_refers_to ?schilderij ; 
           crm:P2_has_type/rdfs:label ?schilderij_ondergrond ;
            crm:P2_has_type/rdfs:label ?schilderij_genre ;
          crm:P2_has_type/rdfs:label ?materiaal_technisch_onderzoek_naar ;
          crm:P67_refers_to ?onderzoek ;
           crm:P1_is_identified_by ?titel_uri . 
  ?onderzoek crm:P32_used_general_technique/rdfs:label ?analysemethode .
  ?titel_uri a crm:E33_E41_Linguistic_Appellation ; 
             crm:P190_has_symbolic_content ?technisch_rapport .

}
    