#+ name: Query-1-14
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?rijksmonument ?nummer  ?omschrijving
#?geometrie
where {
  ?rijksmonument a ceo:Rijksmonument.
  ?rijksmonument ceo:rijksmonumentnummer ?nummer.
  ?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864>.
  ?rijksmonument ceo:heeftGeometrie/geo:asWKT ?geometrie.
  ?rijksmonument ceo:heeftOmschrijving ?standpunt_omschrijving.
  ?standpunt_omschrijving ceo:omschrijving ?omschrijving .
  ?standpunt_omschrijving ceo:formeelStandpunt "true"^^<http://www.w3.org/2001/XMLSchema#boolean>.

  {
    ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam <https://data.cultureelerfgoed.nl/term/id/rn/66dc967c-fb6b-4f3e-b522-80a67b6641d8>.
  }
  union
  {
    ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam <https://data.cultureelerfgoed.nl/term/id/rn/a88d2e5e-9b8e-4f46-b89b-a24d262463d3>
  }
  union
  {
    ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam <https://data.cultureelerfgoed.nl/term/id/rn/e74a7939-8793-4823-b206-1a5916bf011b>
  }
  union
  {
    # FILTER regex(?omschrijving, "eendekooi|eendenhok|eendenhuis|eendenkooi|eenden\b|^eenden", "i").
    filter regex(?omschrijving, "neo-gotisch|neo-gotische", "i").
  }
}
order by ?nummer