#+ name: Query-1-13
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/kamarac/Verkeersbordenwegen/services/Verkeersbordenwegen/sparql

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX vbw: <https://data.verkeersborden-wegen.nl/def/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?geometry ?name ?hasId ?hasBordType
WHERE {
  ?bord rdf:type vbw:Verkeersbord .
  ?bord vbw:HasID ?hasId .
  ?bord vbw:HasBordType ?hasBordType .
  ?bord vbw:HeeftWegNaam ?name .
  ?bord geo:hasGeometry ?geometryResource .
  ?geometryResource geo:asWKT ?geometry .
}
