#+ name: Query-11-2
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/RCE-Knowledge-Graph/RCE-Knowledge-Graph/services/RCE-Knowledge-Graph/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix schema: <https://schema.org/>
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix edm: <http://www.europeana.eu/schemas/edm/>

select ?rijksmonument (MAX(?imageUrl) as ?imageUrl_) ?afbeelding ?boek ?archeologischOnderzoeksgebied ?catalogus
       ?geoRijksmonument ?geoArcheologischOnderzoeksgebied ?archeologischOnderzoeksgebiedOmschrijving
       ?rijksmonumentnummer ?straatnaam ?huisnummer ?postcode ?woonplaatsnaam ?omschrijving
       ?geoRijksmonumentLabel ?geoArcheologischOnderzoeksgebiedLabel ?geoRijksmonumentColor
       ?geoArcheologischOnderzoeksgebiedColor ?geoRijksmonumentHeight
where {
  # Grafiek voor Rijksmonumenteninstanties en Archeologische Onderzoeksgebieden
  graph graph:instanties-rce {
    # Rijksmonument
    ?rijksmonument a ceo:Rijksmonument.
    ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
    ?rijksmonument ceo:heeftBasisregistratieRelatie ?basisregistratie.
    ?basisregistratie ceo:heeftBAGRelatie ?bagrelatie.
    ?rijksmonument ceo:heeftGeometrie/geo:asWKT ?geoRijksmonument.
    ?rijksmonument ceo:heeftOmschrijving ?standpunt_omschrijving.
    ?standpunt_omschrijving ceo:omschrijving ?omschrijving .
    ?standpunt_omschrijving ceo:formeelStandpunt "true"^^<http://www.w3.org/2001/XMLSchema#boolean>.

    optional {
      ?bagrelatie ceo:openbareRuimte ?straatnaam.
      ?bagrelatie ceo:huisnummer ?huisnummer.
      ?bagrelatie ceo:postcode ?postcode.
      ?bagrelatie ceo:woonplaatsnaam ?woonplaatsnaam.
    }

    # Archeologisch Onderzoeksgebied
    ?archeologischOnderzoeksgebied a ceo:ArcheologischOnderzoeksgebied.
    ?archeologischOnderzoeksgebied ceo:heeftGeometrie/geo:asWKT ?geoArcheologischOnderzoeksgebied.
    ?archeologischOnderzoeksgebied ceo:heeftKennisregistratie/ceo:omschrijving ?archeologischOnderzoeksgebiedOmschrijving.
  }

  # Filter om te controleren of de geometrieën overlappen
  FILTER(geof:sfOverlaps(?geoRijksmonument, ?geoArcheologischOnderzoeksgebied))

  # Grafiek voor de boekeninformatie
  graph graph:bib {
    ?boek ceo:rijksmonumentnummer ?rijksmonumentnummer.
    ?boek schema:name ?boektitel.
    ?boek schema:sameAs ?catalogus.
  }

  # Grafiek voor afbeeldingen - één afbeelding per rijksmonument
  graph graph:image {
    ?afbeelding schema:about ?rijksmonument.
    ?afbeelding schema:contentUrl ?imageUrl.
    ?afbeelding edm:isShownAt ?beeldbank.
  }

  # Bind statements om extra attributen vast te stellen
  bind(strdt(concat(
    '<div style="background-color:rgba(0,0,0,.2);">',
    '   <center><img src="', COALESCE(STR(?imageUrl), 'afbeelding-niet-beschikbaar.jpg'), '" style="max-width: 200px;"></center>',
    '   <ul>',
    '      <li>Rijksmonument: <a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/', COALESCE(STR(?rijksmonumentnummer), 'Onbekend'), '" target="_blank">', COALESCE(STR(?rijksmonumentnummer), 'Onbekend'), '</a></li>',
    '      <li>Literatuur: <a href="', COALESCE(STR(?catalogus), 'Geen link beschikbaar'), '" target="_blank">', COALESCE(STR(?boektitel), 'Geen boek beschikbaar'), '</a></li>',
    '      <li>In: <a href="', STR(?beeldbank), '" target="_blank">Beeldbank</a></li>',
    '   </ul>',
    '   <br><br>',
    '</div>'
  ), rdf:HTML) AS ?geoRijksmonumentLabel)
  bind(?archeologischOnderzoeksgebiedOmschrijving as ?geoArcheologischOnderzoeksgebiedLabel)
  bind("red" as ?geoRijksmonumentColor)
  bind("green" as ?geoArcheologischOnderzoeksgebiedColor)
  bind(15 as ?geoRijksmonumentHeight)
}
GROUP BY ?rijksmonument ?afbeelding ?boek ?archeologischOnderzoeksgebied ?geoRijksmonument ?catalogus
         ?geoArcheologischOnderzoeksgebied ?archeologischOnderzoeksgebiedOmschrijving ?rijksmonumentnummer
         ?straatnaam ?huisnummer ?postcode ?woonplaatsnaam ?omschrijving ?geoRijksmonumentLabel
         ?geoArcheologischOnderzoeksgebiedLabel ?geoRijksmonumentColor ?geoArcheologischOnderzoeksgebiedColor
         ?geoRijksmonumentHeight ?beeldbank
LIMIT 3
