#+ name: Query-2-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?rijksmonumentnummer (SAMPLE(?naam) AS ?naam) (SAMPLE(?adres) AS ?adres) 
       (SAMPLE(?postcode) AS ?postcode) ?woonplaats ?gemeente (SAMPLE(?functie) AS ?functie) 
(SUBSTR((?redengevende_omschrijving), 1, 100) AS ?redengevende_omschrijving)
#(SAMPLE(xsd:string(?redengevende_omschrijving)) AS ?ro)
WHERE {
  ?rm ceo:rijksmonumentnummer ?rijksmonumentnummer .
  ?rm ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864> .
  OPTIONAL { ?rm ceo:heeftNaam/ceo:naam ?naam }
  OPTIONAL { ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:volledigAdres ?adres }
  OPTIONAL { 
    ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:postcode ?postcode_x .
    BIND(replace(str(?postcode_x), "([0-9])([A-Z])", "$1 $2") AS ?postcode)
  }
  OPTIONAL { ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:woonplaatsnaam ?woonplaats }
  ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftGemeente/skos:prefLabel ?gemeente .
  ?rm ceo:heeftOmschrijving/ceo:omschrijving ?redengevende_omschrijving.
  ?rm ceo:heeftOmschrijving/ceo:formeelStandpunt "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 #   BIND(replace(?redengevende_omschrijving, "X", " ") AS ?redengevende_omschrijving_c)
  OPTIONAL { ?rm ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functie }
  ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie <http://standaarden.overheid.nl/owms/terms/Zeeland_(provincie)> 
}
GROUP BY ?rijksmonumentnummer ?woonplaats ?gemeente ?redengevende_omschrijving
ORDER BY ?rijksmonumentnummer
