#+ name: Query-26-1
#+ description: Gebruikt voor in  python script chat_test_5.5.proef t.b.v. verbeteren redengevende omschrijving
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?rijksmonumentnummer ?redengevendeOmschrijving
WHERE {
  ?rm ceo:rijksmonumentnummer ?rijksmonumentnummer ;
      ceo:heeftOmschrijving ?om .
  ?om ceo:formeelStandpunt "1"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
      ceo:omschrijving ?redengevendeOmschrijving .
  VALUES ?rijksmonumentnummer { "519327" "524828" }
}
LIMIT 20
