#+ name: Query-6-2
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/gebedshuizen/services/gebedshuizen/sparql

PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/joop-van-der-heiden/gebedshuizen/graphs/>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>



SELECT distinct ?persoon ?shape ?shapeLabel ?shapeColor
#?shapeLabel ?persoon ?beroepLabel ?shape ?kerkLabel ?overlijdensdatum ?kerk ?grafmonument ?shapeColor ?rand
#distinct ?beroepLabel (count(?beroepLabel) as ?c) 
WHERE {
  #?reliGebouw ceox:heeftAdresgegevens/ceox:woonplaats ?woonplaats.
  #?reliGebouw ceox:rijksmonumentnummer ?rmnr.
  #?reliGebouw ceox:heeftNaam/ceox:naam ?naam.  
  #?reliGebouw ceox:heeftGeometrie/wgs84:asWKT ?destination.
  
  { select distinct * where { SERVICE <https://query.wikidata.org/sparql> {
 ?kerk wdt:P359 ?rmnr. #alleen kerken met rijksmonumentale status
        
        {?kerk wdt:P31 wd:Q16970.} #een kerk is een kerk
          union
          {?kerk wdt:P31 wd:Q2977.} #een kerk is een kathedraal
       ?kerk wdt:P625 ?shape0.
{
  ?item wdt:P119 ?kerk. #persoon is begraven in kerk
 
 }
  union
  {
          {?grafmonument wdt:P31 wd:Q6023295.} #een grafmonument is een grafmonument}
            union
            {?grafmonument wdt:P31 wd:Q173387.} #een grafmonument kan ook een graf zijn
          union
          {?grafmonument wdt:P31 wd:Q13578361} # een grafmonument kan ook een epitaf zijn
          {?grafmonument wdt:P276 ?kerk.} #een grafmonument bevindt zich in een kerk
          union
          {?grafmonument wdt:P361 ?kerk} #of grafmonument is deel van de kerk
          {?grafmonument wdt:P547 ?item .} #het grafmonument is van een bepaald persoon}
          union
          {?grafmonument wdt:P180 ?item} 
          
         
        }
        
        ?item rdfs:label ?itemLabel. 
          FILTER (LANG(?itemLabel) = "nl").
        
        #?item wdt:P106 ?beroep.#persoon heeft beroep
        #?beroep rdfs:label ?beroepLabel
        #Filter (LANG(?beroepLabel) = "nl").
        
        ?kerk rdfs:label ?kerkLabel
          FILTER (LANG(?kerkLabel) = "nl").
        #optional{ ?item wdt:P18 ?img} #plaatje persoon
        ?item wdt:P570 ?overlijdensdatum #overlijdensdatum van persoon
       # optional {?item wdt:P140 ?geloof}
        SERVICE wikibase:label { bd:serviceParam wikibase:language "nl". }
      }}}
  BIND(RAND()/4000 AS ?rand)
  Bind(replace(str(?shape0), "POINT\\(|\\)", "", "i")as ?sshape)
  Bind(xsd:decimal(STRBEFORE(?sshape, " ")) as ?wkt1a)
  Bind(xsd:decimal(STRAFTER(?sshape, " ")) as ?wkt2a)
  Bind(?wkt2a+(?rand) as ?wkt2) 
  Bind(?wkt1a+(?rand) as ?wkt1) 
  Bind(bif:st_geomfromtext(concat("POINT(",str(?wkt1)," ", str(?wkt2), ")")) as ?shape)
  
  bind(YEAR(?overlijdensdatum) as ?overlijdensjaar)
  Filter(?overlijdensjaar >= "1600"^^<http://www.w3.org/2001/XMLSchema#integer> && ?overlijdensjaar <= "1830"^^<http://www.w3.org/2001/XMLSchema#integer>)
  Filter(?rmnr != "36077") #niet kloostergang domkerk
  
  Bind(str(?itemLabel) as ?persoon) .
  BIND( if (regex(str(?persoon), "Abraham van der Hulst|Aegidius van Braam|Cornelis Cruys|Douwe Aukes|Gilles Schey|Hendrick Lonck|Isaac Sweers|Jacob van Heemskerck|Jan van Brakel|Maarten Harpertszoon Tromp|Michiel de Ruyter|Piet Hein|Willem Joseph van Ghent|Willem van der Zaen", "i"), "blue", "light grey") as ?shapeColor)
  
  BIND(strdt(concat(str(?persoon), ", overleden in ", str(?overlijdensjaar), ". Begraven in ", str(?kerkLabel), ", rijksmonument ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr),'" target="_blank">',str(?rmnr),'</a>'),rdf:HTML) AS ?shapeLabel)


} 
