#+ name: query-capturing-also-the-score-and-origi
prefix text: <http://jena.apache.org/text#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select *
where {
  (?s ?score ?literal) text:query (skos:prefLabel 'kompas' 'lang:nl').
}