#+ name: Query-7-2
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/erfgeo/sparql

prefix graph:  <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix dc:     <http://purl.org/dc/elements/1.1/>
prefix geo:    <http://www.opengis.net/ont/geosparql#>
prefix skos:   <http://www.w3.org/2004/02/skos/core#>
prefix schema: <http://schema.org/>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?geometrie ?geometrieLabel   ?s  ?naam
  ?einddatum
  ?startdatum
where {
  graph <https://linkeddata.cultureelerfgoed.nl/graph/gemeentegeschiedenis> {

    # geometrie
    ?s geo:asWKT ?geometrie .

    # gegevens die u in het label gebruikt

    ?s dc:title           ?naam .
    ?s schema:endDate     ?einddatum .
    ?s schema:startDate   ?startdatum .



    bind(
      strdt(concat(
        '<table>',
         '<tr><td><b>Naam: </b>', str(?naam), '</td></tr>',
        '<tr><td><b>Periode: </b>', str(?startdatum), ' – ', str(?einddatum), '</td></tr>',
        '</table>'
      ), rdf:HTML) as ?geometrieLabel
    )
  }
}


