#+ name: Query-2
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/cht/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT 
  ?concept 
  ?prefLabel 
  ?altLabel 
  ?broaderLabel 
  ?scopeNote
WHERE {



  GRAPH <https://data.cultureelerfgoed.nl/term/id/cht/thesaurus> {

    ?concept a skos:Concept .
    ?concept skos:inScheme <https://data.cultureelerfgoed.nl/term/id/cht/b532325c-dc08-49db-b4f1-15e53b037ec3> .

    # Labels
    OPTIONAL { 
      ?concept skos:prefLabel ?prefLabel .
      FILTER (lang(?prefLabel) = "nl")
    }

    OPTIONAL { 
      ?concept skos:altLabel ?altLabel .
      FILTER (lang(?altLabel) = "nl")
    }

    # Broader + label
    OPTIONAL { 
      ?concept skos:broader ?broader .
      ?broader skos:prefLabel ?broaderLabel .
      FILTER (lang(?broaderLabel) = "nl")
    }

    # Scope note
    OPTIONAL { 
      ?concept skos:scopeNote ?scopeNote .
      FILTER (lang(?scopeNote) = "nl")
    }

    # Zoek op prefLabel OF altLabel
    FILTER (
      CONTAINS(LCASE(STR(?prefLabel)), LCASE(STR(?zoektermlabel))) ||
      CONTAINS(LCASE(STR(?altLabel)), LCASE(STR(?zoektermlabel)))
    )
  }
}
LIMIT 100