#+ name: Query-6-10-2
#+ description: Gemaakt voor Leon om te zoeken op lengte van omschrijvingen
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/2/>

select distinct 
  ?rijksmonument
  ?nummer
  ?functielabel
  (replace(?omschrijvingen, "\n", " ") as ?omschrijvingen_schoon)
where
{
  graph graph:instanties-rce {
    ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
    ?rijksmonument ceo:rijksmonumentnummer ?nummer.
    ?rijksmonument ceo:heeftOmschrijving ?standpunt_omschrijving.
    ?standpunt_omschrijving ceo:omschrijving ?omschrijvingen.
    ?standpunt_omschrijving ceo:formeelStandpunt "true"^^xsd:boolean.

    ?rijksmonument ceo:heeftJuridischeStatus ?status .
    ?status skos:prefLabel ?statusLabel.
    ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?functie.
   ?functie skos:prefLabel ?functielabel.

    filter(strlen(?omschrijvingen) >= ?min && strlen(?omschrijvingen) <= ?max)
  }
}