#+ name: Query-11
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix owms: <http://standaarden.overheid.nl/owms/terms/>


SELECT (COUNT(?rijksmonument) as ?rmaantal) WHERE {
  GRAPH graph:instanties-rce {
    ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
#  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
    ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentNummer.
  OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?geometrie.}
    OPTIONAL {?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov .}
    OPTIONAL {?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?functieNaam.}
  ?functieNaam skos:prefLabel ?functieZooi.
  bind(replace(?functieZooi, "\\s\\(.*\\)|\\(.*\\)", "") AS ?functie)   
  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
  FILTER (?jaarInschrijving >= ?beginJaarInschrijving && ?jaarInschrijving <= ?eindJaarInschrijving)
  bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
  BIND(concat(str(?beginJaarInschrijving)," - ", ?eindJaarInschrijving) AS ?periode) 
  }
  GRAPH graph:denominatie {
    ?rijksmonument dbo:denomination ?den.
      BIND(str(?den) AS ?denominatie)
  }
  {   GRAPH graph:owms {
      ?prov skos:prefLabel ?provincie . 
   }
  } 
} LIMIT 100