#+ name: Query-9
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rn: <https://data.cultureelerfgoed.nl/term/id/rn#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?eindBouwjaars (COUNT(?rijksmonument) AS ?aantal)  
WHERE {
  GRAPH graph:instanties-rce {
  ?rijksmonument a ceo:Rijksmonument.
  ?rijksmonument ceo:heeftJuridischeStatus/skos:prefLabel ?grm.
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
  bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
  ?rijksmonument ceo:heeftMonumentAard <https://data.cultureelerfgoed.nl/term/id/rn/fc966a68-8863-4970-a83e-110f96006c21>.
  ?rijksmonument ceo:heeftGebeurtenis ?gebeurtenis.
  ?gebeurtenis ceo:heeftGebeurtenisNaam/skos:prefLabel ?gebeurtenisNaam.
  ?gebeurtenis ceo:heeftDatering ?datering.
  ?datering ceo:heeftBeginDatering ?beginDatering.
  ?datering ceo:heeftEindDatering ?eindDatering.
  ?beginDatering ceo:datum ?beginDatum.
    BIND(year(xsd:dateTime(?beginDatum)) as ?beginBouwjaar)
  bind(concat(str(?beginBouwjaar)) as ?beginBouwjaars)
  ?eindDatering ceo:datum ?eindDatum .
    BIND(year(xsd:dateTime(?eindDatum)) as ?eindBouwjaar)
  bind(concat(str(?eindBouwjaar)) as ?eindBouwjaars)
  FILTER (CONTAINS(?gebeurtenisNaam, "vervaardiging"))
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
}
}
GROUP BY ?eindBouwjaars ?aantal
ORDER BY ?eindBouwjaars