#+ name: Query-8
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX sdo: <https://schema.org/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>

SELECT distinct ?woonplaats ?naam ?omschrijving ?eventMedia WHERE {
 ?reliGebouw ceox:heeftAdresgegevens/ceox:woonplaats ?woonplaats.
  ?reliGebouw ceox:rijksmonumentnummer ?rmnr.
 ?reliGebouw ceox:heeftNaam/ceox:naam ?naam.
  BIND(replace (str(?naam), "(\\(|\\)|\\-)", "") AS ?naamN) .
  Bind(strbefore(?NaamN,",") as ?naam1) 
  Bind(strafter(?NaamN,",") as ?naam2)
 
   
{select ?s ?label ?woonplaats ?desc ?eventMedia
    where{ SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/HackaLOD/GVN/services/GVN/sparql>{
   ?s dct:isPartOf <https://data.netwerkdigitaalerfgoed.nl/hackalod/gvn/TopografievanNederland>.
 ?s dc:description ?desc.
 ?s dct:spatial ?woonplaats.
 ?s dct:source ?eventMedia.
  ?s rdfs:label ?label
        Filter regex(?desc,  "interieur", "i")
        Filter regex(?desc, "kerk", "i")
            
      }}}
  bind(concat(?desc, " ", ?label) as ?omschrijving)
  Filter regex(?omschrijving, ?naam, "i")
  
       BIND(strdt(concat('<img src="',str(?eventMedia),'" style="max-width: 100px;">','</a>','</p>',"Titel: ",?naam,'</p>','</p>', "Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr),'" target="_blank">',str(?rmnr),'</a>'),rdf:HTML) AS ?widget)

} 
