#+ name: Query-5-3
#+ description: This SPARQL query retrieves distinct rijksmonument numbers and their corresponding rijksmonument instances, excluding those with a specific juridical status, and generates clickable URIs for each rijksmonument number. The results are ordered based on the rijksmonument number.
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql
#+ description: This SPARQL query retrieves distinct rijksmonument numbers and their corresponding rijksmonument instances, excluding those with a specific juridical status, and generates clickable URIs for each rijksmonument number. The results are ordered based on the rijksmonument number.
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>  # Prefix for the CEO vocabulary
PREFIX geo: <http://www.opengis.net/ont/geosparql#>  # Prefix for the GeoSPARQL vocabulary
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  # Prefix for the RDF vocabulary
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  # Prefix for the RDFS vocabulary
#2023-06016=46

# The following line retrieves all the distinct values for the variables rijksmonumentnummer, rijksmonument, and uri
SELECT DISTINCT ?rijksmonumentnummer ?rijksmonument (URI(CONCAT("https://monumentenregister.cultureelerfgoed.nl/monumenten/", URI(?rijksmonumentnummer))) AS ?uri) WHERE {

  # Retrieve all instances of the ceo:Rijksmonument class
  ?rijksmonument a ceo:Rijksmonument.

  # Optional pattern to retrieve the geometrical shape of the rijksmonument using the geo:asWKT property
  OPTIONAL { ?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape }

  # Retrieve the value of the ceo:rijksmonumentnummer property for each rijksmonument
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.

  # Exclude rijksmonuments that have the ceo:heeftJuridischeStatus property with the given URI
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}

  # Filter out rijksmonuments that do not have a geometrical shape
  FILTER (!bound(?shape))

  # Create a URI for each rijksmonumentnummer using the CONCAT function
 # BIND(CONCAT("https://monumentenregister.cultureelerfgoed.nl/monumenten/", URI(?rijksmonumentnummer)) AS ?uri)
}

# Order the results based on the rijksmonumentnummer variable
ORDER BY ?rijksmonumentnummer
