#+ name: Query-1-9
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?class
       (GROUP_CONCAT(REPLACE(str(?objectproperty), "^https://linkeddata.cultureelerfgoed.nl/def/ceo(.+)", "$1"); SEPARATOR=" ") AS ?objectproperties)
       (GROUP_CONCAT(REPLACE(str(?dataproperty), "^https://linkeddata.cultureelerfgoed.nl/def/ceo(.+)", "$1"); SEPARATOR=" ") AS ?dataproperties)
WHERE {
  {
    ?dataproperty rdf:type owl:DatatypeProperty.
    ?dataproperty rdfs:domain ?class.
    BIND(?dataproperty AS ?datapropertyPrefix)
    BIND (" " AS ?objectproperty)
  }
  UNION
  {
    ?objectproperty rdf:type owl:ObjectProperty.
    ?objectproperty rdfs:domain ?class.
    BIND(?objectproperty AS ?objectpropertyPrefix)
    BIND (" " AS ?dataproperty)
  }
  
  OPTIONAL {
    ?class rdfs:label ?classLabel.
    ?objectproperty rdfs:label ?objectpropertyLabel.
    ?dataproperty rdfs:label ?datapropertyLabel.
  }
}
GROUP BY ?class
