#+ name: Query-21
#+ description: Welke properties zijn registergegevens (14)
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?ceoProperties ?comment ?registerGegeven
where {
	?ceoProperties ceo:registergegeven  ?o .
 ?ceoProperties rdfs:comment ?comment.
  FILTER (!REGEX(?comment, "register", "i"))
    ?ceoProperties rdfs:comment ?registerGegeven.
  FILTER REGEX(?registerGegeven, "register", "i")
}











