#+ name: Query-44
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT  ?s ?rm
       (REPLACE(?description, "\n", " ") AS ?descriptionschoon)

WHERE {
  ?s ceo:heeftOmschrijving/ceo:omschrijving ?description.
  ?s ceo:rijksmonumentnummer ?rm.
  FILTER (
    CONTAINS(LCASE(?description), "uurwerken") && !CONTAINS(LCASE(?description), "wijzerplaten")
  )
}

ORDER BY ?rm