#+ name: Query-18
#+ description: Eerste opzet
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/gebedshuizen/services/gebedshuizen/sparql

PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
PREFIX wd:<http://www.wikidata.org/entity/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX ceo:<https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX wgs84:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geo:<http://www.opengis.net/ont/geosparql#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema:<https://schema.org/>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>


SELECT ?grafmonument (group_concat(distinct ?persoon; separator=", ") as ?personen) (group_concat(distinct ?beeldhouwer; separator=",") as ?beeldhouwers)  (strdt(concat("Rijksmonument ", '<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmnr),'" target="_blank">',str(?rmnr),'</a>', '<p>', "Begraven: ", ?personen, '<p>', "Graf ontworpen door: ", ?beeldhouwers, '<p>', "In opdracht van ", ?opdrachtgever, '<p>', "In het jaar ", ?dat),rdf:HTML) AS ?shapeLabel)  ?shape ?shapeColor

WHERE {

  ?rijksmonument ceox:rijksmonumentnummer ?rmnr. 
 
  ?rijksmonument ceox:heeftGeometrie/wgs84:asWKT ?_shape.
  bind(bif:st_geomfromtext(?_shape) as ?shape)
  ?rijksmonument ceox:heeftDenominatie/ceox:heeftDenominatieNaam ?den.
    ?den skos:prefLabel ?denominatie ;
                 rnce:hasChurchMovement/skos:prefLabel ?stroming.
  ?rijksmonument ceox:hoortBij ?grafmonument.
  ?grafmonument ceox:IsTerNagedachtenisVan/ceox:naam ?persoon.
  optional {?grafmonument ceox:heeftGebeurtenis/ceox:heeftActorEnRol/ceox:naam ?beeldhouwer. }
  optional{ ?grafmonument ceox:opdrachtgever ?opdrachtgever.}
  ?grafmonument ceox:heeftGebeurtenis/ceox:heeftDatering/ceox:datering ?dat.
  
  Bind( xsd:integer(?dat) as ?jaar)
  Filter (?jaar <1830)
 
  # BIND(replace(str(?bouwperiode),"( ev| ca)", "") AS ?event1)
   #BIND(replace(str(?event1),"(^[^( |\\-)]*( |\\-))", "") AS ?event2)
  

  
  BIND(if(?stroming="Christendom, Evangelisch", "red", if(?stroming="Christendom, Katholiek", "purple", if(?stroming="Christendom, Oecumenisch", "maroon", if(?stroming="Christendom, Overig", "black", if(?stroming="Christendom, Protestants", "orange", if(?stroming="Christendom, Reformatorisch", "gray", if(?stroming="Christendom, Vrijzinnig", "white", if(?stroming="Jodendom", "green", "fuchsia")))))))) as ?shapeColor)
} 
order by ?eventStart
#LIMIT 100

