#+ name: Query-51
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/tooi/sparql

prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix tooi:  <https://identifier.overheid.nl/tooi/def/ont/>

select DISTINCT ?gemeente
  ?label
  ?gemeentecode
  ?organisatiecode
  ?officieleNaamExclSoort
  ?owms
where {
  graph <https://linkeddata.cultureelerfgoed.nl/rce/tooi/graphs/default-gemeenten> {
    ?gemeente rdf:type          tooi:Gemeente ;
      rdfs:label        ?label ;
      tooi:gemeentecode ?gemeentecode ;
      tooi:organisatiecode ?organisatiecode ;
      tooi:officieleNaamExclSoort ?officieleNaamExclSoort ;
      tooi:owmsId ?owms.
  }
}
