#+ name: Query-2-7
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?p (SAMPLE(?value) AS ?example) WHERE {
  ?p a owl:DatatypeProperty .
  ?s ?p ?value .
  
  FILTER (strstarts(str(?p), "https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}
GROUP BY ?p
