#+ name: Query-32-1
#+ description: Stand 14-08-2023 -> 33
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
#+ the query retrieves the municipality name, the monument number, and the residence name for cultural heritage sites using the specified relationships and properties.
#+ https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>

SELECT ?rm ?gemeente_rce ?opvolger_owms ?eindDatum ?rmn
WHERE {
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce> {
  ?rm a ceo:Rijksmonument.
  ?rm ceo:heeftJuridischeStatus rn:b2d9a59a-fe1e-4552-9a05-3c2acddff864 .
  ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftGemeente ?gemeente.
  ?rm ceo:rijksmonumentnummer ?rmn.
  }
  GRAPH graph:owms {
    ?gemeente skos:prefLabel ?gemeente_rce.
  ?gemeente owms:successor ?opvolger .
  ?gemeente owms:endDate ?eindDatum.
   ?opvolger skos:prefLabel ?opvolger_owms. 
  }
}
