#+ name: Query-6-10-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

# We definiëren de gebruikte prefixes voor namespaces aan het begin van de query.
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rn: <https://data.cultureelerfgoed.nl/term/id/rn/>

# We selecteren de variabelen die we willen ophalen in de resultaten.
SELECT ?rijksmonument ?nummer ?omschrijving ?standpunt_omschrijving

# Hier begint de query voor het ophalen van de gegevens.
WHERE 
{
  GRAPH graph:instanties-rce {
    # We halen informatie op over rijksmonumenten uit een specifieke grafiek.

    # We filteren op basis van de inschrijvingsdatum, het rijksmonumentnummer en de omschrijving.
    ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
    ?rijksmonument ceo:rijksmonumentnummer ?nummer.
    ?rijksmonument ceo:heeftOmschrijving ?standpunt_omschrijving.
    ?standpunt_omschrijving ceo:omschrijving ?omschrijving .
    ?standpunt_omschrijving ceo:formeelStandpunt "true"^^<http://www.w3.org/2001/XMLSchema#boolean>.

}}