#+ name: Query-3-9
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/bibliotheek/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix schema: <https://schema.org/>
prefix edm: <http://www.europeana.eu/schemas/edm/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select ?publicatie ?name (group_concat(?auteur; separator=", ") as ?authors) where {
  graph graph:bib {
    ?publicatie schema:keywords ?keywords.
    optional {
      ?publicatie schema:author/schema:name ?auteur.
    }
    ?publicatie schema:name ?name.
  }
} group by ?name ?publicatie
limit 10
