PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?rijksmonumentnummer ?actor WHERE {
  ?rm a  ceo:Rijksmonument ; ceo:rijksmonumentnummer ?rijksmonumentnummer ; ceo:heeftGebeurtenis/ceo:heeftActorEnRol ?actorRol . ?actorRol ceo:heeftActor ?actor
}