#+ name: Query-2-9
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT *
WHERE {
  {
    ?property rdf:type owl:DatatypeProperty.
    ?property rdfs:domain ?class.
  }
  UNION
  {
    ?property rdf:type owl:ObjectProperty.
    ?property rdfs:domain ?class.
  }
}
ORDER BY ?class

