#+ name: Query-11-3
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/patrick-mout/Archeologisch-Basis-Register/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?artefact ?beginPeriode ?eindPeriode
WHERE {
  <https://data.cultureelerfgoed.nl/term/id/abr/22cbb070-6542-48f0-8afe-7d98d398cc0b> skos:narrower+ ?artefactUri .
  ?artefactUri skos:prefLabel ?artefact ;
               rnce:hasBeginPeriodAbr/skos:prefLabel ?beginPeriode ;
               rnce:hasEndPeriodAbr/skos:prefLabel ?eindPeriode
}
ORDER BY ?artefactUri
LIMIT 1

