#+ name: Query-30
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT *
WHERE {
  SERVICE <https://api.labs.kadaster.nl/datasets/dst/kkg/services/default/sparql> {
    ?Verblijfsobject_kadaster <https://data.kkg.kadaster.nl/sor/model/def/hoofdadres> ?hoofdadres ; <https://data.kkg.kadaster.nl/sor/model/def/maaktDeelUitVan> ?pand .
    ?hoofdadres <https://data.kkg.kadaster.nl/sor/model/def/ligtAan> ?ligtaan ;
             <https://data.kkg.kadaster.nl/sor/model/def/huisnummer> ?huisnummerBAG ; 
                <https://data.kkg.kadaster.nl/sor/model/def/postcode> ?postcode .
    ?ligtaan skos:prefLabel ?straat_BAG .  BIND(STR(?huisnummerBAG) AS ?huisnummer)
              
  } 
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer ;
                 
                 ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie ?bag . ?bag ceo:postcode ?postcode ; ceo:huisnummer ?huisnummer ; 
                 ceo:verblijfsobjectIdentificatie ?VerblijfsID_RCE 

} limit 100