#+ name: Query-2-3-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix schema: <https://schema.org/>
prefix skos:   <http://www.w3.org/2004/02/skos/core#>
prefix ceo:    <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix graph:  <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix owms:   <https://linkeddata.cultureelerfgoed.nl/graph/owms>

select
  ?rijksmonument
  (iri(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/", ?rijksmonumentnummer)) as ?monumentenregister)
  (iri(concat("https://download.memorix.nl/maior/rce/",replace(replace(str(?image),".*fullsize/",""),"\\.jpg.*",""))) as ?downloadUrl)
  ?rijksmonumentnummer
  ?image
  ?monumentaard
  ?juridischeStatus
  ?provincie
  ?gemeente
  ?straat
  ?huisnummer
  ?adres
  ?postcode
  ?woonplaatsnaam
  ?functie
  ?datumInschrijving
where {

  ########################################
  # BASIS: rijksmonument
  ########################################
  graph graph:instanties-rce {

    ?rijksmonument
      ceo:rijksmonumentnummer ?rijksmonumentnummer ;
#      ceo:datumInschrijvingInMonumentenregister ?datumInschrijving ;
     ceo:heeftJuridischeStatus ?status ;
      ceo:heeftMonumentAard ?aard ;
      ceo:heeftBasisregistratieRelatie ?basisrel .

    ?basisrel ceo:heeftProvincie ?prov ;
      ceo:heeftGemeente  ?gem .

    ?aard   skos:prefLabel ?monumentaard .
    ?status skos:prefLabel ?juridischeStatus .
  }

  ########################################
  # AFBEELDINGEN (koppeling!)
  ########################################
  optional {
    service <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/afbeeldingen2/sparql> {
      ?imgObj a schema:ImageObject ;
        schema:about ?rijksmonument ;
        schema:contentUrl ?image .
    }
  }

  ########################################
  # OWMS labels
  ########################################
  graph owms: {
    ?prov skos:prefLabel ?provincie .
    ?gem  skos:prefLabel ?gemeente .
  }

  ########################################
  # WOONPLAATS
  ########################################
  optional {
    {
      select ?rijksmonument
        (group_concat(distinct ?wp; separator=", ") as ?woonplaatsnaam)
      where {
        graph graph:instanties-rce {
          ?rijksmonument
            ( ceo:heeftBasisregistratieRelatie
              | ceo:bevatObject/ceo:heeftBasisregistratieRelatie )
            / ceo:heeftBAGRelatie
            / ceo:woonplaatsnaam
            ?wp .
        }
      }
      group by ?rijksmonument
    }
  }

  ########################################
  # ADRES
  ########################################
  optional {
    {
      select ?rijksmonument
        (sample(?straat_) as ?straat)
        (sample(?huisnummer_) as ?huisnummer)
        (sample(?adres_) as ?adres)
        (sample(?postcodeNetto) as ?postcode)
      where {
        graph graph:instanties-rce {

          ?rijksmonument
            ( ceo:heeftBasisregistratieRelatie
              | ceo:bevatObject/ceo:heeftBasisregistratieRelatie )
            / ceo:heeftBAGRelatie
            ?bag .

          optional {
            ?bag ceo:openbareRuimte ?straat_
          }
          optional {
            ?bag ceo:huisnummer ?huisnummer_
          }
          optional {
            ?bag ceo:volledigAdres ?adres_
          }
          optional {
            ?bag ceo:postcode ?pc .
            bind(replace(str(?pc), "([0-9]{4})([A-Z]{2})", "$1 $2") as ?postcodeNetto)
          }
        }
      }
      group by ?rijksmonument
    }
  }

  ########################################
  # FUNCTIE
  ########################################
  optional {
    {
      select ?rijksmonument
        (group_concat(distinct ?functieClean; separator=", ") as ?functie)
      where {

        graph graph:instanties-rce {
          ?rijksmonument
            ceo:heeftOorspronkelijkeFunctie ?fRel .

          ?fRel ceo:formeelStandpunt true ;
            ceo:heeftFunctieNaam ?fnConcept .
        }

        graph graph:bebouwdeomgeving {
          ?fnConcept skos:prefLabel ?fnLabel .
        }

        bind(replace(?fnLabel, "\\s*\\(.*?\\)", "") as ?functieClean)
      }
      group by ?rijksmonument
    }
  }
}
limit 20000