#+ name: Query-5-4-1-2
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix dc: <http://purl.org/dc/elements/1.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix sor: <https://data.kkg.kadaster.nl/sor/model/def/>
prefix kad: <https://data.kkg.kadaster.nl/kad/model/def/>
prefix owms: <http://standaarden.overheid.nl/owms/terms/>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix geo: <http://www.opengis.net/ont/geosparql#>

select distinct * where {
  service <https://api.labs.kadaster.nl/datasets/kadaster/kkg/services/kkg/sparql> {
    ?koppeling
      rdf:object ?nummeraanduiding;
      rdf:subject ?perceel1.
    ?perceel1
      kad:akrAanduiding ?akrAanduiding;
      sor:hoortBij ?nummeraanduiding;
      sor:oppervlakte ?kadgroottePerceel;
      sor:sectie ?sectie;
      sor:perceelnummer ?perceel.
  }

  graph graph:instanties-rce {
   ?cho a ceo:Rijksmonument .
   ?cho ceo:heeftJuridischeStatus rn:b2d9a59a-fe1e-4552-9a05-3c2acddff864.
  ?cho ceo:rijksmonumentnummer ?rm.
      bind (xsd:integer(?perceel) as ?integerPerceel)
    ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:perceelnummer ?integerPerceel.
 #   ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:sectie ?sectie.
  #  ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:postcode ?postcode.
  #  ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:gemeentenaam ?gemeentenaam.
  #  ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:gemeentecode ?kadastraleGemeentecode.
  #  optional {
  #    ?cho ceo:heeftBasisregistratieRelatie/ceo:heeftGemeente ?gemeente .
  #  }
  #  graph graph:owms {
  #    ?gemeente owms:CBSCode ?cbscode.
   # }

  }


  # bind(concat(str(?akrAanduiding), '-', str(?sectie), '-', str(?perceelnummer)) as ?kadAanduiding)
  # bind(coalesce(?kadAanduiding, 'Appartementsrecht') as ?kadAanduidingFiltered)
}
limit 100
