#+ name: Query-28
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/colonialheritage/colonialobjects/services/colonialobjects/sparql

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?sub (GROUP_CONCAT(DISTINCT ?genre; SEPARATOR="|") as ?genres)
           (GROUP_CONCAT(DISTINCT ?keywords; SEPARATOR="|") as ?allKeywords)
           (GROUP_CONCAT(DISTINCT ?material; SEPARATOR="|") as ?materials)
           (GROUP_CONCAT(DISTINCT ?artform; SEPARATOR="|") as ?artforms)
WHERE {
  ?sub a schema:VisualArtwork.
  OPTIONAL {
    ?sub schema:genre ?genre.
    ?sub schema:keywords ?keywords.
    ?sub schema:material ?material.
    ?sub schema:artform ?artform.
  }
}
GROUP BY ?sub
