#+ name: Query-12-3
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>


select distinct (CONCAT(?p1Name, " -> ", ?p2Name, " -> ", ?propertyName, " -> ",?value) as ?propertyPath) ?value where {
  ?rijksmonument a ceo:Rijksmonument ;
                  ?p1 ?o1 .
  ?o1 ?p2 ?o2 .
  ?o2 ?propertyName ?value .
  ?p1 rdfs:label ?p1Name .
  ?p2 rdfs:label ?p2Name .
  ?rijksmonument ceo:rijksmonumentnummer "1" .
}
