#+ name: Query-17-2-1-1-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select distinct ?choi (uri(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/", ?rijksmonumentnummer)) as ?monumentenregister) ?rijksmonumentnummer ?hoofdcategorie ?subcategorie ?vunctie ?functie ?functie2 ?TFU ?TBW
where {
  graph graph:instanties-rce {
    ?choi rdf:type ceo:Rijksmonument.
    ?choi ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864>.
    ?choi ceo:rijksmonumentnummer ?rijksmonumentnummer.
    ?choi ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving_.
    optional {
      ?choi ceo:heeftOorspronkelijkeFunctie ?functies_.
      ?functies_ ceo:heeftFunctieNaam ?functies.
      ?functies skos:prefLabel ?functiel.
      ?functies_ ceo:formeelStandpunt "1"^^xsd:boolean.
    }
  }

  graph graph:bebouwdeomgeving {
    optional {
      ?functies skos:hiddenLabel ?label.
    }
  }

  BIND (IF(BOUND(?label) && strlen(str(?label)) < 2, ?functiel, "") AS ?hoofdcategorie)
  BIND (IF(BOUND(?label) && strlen(str(?label)) = 2, ?functiel, "") AS ?subcategorie)
  BIND (IF(BOUND(?hoofdcategorie) && ?hoofdcategorie != "", "", ?functiel) AS ?filteredFunctie1)
  BIND (IF(BOUND(?subcategorie) && ?subcategorie != "", "", ?filteredFunctie1) AS ?functie)
  BIND (IF(CONTAINS(STR(?label), "_TFU"), "functie", "") AS ?TFU)
  BIND (IF(CONTAINS(STR(?label), "_TBW"), "type", "") AS ?TBW)

  # Lijst van specifieke functies
  VALUES ?specifiekeFunctie {"Turbinehal" "Hoogspanningsmast" "Gasfabriek" "Pompstation" "Gashouder" 
                             "Schakelstation" "Pompgebouw(M05)" "Elektriciteitscentrale" "Zuiveringshuis" 
                             "Waterzuivering" "Filtergebouw" "Hoogtorenstation" "Telescopische gashouder" 
                             "Gasmengstation" "Spreng(M)" "Retort" "Regulateurshuis" "Transformatorgebouw" 
                             "Waterstation(M)" "Watertoren"}

  # Stel ?functie2 in op "Nutsbedrijven" als ?functie in de lijst van specifieke functies zit
  BIND (IF(?functie IN (?specifiekeFunctie), "Nutsbedrijven", "") AS ?functie2)
  BIND(COALESCE(IF(BOUND(?functie2) && ?functie2 != "", CONCAT(?functie2, "; ", ?functie), ?functie), ?functie) AS ?vunctie)


}
