#+ name: Query-2-10
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/kunstcollecties-kc-2/services/kunstcollecties-kc-2/sparql

SELECT ?class ?property (COUNT(*) AS ?gebruik)
WHERE {
  GRAPH ?g {
    ?s a ?class ;
       ?property ?o .
  }
}
GROUP BY ?class ?property
ORDER BY DESC(?class)
