#+ name: Query-2-8
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?class (CONCAT("<", STR(?example), ">") AS ?exampleValue) WHERE {
  ?class a owl:Class .
  ?class skos:example ?example .
  
  FILTER (strstarts(str(?class), "https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}
GROUP BY ?class
ORDER BY ?class
