#+ name: Query
#+ description: Deze query transformeert rd-wkt geometrie naar gewoon wkt geometrie.
#- Deze query gebruikt afstand.
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
select ?wkt1 ?wkt2 ?wkt2Color ?wkt1Color ?sub2 where {
graph <https://linkeddata.cultureelerfgoed.nl/graph/linies> {
?sub1 ceo:asWKT-RD ?rd1.
    bind(strdt(concat("<http://www.opengis.net/def/crs/EPSG/0/28992> ", str(?rd1)), geo:wktLiteral) as ?shape)
     bind(bif:ST_Transform(?shape, 4326) as ?wkt1)
}
   graph <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce> {
   
?sub2 ceo:heeftGeometrie/geo:asWKT ?wkt2
 }
  bind ("red" as ?wkt1Color)
  bind ("orange" as ?wkt2Color)
 FILTER((geof:distance(?wkt1,?wkt2, uom:meter)) < 0.5 )
}






Limit 3