#+ name: Query-15-1
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?volgnummer ?rijksmonumentnummer ?datumInschrijvingInMonumentenregister ?adres ?gemeente ?omschrijving 

WHERE {
  VALUES ?rijksmonumentnummer 
  {"2041" "11630" "12646" "25736" "25735"} .
  ?rm a ceo:Rijksmonument ; 
      ceo:datumInschrijvingInMonumentenregister ?datumInschrijvingInMonumentenregister ;
      ceo:rijksmonumentnummer ?rijksmonumentnummer ;
      ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:volledigAdres ?adres ;
      ceo:heeftBasisregistratieRelatie/ceo:heeftBRKRelatie/ceo:gemeentenaam ?gemeente ;
      ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving . 
  MINUS {?rm ceo:heeftOmschrijving/ceo:formeelStandpunt "0"^^xsd:boolean } . BIND(?rijksmonumentnummer as ?volgnummer)
} 
order by ?rijksmonumentnummer
