#+ name: Query-17
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/Aardbevingen/services/aardbevingen/sparql

PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
#DECLAREER PREFIXES
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix overheid: <http://standaarden.overheid.nl/owms/terms/> 
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

SELECT *
#?shape_ab ?shape_rm ?shape_abColor ?shape_rmColor ?ab ?rm ?dist
#?magnitude ?datum ?locatieNaam_ab ?shape_ab ?shape_rm ?locatieNaam_rm ?type (str(?rm_n) AS ?rijksmonumentnummer)
 {
 # ?ab <https://data.netwerkdigitaalerfgoed.nl/ca8725/def/Magnitude> ?magnitude .
 # ?ab <https://data.netwerkdigitaalerfgoed.nl/ca8725/def/YYMMDD> ?datum_ab.
 # ?ab geo:asWKT ?shape_abs .
 # BIND(strdt(?shape_abs, geo:wktLiteral) as ?shape_ab)
 # ?ab <https://data.netwerkdigitaalerfgoed.nl/ca8725/def/LOCATION> ?locatieNaam_ab .

  SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql> {
  ?rm a ceo:Rijksmonument .
  ?rm ceo:rijksmonumentnummer ?rm_n . 
  ?rm ceo:heeftMonumentAard ?aard .
  ?rm ceo:heeftGeometrie/geo:asWKT ?shape_rm.
  ?rm ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie <http://standaarden.overheid.nl/owms/terms/Groningen_(provincie)> .
  ?rm ceo:heeftLocatieAanduiding/ceo:locatienaam ?locatieNaam_ab .
}
  #   bind("green" as ?shape_abColor)
    bind("purple" as ?shape_rmColor)
   #{BIND (geof:distance(?shape_rm,?shape_ab, uom:metre) as ?dist)
  # FILTER((geof:distance(?shape_rm,?shape_ab, uom:meter)) < 1000 )
  BIND(<https://haleconnect.com/ows/services/org.874.7e01e60c-8887-425c-af9b-e2cf6af9181b_wms?SERVICE=WMS&Request=GetCapabilities> as ?mapEndpoint)

}
LIMIT 250