#+ name: Query-48
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT 
  DISTINCT ?rijksmonumentnummer ?monumentnaam ?geometrie
  #(COUNT(DISTINCT ?rm_uri) AS ?aantal)
WHERE {
  ?rm_uri ceo:rijksmonumentnummer ?rijksmonumentnummer ; ceo:heeftJuridischeStatus 
    <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864> ; 
          ceo:heeftMonumentAard <https://data.cultureelerfgoed.nl/term/id/rn/fc966a68-8863-4970-a83e-110f96006c21> ;
          ceo:heeftGeometrie/ceo:asWKT-RD ?geometrie .
  OPTIONAL { ?rm_uri ceo:heeftNaam/ceo:naam ?monumentnaam } 
}
LIMIT 10000 OFFSET 0
