#+ name: Query-4-1-2
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?aantalRijksmonumenten ?top_20_gemeenten (count(distinct(?rijksmonument)) as ?aantal_rijksmonumenten)

WHERE {
 
  GRAPH graph:instanties-rce {
  ?rijksmonument a ceo:Rijksmonument;
  ceo:heeftBasisregistratieRelatie/ceo:heeftGemeente ?gemeenteCheck2;
  ceo:datumInschrijvingInMonumentenregister ?inschrijving.
    MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
}
 ?gemeenteCheck2 skos:prefLabel ?top_20_gemeenten
  BIND(year(xsd:dateTime(?inschrijving)) as ?jaarInschrijving)
 
  BIND (
   IF(?jaarInschrijving > 1960 && ?jaarInschrijving <= 1973, "Piek 1", 
    IF(?jaarInschrijving >= 1997 && ?jaarInschrijving <= 2002, "Piek 2", "Buiten pieken")) AS ?aantalRijksmonumenten)
      

   FILTER(LANG(?top_20_gemeenten) = "nl").
  
 FILTER regex(?top_20_gemeenten, "(^Amsterdam$|^Rotterdam$|^Maastricht$|Gravenhage$|^Leiden$|^Utrecht$|^Haarlem$|^Groningen$|^Delft$|^Leeuwarden$|^Dordrecht$|^Middelburg$|^Arnhem$|Hertogenbosch$|^Breda$|^Deventer$|^Nijmegen$|^Amersfoort$|^Gouda$|^Zwolle$)", "i") 
     
  
}


order by desc(?aantal_rijksmonumenten) 
