#+ name: Query-42
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/thesauri/services/thesauri/sparql

prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix text: <http://jena.apache.org/text#>
select distinct ?s ?lbl
where {
  ?s text:query ( skos:prefLabel skos:altLabel skos:scopeNote ?lbl) ;

}