#+ name: Query-6-5
#+ description: Wat is van alle properties het domein?
#- Check ceo en cho.
#- Vanuit ceo inzicht in het model
#- Vanuit cho, klopt de uitwerking
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?property ?domain
WHERE
{
?property rdfs:domain ?domain
FILTER (strstarts(str(?property),"https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}
order by ?domain
