#+ name: Query-16-1
#+ description: Query waarbij in de omschrijving van het compex gezocht wordt naar het woord "buitenplaats".
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?complex ?complexnummer ?naam ?omschrijving ?hoofdobjectnummer WHERE {
 GRAPH graph:instanties-rce { 
  ?complex a ceo:Complex .
  ?complex ceo:complexnummer ?complexnummer.
  ?complex ceo:heeftHoofdobject ?hoofdobject.
 OPTIONAL{ ?complex ceo:heeftKennisregistratie/ceo:naam ?naam.}
  ?complex ceo:heeftKennisregistratie/ceo:omschrijving ?omschrijving.
#  Filter regex(?omschrijving, "buitenplaats", "i")
  ?complex ceo:heeftRijksmonument ?rijksmonument.
  ?hoofdobject ceo:rijksmonumentnummer ?hoofdobjectnummer.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.

  }
 
}#LIMIT 2