# gebaseerd op query Marije Timmermans

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX overheid: <http://standaarden.overheid.nl/owms/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX schema:<https://schema.org/>

SELECT distinct *
#?linkRijksmuseum ?titel ?datering ?omschrijving

WHERE 
{
  {  SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/Rijksmuseum/collection/services/collection/sparql>{
  ?linkRijksmuseum dc:creator/skos:prefLabel "Rietveld, Gerrit Thomas"@nl;
                                                       dc:description ?description;
                                                        dct:created ?eventDate;
                                                        dc:title ?eventLabel;
                                                        dct:spatial ?spat.
    filter(lang(?eventLabel)='nl' && lang(?description)='nl'&& lang(?eventDate)='nl')
      
# filter regex(iri(str(?spat)), "http://sws.geonames.org") . 
    ?spat wgs84:lat ?lat.
      ?spat wgs84:long ?long.
    
   

    }

   
    # BIND(RAND()/200 AS ?rand)
   # Bind(xsd:decimal(?longn) as ?wkt1ni)
   # Bind(xsd:decimal()+(?rand) as ?wkt) 
   Bind(bif:st_geomfromtext(concat("POINT(",str(4.885278)," ", str(52.36), ")")) as ?shape)

   BIND(strdt(concat('<a href="',(?linkRijksmuseum),'" target="_blank">',str(?eventLabel),'</a>', " uit ", ?eventDate,".", '<p>',  ?description),rdf:HTML) AS ?shapeLabel)
    Bind("orange" as ?shapeColor)
      
    filter regex(?eventDate, "^[0-9]", "i")}
  union
  {
      GRAPH graph:instanties-rce {
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving.
    ?rijksmonument ceo:heeftOmschrijving/ceo:formeelStandpunt "1"^^xsd:boolean.
       ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:volledigAdres ?straat .
      ?rijksmonument ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:woonplaatsnaam "Utrecht" .
            optional{?rijksmonument ceo:heeftNaam/ceo:naam ?naamrm.}
      optional{?rijksmonument ceo:heeftStijlEnCultuur/ceo:heeftStijlEnCultuurNaam/skos:prefLabel ?stijlrm.}
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
  OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}

    
    
   #selecteer alle monumenten van Rietveld in de actor en beschrijving 
    {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld ; Stad Amsterdam"}
    union
        {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G.Th. ; Utrecht"}
   union
   {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G.T. ; Stad Utrecht"}
     union
   {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G. ; Noord-Holland"}
    union
    {Filter regex(?omschrijving, "gerrit rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Th\\. Rietveld", "i")}
        union
    {Filter regex(?omschrijving, "G\\. Rietveld", "i")}
            union
    {Filter regex(?omschrijving, "Th\\.Rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Gerrit Thomas Rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Th\\.Rietveld", "i")}

 }
 

 SERVICE  <https://api.data.netwerkdigitaalerfgoed.nl/datasets/hetutrechtsarchief/Beeldbank/services/Beeldbank/sparql> {
	?cho dc:description ?d .
    ?cho edm:isShownBy ?img.
    Filter contains(?d, "Rietveld")
    ?cho 	<http://www.europeana.eu/schemas/edm/isShownAt> ?catalogus.
    ?cho dc:rights ?rechten
  }

  Filter contains(?d, ?straat) 
  Filter contains(?rechten, "CC")
 Bind(replace(str(?functie), "\\(K\\)", "", "i") as ?f)
   # Bind(replace(?stijlrm, "n.v.t.", "", "i") as ?stijl)
    #  Bind(if(strlen(?stijl) > 2, concat("Stijl:  ", ?stijl), "") as ?stijl2) 
	#	Bind(if(strlen(?naamrm) > 2, concat(?naamrm, ' - '), "") as ?naamrm2) 
      BIND(strdt(concat('<img src="',str(?img),'" style="max-width: 150px;">','</a></p>', ?naamrm,'<p>', ?f, ?omschrijving2, " - rijksmonument ", '<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>', '<p>', ?stijlrm,'<p>', "<a href=", uri(?catalogus),' "target="_blank">', "Foto uit Het Utrechts Archief"),rdf:HTML) AS ?shapeLabel)
    Bind("#648fff" as ?shapeColor)
  }
  union
  {
   GRAPH graph:instanties-rce {
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
  ?rijksmonument ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving.
    ?rijksmonument ceo:heeftOmschrijving/ceo:formeelStandpunt "1"^^xsd:boolean.
      optional{?rijksmonument ceo:heeftNaam/ceo:naam ?naamrm.}
      optional{?rijksmonument ceo:heeftStijlEnCultuur/ceo:heeftStijlEnCultuurNaam/skos:prefLabel ?stijlrm.}
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
  OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}

        
   #selecteer alle monumenten van Rietveld in de actor en beschrijving 
    {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld ; Stad Amsterdam"}
    union
        {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G.Th. ; Utrecht"}
   union
   {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G.T. ; Stad Utrecht"}
     union
   {?rijksmonument ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor "Rietveld, G. ; Noord-Holland"}
    union
    {Filter regex(?omschrijving, "gerrit rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Th\\. Rietveld", "i")}
        union
    {Filter regex(?omschrijving, "G\\. Rietveld", "i")}
            union
    {Filter regex(?omschrijving, "Th\\.Rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Gerrit Thomas Rietveld", "i")}
    union
    {Filter regex(?omschrijving, "Th\\.Rietveld", "i")}
      
            Filter(?rijksmonumentnummer != "18329")
      Filter(?rijksmonumentnummer != "46957")
      Filter(?rijksmonumentnummer != "46958")

     # Bind(if(strlen(?stijlrm) > 2, concat("Stijl:  ", ?stijlrm), "") as ?stijl2) 
		#Bind(if(strlen(?naamrm) > 2, concat(?naamrm, ' - '), "") as ?naamrm2) 
           Bind(replace(str(?functie), "\\(K\\)", "", "i") as ?f)
       BIND(strdt(concat(?naamrm, '<p>', ?f, " - rijksmonument ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rijksmonumentnummer),'" target="_blank">',str(?rijksmonumentnummer),'</a>', '<p>', ?stijlrm),rdf:HTML) AS ?shapeLabel)
      Bind("#00008B" as ?shapeColor)
     
  }
      

}
  union
  {SERVICE <https://api.collectiedata.hetnieuweinstituut.nl/datasets/the-other-interface/knowledge-graph/services/knowledge-graph/sparql>{
   ?stuk rico:isAgentAssociatedWithAgent <https://collectiedata.hetnieuweinstituut.nl/id/people/12546> .
  ?stuk skos:prefLabel ?naamn.
  ?stuk rico:hasRecordSetType/skos:prefLabel ?typen.
  ?stuk rico:date/skos:prefLabel ?daten.
  ?stuk rico:isOrWasHolderOf/schema:foundingLocation/rdfs:seeAlso ?archiefplek.
      ?stuk <https://www.ica.org/standards/RiC/ontology#scopeAndContent> ?scope.
Filter(?archiefplek = <http://vocab.getty.edu/tgn/7006792>)
  }

    
   #   ?archiefplek wgs84:long ?longn.
   #  BIND(RAND()/200 AS ?randni)
   # Bind(xsd:decimal(?longn) as ?wkt1ni)
   # Bind(xsd:decimal()+(?randni) as ?wktni) 
   Bind(bif:st_geomfromtext(concat("POINT(",str(4.470925)," ", str(51.914589), ")")) as ?shape)

   BIND(strdt(concat('<a href="',(?stuk),'" target="_blank">', " ", str(?naamn),'</a>', '<p>', ?typen, " uit ", ?daten, ".", '<p>', ?scope),rdf:HTML) AS ?shapeLabel)
    Bind("#dc267f" as ?shapeColor)
  }
}