#+ name: Query-51
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>

SELECT ?geometryType (COUNT(*) AS ?aantal)
  
WHERE {
  graph graph:instanties-rce {
  ?rijksmonument a ceo:Rijksmonument ;
                 ceo:heeftGeometrie ?geom .

  ?geom geo:asWKT ?wkt .
}
  BIND(
    UCASE(STRBEFORE(STR(?wkt), "("))
    AS ?geometryType
  )
}
GROUP BY ?geometryType
ORDER BY DESC(?aantal)