#+ name: RCE1--WD1-tijdreeks
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX pqv: <http://www.wikidata.org/prop/qualifier/value/>
PREFIX cidoc: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rel: <http://purl.org/vocab/relationship/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX schema: <https://schema.org/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX thesau: <https://collectiedata.hetnieuweinstituut.nl/model/con/thesau/>

SELECT DISTINCT 
?widget ?bron ?gebouw (COALESCE(?rijksmonumentnummer, "nvt") AS ?rijksmonumentnummer)
(COALESCE(?eventStart, "onbekend") AS ?eventStart) ?eventLabel (SAMPLE(?afbeelding) AS ?eventMedia) ?eventMediaCaption 
  
   
  
{
 
   bind('''
<h2>{{eventLabel}}</h2>
<img src="{{eventMedia}}">
<ul>
  <li>Beschrijving: {{eventMediaCaption}}</li>
  <li>Datum: {{eventStart}}</li>
  <li>Rijksmonumentnummer: {{rijksmonumentnummer}}</li>
  <li>Bron: {{bron}}</li>
  
</ul>'''^^rdf:HTML as ?widget)

  

#-------------------------------Dataset 1 Rijksmonumenten-----------------------------------
#-------------------------------------------------------------------------------------------
  { 
    SELECT DISTINCT ?bron ?gebouw ?rijksmonumentnummer  ?eventStart ?eventLabel ?afbeelding ?eventMediaCaption 
    WHERE {
      GRAPH graph:instanties-rce {

  ?gebouw ceo:heeftOmschrijving/ceo:omschrijving ?eventDescription.  
    
  ?gebouw ceo:heeftOmschrijving/ceo:formeelStandpunt "1"^^xsd:boolean .

OPTIONAL{?gebouw ceo:datumInschrijvingInMonumentenregister ?datum .
      BIND(YEAR(?datum) AS ?jaar)}

        
        #?gebouw ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam/skos:prefLabel ?functie.
        ?gebouw ceo:rijksmonumentnummer ?rijksmonumentnummer.
        #OPTIONAL { ?gebouw ceo:heeftType/ceo:heeftTypeNaam/skos:prefLabel ?gebouwType. }
        OPTIONAL { ?gebouw ceo:heeftKennisregistratie/ceo:heeftActorEnRol/ceo:heeftActor ?actor. }
      FILTER REGEX(?eventDescription, "gerrit*rietveld | Th.*Rietveld | G.*Rietveld | Th.*Rietveld | Gerrit Thomas Rietveld | *G.Th. Rietveld*", "i")    
      
      VALUES ( ?bron) {('Rijksdienst voor Cultureelerfgoed')}
#----------------------------------------eventLabel----------------------------------------------

 BIND(strdt(concat('''''', COALESCE(?rijksmonumentnummer, ""),''''''), rdf:HTML) AS ?eventLabel)
      
#------------------------------------eventMediaCaption----------------------------------------------
 BIND(strdt(concat('''
        <ul>
        <li>Wikinummer: <a href="''', ?gebouw, '" target="_blank">', ?gebouw, '''</a></li>
        <li>Beschrijving: <a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/''', 
                   uri(?rijksmonumentnummer), '" target="_blank">', 
                   str(?rijksmonumentnummer), '</a>','</li></ul>'), rdf:HTML) as ?eventMediaCaption)
           FILTER(BOUND(?afbeelding))

    }
  }
    }
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
  
 UNION
  
#--------------------------------Dataset 2 Wikidata-----------------------------------------
#-------------------------------------------------------------------------------------------
  { 
    SELECT DISTINCT ?bron ?eventLabel ?afbeelding
      ?gebouw ?eventMediaCaption (SAMPLE(?eventStartYear) AS ?eventStart) ?rijksmonumentnummer
    WHERE {
      SERVICE <https://query.wikidata.org/sparql> {
        {
          SELECT DISTINCT ?gebouw WHERE {
          ?gebouw p:P84 ?statement0.
          ?statement0 (ps:P84/(wdt:P279*)) wd:Q160435. # wd:Q160435 = Gerrit Rietveld 
          }
        }

        VALUES ( ?bron) {('Wikidata')}
# ------------------------------------------gebouwLabel---------------------------------------
        OPTIONAL { ?gebouw (wdt:P1705|rdfs:label) ?gebouwLabel . FILTER(LANG(?gebouwLabel) = "nl")}  
        
# --------------------------------------Rijksmonumentnummer---------------------------------  
        OPTIONAL { ?gebouw (wdt:P7135|wdt:P359) ?rijksmonumentnummer .}    
        
#----------------------------------------------afbeelding-----------------------------------------   
        # filter alleen afbeelding format dat werkt met de tijdlijn visualisatie.
        OPTIONAL { ?gebouw wdt:P18 ?afbeelding . FILTER(REGEX(str(?afbeelding), "(?i)\\.(jpg|gif|jpeg|png)", "i"))}
#-----------------------------------------eventStartDate------------------------------------
        OPTIONAL{?gebouw (wdt:P571|wdt:P276/(pqv:P580*)|wdt:P1619|wdt:P1319|ps:P580) ?eventStartDate . 
        FILTER(YEAR(?eventStartDate) > 1900)} 
        BIND(YEAR(?eventStartDate) AS ?eventStartYear)   
 }
#-------------------------------------------eventLabel----------------------------------------

    BIND(strdt(concat('''''',COALESCE(?rijksmonumentnummer, ""), ''' ''',
            COALESCE(?gebouwLabel, ""),''''''), rdf:HTML) AS ?eventLabel)
      
#-------------------------------------------eventMediaCaption-----------------------------------      
      BIND(strdt(concat('''
        <ul>
        <li>Verbouwingsjaar: ''',COALESCE(?eventStartYear, "onbekend"),'''</li>
<li>Wikinummer: <a href="''', ?gebouw, '" target="_blank">', ?gebouw, '''</a></li>
  </ul>'''), rdf:HTML) as ?eventMediaCaption)
    }
  } 

#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
  
 UNION
  
#------------------------Dataset 3 Het Nieuwe Instituut-------------------------------------
#-------------------------------------------------------------------------------------------
  {
  SELECT DISTINCT
  ?bron
?gebouw
(MAX(?titel) AS ?eventLabel)
(MAX(?collectie) AS ?colectieNaam)
(MAX(?objectType) AS ?eventMediaAlt)
(MAX(?id) AS ?collectieID) 
(MAX(?startjaar) AS ?eventStart)
(MAX(?beschrijving) AS ?eventMediaCaption)
?afbeelding
(MAX(?type) AS ?eventType)

WHERE{

    {SERVICE <https://api.collectiedata.hetnieuweinstituut.nl/datasets/the-other-interface/knowledge-graph/services/knowledge-graph/sparql>{

     VALUES ?property { dct:contributor thesau:256 thesau:26455 thesau:5234 thesau:2136 thesau:2109 thesau:1803 thesau:176 schema:creator rico:isCreatorOf rico:isAgentAssociatedWithAgent rel:cre}

?gebouw ?property <https://collectiedata.hetnieuweinstituut.nl/id/people/12546> .

OPTIONAL{?gebouw schema:identifier ?id .}
OPTIONAL{?gebouw schema:description|schema:abstract ?beschrijving .}
OPTIONAL{?gebouw skos:prefLabel|rico:title|schema:name|schema:artform/rdfs:label ?gebouwLabel .}
OPTIONAL{?gebouw dct:contributor/schema:name|thesau:5234/schema:name ?contributor .}
OPTIONAL{?gebouw schema:artform/rdfs:label|schema:type/schema:Article|rdf:type ?objectType .}
OPTIONAL{?gebouw schema:archivedAt|rico:scopeAndContent|schema:isPartOf/schema:name ?collectie .}
OPTIONAL{?gebouw schema:dateCreated/cidoc:P82a_begin_of_the_begin|schema:datePublished|rico:date/rico:hasBeginningDate ?startjaar .}
      OPTIONAL{?gebouw (schema:associatedMedia/schema:image) ?afbeelding1 .}
    OPTIONAL {?gebouw (schema:url|schema:associatedMedia/schema:image) ?afbeelding2 .}

      BIND(COALESCE(?afbeelding1, ?afbeelding2) AS ?afbeelding)
      
      BIND(IF(REGEX(?gebouwLabel, "(huis|woning|woningen|flat|gebouw|huizen|wijk|winkel|toren|Bungalows|villa|Stedenbouwkundig|museum)", "i"), "gebouw", 
          IF(REGEX(?gebouwLabel, "(stoel|zit|lessenaar|fauteuil|bank|tafel|bed)", "i"), "meubel", 
            IF(REGEX(?gebouwLabel, "(interieur|zaal|inrichting)", "i"), "interieur","overig")
          
          )) AS ?type)
      FILTER(?type = "gebouw")
      VALUES (?bron) {('Het Nieuwe Instituut')}
    }}}

GROUP BY ?bron ?gebouw ?eventType ?eventLabel ?afbeelding
}

  }

order by ?eventStart desc(?eventMedia) 
LIMIT 5