#+ name: restrict-search-to-Dutch
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/thesauri/services/thesauri/sparql

prefix text: <http://jena.apache.org/text#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select *
where { 
	?s text:query (skos:prefLabel 'kompas' 'lang:nl').
}