#+ name: rest-api-werelderfgoed
#+ description: ####REST API query for the path werelderfgoed.</p>
#- This SPARQL query is designed to retrieve information about Dutch UNESCO World Heritage Sites (Unesco Werelderfgoederen in Dutch) from the Cultural Heritage Linked Data source that conforms to the Cultureel Erfgoed Ontology (CEO).</p>
#- 
#- - werelderfgoednummer, ex: 1349
#- - cultuurfistorischObjectnummer, ex: 10134675
#- - heeftNaam, ex: Hollandse Waterlinies
#- - registratiedatum, ex: 2021-11-22
#- </p>
#- Date: dd. 2023-11-20</br>
#- Version: 0.5
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
construct {
  $this ?p1 ?o1.
  ?o1 ?p2 ?o2.
  ?o2 ?p3 ?o3.
  ?o3 ?p4 ?o4.
  ?o4 ?p5 ?o5.
  ?o5 ?p6 ?o6.
  ?o6 ?p7 ?o7.
} where {
  graph graph:instanties-rce {
    {
      select distinct $this {
        $this
          a ceo:Werelderfgoed ;
          ceo:werelderfgoednummer ?werelderfgoednummer ;
          ceo:cultuurhistorischObjectnummer ?cultuurhistorischObjectnummer ;
          ceo:registratiedatum ?registratiedatum ;
          ceo:heeftNaam/ceo:naam ?heeftNaam .
      }
      limit 5
      # paginate
    }
    $this ?p1 ?o1.
    optional {
      filter(?p1 not in (ceo:bevatObject, ceo:isHoofdobjectVanComplex, ceo:isOnderdeelVanComplex))
      ?o1 ?p2 ?o2.
      optional {
        ?o2 ?p3 ?o3.
        optional {
          ?o3 ?p4 ?o4.
          optional {
            ?o4 ?p5 ?o5.
            optional {
              ?o5 ?p6 ?o6.
              optional {
                ?o6 ?p7 ?o7.
              }
            }
          }
        }
      }
    }
  }
}
