#+ name: rest-api-gezicht
#+ description: ##### REST API query for the path gezicht(en).</p>
#- This SPARQL query is designed to retrieve information related to "gezichten," specifically stads- en dorpsgezichten (urban and village views) from a Linked Data source that conforms to the Cultureel Erfgoed Ontology (CEO).</p>
#- - gezichtsnummer, ex.: 1439
#- - cultuurhistorischObjectnummer, ex.: 10134173
#- - gezichtsstatus, ex.: rijksbeschermd stads- of dorpsgezicht
#- - naam, ex.: Kamerik
#- - registratiedatum, ex: 1966-08-04
#- </p>
#- Date: dd. 2024-03-05</br>
#- Version: 1.0
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>

# Construct a new RDF graph with specific patterns
CONSTRUCT {
  $this ?p1 ?o1.
  $this ceo:gezichtsnummer ?url.
  ?o1 ?p2 ?o2.
  ?o2 ?p3 ?o3.
  ?o3 ?p4 ?o4.
  ?o4 ?p5 ?o5.
  ?o5 ?p6 ?o6.
  ?o6 ?p7 ?o7.
} WHERE {
  {
    # Focus on the graph named 'instanties-rce' within the specified namespace
    GRAPH graph:instanties-rce {
      {
        # Selecting distinct instances with their associated information
        #! paginate: true
        SELECT DISTINCT $this {
          $this
            a ceo:Gezicht ;
            ceo:cultuurhistorischObjectnummer ?cultuurhistorischObjectnummer ;
            ceo:heeftGezichtsstatus/skos:prefLabel ?gezichtsstatus ;
            ceo:registratiedatum ?registratiedatum ;
            ceo:heeftNaam/ceo:naam ?heeftNaam ;
            ceo:gezichtsnummer ?gezichtsnummer.
        }
        LIMIT 5

      }
    }
  }
  {
    # Now, include the 'gezicht_hvdl' graph in the query
    GRAPH graph:gezicht_hvdl {
      # Add patterns for this graph here
      # Example:
      $this ceo:heeftGeometrie/ceo:oppervlakteInHectare ?oppervlakteinhectare.
    }
    # Extract additional information about the selected instances
    $this ?p1 ?o1.
    # Extract additional information about the selected instances
    $this ?p1 ?o1.
    FILTER (?p1 != ceo:gezichtsnummer) # Filtering out gezichtsnummer property
    $this ceo:gezichtsnummer ?gezichtsnummer .
    # Creating URL based on the provided format
    BIND(concat('https://archisarchief.cultureelerfgoed.nl/Beschermde_Gezichten/BG', STR(?gezichtsnummer)) AS ?url)
    OPTIONAL {
      # Filter out specific properties from the data
      FILTER (?p1 NOT IN (ceo:bevatObject, ceo:isHoofdobjectVanComplex, ceo:isOnderdeelVanComplex))
      ?o1 ?p2 ?o2.
      OPTIONAL {
        ?o2 ?p3 ?o3.
        OPTIONAL {
          ?o3 ?p4 ?o4.
          OPTIONAL {
            ?o4 ?p5 ?o5.
            OPTIONAL {
              ?o5 ?p6 ?o6.
              OPTIONAL {
                ?o6 ?p7 ?o7.
              }
            }
          }
        }
      }
    }
  }
}
