#+ name: rest-api-werelderfgoed
#+ description: #### REST API query for the path werelderfgoed.</p>
#- This SPARQL query is designed to retrieve information about Dutch UNESCO World Heritage Sites (Unesco Werelderfgoederen in Dutch) from the Cultural Heritage Linked Data source that conforms to the Cultureel Erfgoed Ontology (CEO).</p>
#- 
#- - werelderfgoednummer, ex: 1349
#- - cultuurfistorischObjectnummer, ex: 10134675
#- - heeftNaam, ex: Hollandse Waterlinies
#- - registratiedatum, ex: 2021-11-22
#- - werelderfgoedstatus, ex: werelderfgoed
#- </p>
#- Date: dd. 2024-03-05</br>
#- Version: 1.0
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>

CONSTRUCT {
  $this ?p1 ?o1.
  $this ceo:werelderfgoednummer ?url.
  ?o1 ?p2 ?o2.
  ?o2 ?p3 ?o3.
  ?o3 ?p4 ?o4.
  ?o4 ?p5 ?o5.
  ?o5 ?p6 ?o6.
 # ?o6 ?p7 ?o7.
} WHERE {
  GRAPH graph:instanties-rce {
    {
                  #! paginate: true
      # Selecting distinct instances with their associated information
      SELECT DISTINCT $this ?werelderfgoednummer  {
        $this
          a ceo:Werelderfgoed ;
          ceo:heeftWerelderfgoedstatus/skos:prefLabel ?werelderfgoedstatus ;
          ceo:werelderfgoednummer ?werelderfgoednummer ;
          ceo:cultuurhistorischObjectnummer ?cultuurhistorischObjectnummer ;
          ceo:registratiedatum ?registratiedatum ;
          ceo:heeftNaam/ceo:naam ?heeftNaam .
        # Creating URL based on the UNESCO list
        BIND(CONCAT('https://whc.unesco.org/en/list/',STR(?werelderfgoednummer)) AS ?url)
      }
      LIMIT 5

    }
  }
  # Including the 'werelderfgoed_hvdl' graph in the query
  GRAPH graph:werelderfgoed_hvdl {
    # Adding patterns for this graph here (not specified in the original query)
    $this ceo:heeftGeometrie/ceo:oppervlakteInHectare ?oppervlakteinhectare.
  }
  # Extracting additional information about the selected instances
  $this ?p1 ?o1.
  FILTER(?p1 != ceo:werelderfgoednummer) # Filtering out werelderfgoednummer property
  $this ceo:werelderfgoednummer ?werelderfgoednummer .
  BIND(CONCAT('https://whc.unesco.org/en/list/',STR(?werelderfgoednummer)) AS ?url) # Creating URL based on the UNESCO list
  OPTIONAL {
    # Filtering out specific properties from the data
    $this ?p1 ?o1.
    OPTIONAL {
      FILTER(?p1 NOT IN (ceo:bevatObject, ceo:isHoofdobjectVanComplex, ceo:isOnderdeelVanComplex))
      ?o1 ?p2 ?o2.
      OPTIONAL {
        ?o2 ?p3 ?o3.
        OPTIONAL {
          ?o3 ?p4 ?o4.
          OPTIONAL {
            ?o4 ?p5 ?o5.
            OPTIONAL {
              ?o5 ?p6 ?o6.
            #   OPTIONAL {
            #     ?o6 ?p7 ?o7.
            #   }
             }
          }
        }
      }
    }
  }
}
