#+ name: Resultaat-in-tabel
#+ description: Hoort bij vuurtorens
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?label ?bouwjaar ?rm_nr ?jaarBuitendienststelling ?MarineTraffic_id ?ARLHS_id ?hoogte ?omschrijving
WHERE
{
?vuurtoren ceox:heeftFunctieNaam <https://data.cultureelerfgoed.nl/term/id/rn/e1caeac0-0ff1-4651-823c-458eb2c9c286> ;
 ; ceo:rijksmonumentnummer ?rm_nr .
      
  optional {?vuurtoren rdfs:label ?label}
#  optional {?vuurtoren ceox:jaarInGebruikname ?jaarInGebruikname}
  optional {?vuurtoren ceox:jaarBuitendienststelling ?jaarBuitendienststelling}
  ?vuurtoren ceox:MarineTraffic_id ?MarineTraffic_id
  optional {?vuurtoren ceox:bouwjaar ?bouwjaar}
  optional {?vuurtoren ceox:ARLHS_id ?ARLHS_id}
  optional {?vuurtoren ceox:hoogte ?hoogte}
  OPTIONAL {?vuurtoren ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving.}
 # ?vuurtoren ceo:heeftGeometrie/geo:asWKT ?geo.

} order by DESC(?hoogte)                                                                                        
                                                                                          
