#+ name: Rijksmonumenten-geo
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>

SELECT ?rijksmonumentnummer ?shape ?shaperd ?functie ?datumInschrijving ?omschrijving 

WHERE 
{
  GRAPH graph:instanties-rce {
    MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
    ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
    OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?shape.}
    OPTIONAL {?rijksmonument ceo:heeftGeometrie/ceo:asWKT-RD ?shaperd.}
    OPTIONAL {?rijksmonument ceo:heeftOmschrijving ?omschrijving1 . ?omschrijving1 ceo:omschrijving ?omschrijving  ; ceo:formeelStandpunt "1"^^xsd:boolean.}
    ?rijksmonument ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?functienaam.
    ?functienaam skos:prefLabel ?functie .
    ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.  
}
}
limit 10


  


  

