prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select ?wkt ?stijl {
  ?rijksmonument
    a ceo:Rijksmonument;
    ceo:heeftGeometrie/geo:asWKT ?wkt;
    ceo:heeftLocatieAanduiding/ceo:locatienaam ?locatienaam.
  optional { ?rijksmonument ceo:heeftStijlEnCultuur/ceo:heeftStijlEnCultuurNaam/skos:prefLabel ?stijl. }
}
