#+ name: rijksmonumenten-gezicht
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix gsp: <http://www.opengis.net/ont/geosparql#>
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select ?ge ?rm  ?gezichtsnaam ?rmn ?oorspronkelijkeFunctie ?geogez ?geormn ('red' as ?geogezColor) ('blue' as ?geormColor)
where {
  values (?ge ?gezichtnummer) {
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134190> 196 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134555> 197 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134563> 198 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134647> 199 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134597> 200 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134585> 201 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134539> 202 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134630> 203 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134534> 204 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134535> 205 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134649> 206 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134646> 207 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134601> 208 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134537> 209 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134511> 210 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134635> 211 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134562> 212 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134545> 213 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134524> 214 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134564> 215 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134525> 216 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134580> 217 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134543> 218 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134548> 219 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134616> 220 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134620> 221 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134578> 222 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134643> 223 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134644> 224 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134557> 225 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134648> 226 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134589> 227 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134550> 228 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134651> 229 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134512> 230 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134584> 231 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134523> 232 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134521> 233 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134587> 234 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134582> 235 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134600> 236 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134591> 237 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134517> 238 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134533> 239 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134559> 240 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134579> 241 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134561> 242 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134189> 243 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134612> 245 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134549> 246 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134598> 247 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134593> 248 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134569> 249 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134603> 250 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134516> 251 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134526> 252 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134515> 253 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134592> 254 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134605> 255 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134519> 256 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134636> 257 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134529> 258 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134530> 259 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134573> 260 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134586> 261 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134641> 262 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134201> 263 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134520> 264 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134611> 265 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134608> 266 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134652> 267 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134551> 268 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134554> 269 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134607> 270 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134181> 271 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134566> 272 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134522> 273 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134609> 274 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134558> 275 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134553> 276 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134565> 277 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134610> 278 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134581> 279 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134536> 280 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134538> 281 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134542> 282 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134514> 283 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134500> 284 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134638> 285 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134527> 286 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134577> 287 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134602> 288 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134570> 289 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134572> 290 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134541> 291 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134575> 292 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134528> 293 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134540> 294 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134531> 295 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134547> 296 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134595> 297 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134574> 298 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134567> 299 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134556> 300 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134571> 301 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134604> 302 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134599> 303 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134246> 312 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134483> 313 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134423> 316 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134546> 317 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134445> 318 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134438> 319 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134188> 320 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134594> 323 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134626> 324 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134625> 1305 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134619> 1306 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134622> 1309 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134623> 1310 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134210> 1315 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134211> 1316 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134200> 1317 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134202> 1318 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134203> 1319 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134204> 1320 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134206> 1321 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134207> 1322 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134208> 1323 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134209> 1324 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134178> 1325 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134179> 1326 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134180> 1327 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134184> 1328 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134185> 1329 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134187> 1330 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134212> 1331 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134213> 1332 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134214> 1333 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134215> 1334 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134216> 1335 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134191> 1336 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134192> 1337 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134193> 1338 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134197> 1339 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134198> 1340 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134199> 1341 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134217> 1342 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134218> 1343 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134650> 1344 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134219> 1345 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134220> 1346 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134221> 1347 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134222> 1348 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134223> 1349 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134205> 1350 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134224> 1351 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134225> 1352 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134226> 1353 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134227> 1354 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134228> 1355 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134229> 1356 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134182> 1357 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134230> 1358 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134231> 1359 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134232> 1360 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134233> 1361 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134234> 1362 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134235> 1363 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134237> 1364 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134238> 1365 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134239> 1366 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134240> 1367 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134241> 1368 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134242> 1369 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134244> 1370 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134245> 1371 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134247> 1372 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134248> 1373 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134243> 1374 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134249> 1375 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134250> 1376 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134251> 1377 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134252> 1378 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134253> 1379 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134254> 1380 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134256> 1381 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134257> 1382 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134258> 1383 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134259> 1384 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134260> 1385 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134261> 1386 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134262> 1387 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134263> 1388 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134264> 1389 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134265> 1390 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134266> 1391 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134267> 1392 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134268> 1393 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134269> 1394 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134270> 1395 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134272> 1396 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134273> 1397 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134274> 1398 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134275> 1399 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134278> 1400 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134279> 1401 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134280> 1402 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134281> 1403 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134271> 1404 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134276> 1405 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134277> 1406 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134282> 1407 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134283> 1408 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134284> 1409 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134285> 1410 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134286> 1411 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134287> 1412 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134288> 1413 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134289> 1414 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134590> 1415 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134290> 1416 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134291> 1417 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134293> 1418 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134634> 1419 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134294> 1420 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134606> 1421 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134295> 1422 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134296> 1423 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134297> 1424 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134298> 1425 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134299> 1426 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134300> 1427 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134301> 1428 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134302> 1429 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134303> 1430 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134304> 1431 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134305> 1432 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134306> 1433 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134307> 1434 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134309> 1435 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134310> 1436 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134311> 1437 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134312> 1438 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134173> 1439 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134313> 1440 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134314> 1441 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134315> 1442 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134316> 1443 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134318> 1444 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134319> 1445 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134320> 1446 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134629> 1447 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134321> 1448 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134322> 1449 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134323> 1450 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134324> 1451 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134325> 1452 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134326> 1453 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134327> 1454 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134328> 1455 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134329> 1456 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134292> 1457 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134330> 1458 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134331> 1459 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134332> 1460 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134333> 1461 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134174> 1462 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134334> 1463 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134335> 1464 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134336> 1465 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134337> 1466 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134338> 1467 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134339> 1468 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134308> 1469 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134340> 1470 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134186> 1471 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134317> 1472 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134341> 1473 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134342> 1474 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134343> 1475 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134345> 1476 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134346> 1477 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134347> 1478 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134348> 1479 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134349> 1480 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134350> 1481 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134352> 1482 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134353> 1483 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134195> 1484 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134354> 1485 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134355> 1486 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134356> 1487 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134357> 1488 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134358> 1489 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134359> 1490 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134196> 1491 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134360> 1492 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134361> 1493 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134362> 1494 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134363> 1495 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134596> 1496 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134364> 1497 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134366> 1498 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134367> 1499 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134368> 1500 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134369> 1501 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134370> 1502 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134371> 1503 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134373> 1504 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134374> 1505 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134375> 1506 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134376> 1507 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134377> 1508 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134378> 1509 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134380> 1510 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134381> 1511 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134382> 1512 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134383> 1513 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134384> 1514 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134386> 1515 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134387> 1516 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134388> 1517 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134389> 1518 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134390> 1519 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134391> 1520 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134394> 1521 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134395> 1522 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134396> 1523 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134397> 1524 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134398> 1525 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134631> 1526 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134400> 1527 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134401> 1528 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134402> 1529 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134403> 1530 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134404> 1531 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134632> 1532 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134405> 1533 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134406> 1534 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134344> 1535 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134392> 1536 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134399> 1537 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134236> 1538 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134379> 1539 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134393> 1540 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134372> 1541 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134407> 1542 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134408> 1543 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134409> 1544 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134410> 1545 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134411> 1546 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134412> 1547 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134413> 1548 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134414> 1549 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134415> 1550 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134416> 1551 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134417> 1552 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134418> 1553 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134419> 1554 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134420> 1555 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134421> 1556 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134424> 1557 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134425> 1558 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134426> 1559 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134422> 1560 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134255> 1561 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134427> 1562 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134428> 1563 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134365> 1564 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134429> 1565 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134430> 1566 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134351> 1567 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134431> 1568 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134432> 1569 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134433> 1570 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134435> 1571 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134436> 1572 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134439> 1573 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134441> 1574 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134442> 1575 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134443> 1576 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134444> 1577 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134446> 1578 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134447> 1579 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134448> 1580 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134449> 1581 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134437> 1582 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134450> 1583 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134452> 1584 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134453> 1585 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134454> 1586 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134455> 1587 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134456> 1588 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134457> 1589 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134458> 1590 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134459> 1591 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134627> 1592 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134460> 1593 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134461> 1594 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134462> 1595 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134183> 1596 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134463> 1597 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134434> 1598 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134440> 1599 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134175> 1600 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134451> 1601 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134177> 1602 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134464> 1603 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134385> 1604 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134465> 1605 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134466> 1606 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134467> 1607 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134468> 1608 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134469> 1609 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134470> 1610 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134471> 1611 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134472> 1612 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134473> 1613 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134474> 1614 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134475> 1615 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134477> 1616 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134478> 1617 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134479> 1618 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134480> 1619 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134481> 1620 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134482> 1621 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134476> 1622 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134484> 1623 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134485> 1624 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134486> 1625 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134487> 1626 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134488> 1627 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134489> 1628 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134490> 1629 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134491> 1630 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134492> 1631 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134493> 1632 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134494> 1633 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134176> 1634 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134496> 1635 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134497> 1636 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134498> 1637 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134499> 1638 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134495> 1639 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134501> 1640 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134502> 1641 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134503> 1642 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134504> 1643 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134505> 1644 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134506> 1645 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134507> 1646 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134508> 1647 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134509> 1648 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134510> 1649 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134513> 1650 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134518> 1651 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134544> 1652 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134552> 1653 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134560> 1654 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134642> 1655 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134568> 1656 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134532> 1657 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134576> 1658 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134583> 1659 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134588> 1660 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134615> 1671 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134653> 1672 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134614> 1679 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134628> 1686 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134621> 1698 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134624> 1709 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134194> 1729 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134617> 1733 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134618> 1734 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134613> 1735 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134633> 1767 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134645> 1769 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134639> 1770 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134637> 1771 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134654> 2124 )
( <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/gezicht/10134640> 2125 )

}
  graph graph:instanties-rce {
    ?ge a ceo:Gezicht ;
        ceo:gezichtsnummer ?gezichtnummer ;
        ceo:heeftNaam/ceo:naam ?gezichtsnaam ;
        ceo:heeftGeometrie/gsp:asWKT ?geogez .

    ?rm a ceo:Rijksmonument ;
        ceo:rijksmonumentnummer ?rmn ;
        ceo:heeftGeometrie/gsp:asWKT ?geormn .

    optional {
 ?rm ceo:heeftOorspronkelijkeFunctie/ceo:heeftFunctieNaam ?functie }

    filter(geof:sfWithin(?geormn, ?geogez))
  }

  graph graph:bebouwdeomgeving {
    optional {
 ?functie skos:broader/skos:prefLabel ?oorspronkelijkeFunctie }
  }
}
order by ?gezichtnummer ?rmn
