#+ name: rijksmonument-joods-erfgoed--tabel
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select distinct (uri(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/", ?rijksmonumentnummer)) as ?monumentenregister) 
?provincie ?functie ?categorieenfunctie 
(group_concat(distinct ?joodsGerelateerd) as ?gevondenTermen) ?omschrijving
where {
  graph graph:instanties-rce {
    ?choi a ceo:Rijksmonument.
    ?choi ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864>.
    ?choi ceo:rijksmonumentnummer ?rijksmonumentnummer .
    ?choi ceo:heeftOmschrijving/ceo:omschrijving ?omschrijving_ .
    ?choi ceo:heeftOmschrijving ?standpunt_omschrijving.
    ?standpunt_omschrijving ceo:formeelStandpunt "1"^^<http://www.w3.org/2001/XMLSchema#boolean>.
    bind(replace(replace(?omschrijving_, "\r", " "), "\n", " ") as ?omschrijving)

    bind(if(regex(?omschrijving, "\\b(Jood)\\b", "i"), "Jood", "") as ?matchLabel1)
    bind(if(regex(?omschrijving, "\\b(Joods)\\b", "i"), "Joods", "") as ?matchLabel2)
    bind(if(regex(?omschrijving, "\\b(Joodse)\\b", "i"), "Joodse", "") as ?matchLabel3)
    bind(if(regex(?omschrijving, "\\b(Joden)\\b", "i"), "Joden", "") as ?matchLabel4)
    bind(if(regex(?omschrijving, "\\b(Israëlitisch)\\b", "i"), "Israëlitisch", "") as ?matchLabel5)
    bind(if(regex(?omschrijving, "\\b(Hebreeuws)\\b", "i"), "Hebreeuws", "") as ?matchLabel6)
    bind(if(regex(?omschrijving, "\\b(Jiddisch)\\b", "i"), "Jiddisch", "") as ?matchLabel7)
    bind(if(regex(?omschrijving, "\\b(Kosher)\\b", "i"), "Kosher", "") as ?matchLabel8)
    bind(if(regex(?omschrijving, "\\b(Koosjer)\\b", "i"), "Koosjer", "") as ?matchLabel9)
    bind(if(regex(?omschrijving, "\\b(Sjabbat)\\b", "i"), "Sjabbat", "") as ?matchLabel10)
    bind(if(regex(?omschrijving, "\\b(Kille)\\b", "i"), "Kille", "") as ?matchLabel11)
    bind(if(regex(?omschrijving, "\\b(Mikwe)\\b", "i"), "Mikwe", "") as ?matchLabel12)
    bind(if(regex(?omschrijving, "\\b(Sjoel)\\b", "i"), "Sjoel", "") as ?matchLabel13)
    bind(if(regex(?omschrijving, "\\b(Hoogduits)\\b", "i"), "Hoogduits", "") as ?matchLabel14)
    bind(if(regex(?omschrijving, "\\b(Asjkenazisch)\\b", "i"), "Asjkenazisch", "") as ?matchLabel15)
    bind(if(regex(?omschrijving, "\\b(Portugees)\\b", "i"), "Portugees", "") as ?matchLabel16)
    bind(if(regex(?omschrijving, "\\b(Sabat)\\b", "i"), "Sabat", "") as ?matchLabel17)
    bind(if(regex(?omschrijving, "\\b(Synagoge)\\b", "i"), "Synagoge", "") as ?matchLabel18)
    bind(if(regex(?omschrijving, "\\b(Serfadisch)\\b", "i"), "Serfadisch", "") as ?matchLabel19)
    bind(if(regex(?omschrijving, "\\b(Rabbijn)\\b", "i"), "Rabbijn", "") as ?matchLabel20)
    bind(if(regex(?omschrijving, "\\b(Davidster)\\b", "i"), "Davidster", "") as ?matchLabel21)
    bind(if(regex(?omschrijving, "\\b(Davidsster)\\b", "i"), "Davidsster", "") as ?matchLabel22)
    bind(if(regex(?omschrijving, "\\b(Isr.)\\b", "i"), "Isr.", "") as ?matchLabel23)
    
    bind(concat(if(?matchLabel1 != "", " ", ""), ?matchLabel1,
                if(?matchLabel2 != "", " ", ""), ?matchLabel2,
                if(?matchLabel3 != "", " ", ""), ?matchLabel3,
                if(?matchLabel4 != "", " ", ""), ?matchLabel4,
                if(?matchLabel5 != "", " ", ""), ?matchLabel5,
                if(?matchLabel6 != "", " ", ""), ?matchLabel6,
                if(?matchLabel7 != "", " ", ""), ?matchLabel7,
                if(?matchLabel8 != "", " ", ""), ?matchLabel8,
                if(?matchLabel9 != "", " ", ""), ?matchLabel9,
                if(?matchLabel10 != "", " ", ""), ?matchLabel10,
                if(?matchLabel11 != "", " ", ""), ?matchLabel11,
                if(?matchLabel12 != "", " ", ""), ?matchLabel12,
                if(?matchLabel13 != "", " ", ""), ?matchLabel13,
                if(?matchLabel14 != "", " ", ""), ?matchLabel14,
                if(?matchLabel15 != "", " ", ""), ?matchLabel15,
                if(?matchLabel16 != "", " ", ""), ?matchLabel16,
                if(?matchLabel17 != "", " ", ""), ?matchLabel17,
                if(?matchLabel18 != "", " ", ""), ?matchLabel18,
                if(?matchLabel19 != "", " ", ""), ?matchLabel19,
                if(?matchLabel20 != "", " ", ""), ?matchLabel20,
                if(?matchLabel21 != "", " ", ""), ?matchLabel21,
                if(?matchLabel22 != "", " ", ""), ?matchLabel22,
                if(?matchLabel23 != "", " ", ""), ?matchLabel23) as ?joodsGerelateerd)
  }
  
  filter(?joodsGerelateerd != "")
  filter(!regex(?omschrijving, "Jodenbreestraat|Jozef Israëls", "i"))

  optional {
    ?choi ceo:heeftOorspronkelijkeFunctie ?functies_.
    ?functies_ ceo:heeftFunctieNaam ?functies .
    ?functies skos:prefLabel ?functie .
      #  bind(replace(?functie, "\\s\\(.*\\)|\\(.*\\)", "") as ?functiesl)
    ?functies_ ceo:formeelStandpunt "1"^^<http://www.w3.org/2001/XMLSchema#boolean>.

    graph graph:bebouwdeomgeving {
      optional {
        ?functies skos:broader ?broader1 .
        ?broader1 skos:prefLabel ?functie1 .
        filter(?functie1 != "bebouwde omgeving")
        optional {
          ?broader1 skos:broader ?broader2 .
          ?broader2 skos:prefLabel ?functie2 .
          filter(?functie2 != "bebouwde omgeving")
          optional {
            ?broader2 skos:broader ?broader3 .
            ?broader3 skos:prefLabel ?functie3 .
            filter(?functie3 != "bebouwde omgeving")
          }
        }
      }
    }
    bind(concat(
      if(bound(?functie1), concat("", ?functie1), ""),
      if(bound(?functie2), concat(" | ", ?functie2), ""),
      if(bound(?functie3), concat(" | ", ?functie3), "")
    ) as ?categorieenfunctie)
  }
  
  ?choi ceo:heeftBasisregistratieRelatie/ceo:heeftProvincie ?prov.
  graph graph:owms {
    ?prov skos:prefLabel ?provincie.
  }

}
group by ?provincie ?omschrijving ?rijksmonumentnummer ?monumentenregister ?functie ?categorieenfunctie
order by ?provincie ?functie ?rijksmonumentnummer