#+ name: Rijksmonumenten-in-Prenten-in-Oude-Teken
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/Prenten-en-Oude-Tekeningen/services/Prenten-en-Oude-Tekeningen/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix la: <https://linked.art/ns/terms/>
prefix cidoc: <http://www.cidoc-crm.org/cidoc-crm/>

select DISTINCT *
WHERE {
  ?pot1 a cidoc:E22_Human-Made_Object.
  ?pot1 cidoc:P2_has_type <https://data.cultureelerfgoed.nl/term/id/rn/2b73b05a-b83a-423d-a95a-3633664d00b8>.
  ?pot1 cidoc:P129i_is_subject_of/rdfs:label ?onderwerp .
  OPTIONAL {?pot1 cidoc:P62_depicts ?depiction.}
  OPTIONAL {?depiction rdfs:label ?label.
  ?pot1 cidoc:P129i_is_subject_of ?ff.
  ?ff cidoc:P65_shows_visual_item ?ff2.
  ?ff2 la:digitally_shown_by ?a.
    ?a la:access_point ?b.}
  ?depiction cidoc:P190_has_symbolic_content ?pot_mon.
  FILTER (regex(str(?b), "images", "i"))

SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql>
     {
  ?choi a ceo:Rijksmonument. 
  ?choi ceo:heeftGeometrie/geo:asWKT ?geo.   
    OPTIONAL {?choi ceo:heeftNaam/ceo:naam ?rmnaam.}
  ?choi ceo:rijksmonumentnummer ?pot_mon.
    }
  }
limit 150