#+ name: RKM12
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT
#?id 
#?linkRijksmuseum 
#?collectie 
#?ontwerper 
?ontwerperNaam 

#?beschrijving (LANG(?beschrijving) AS ?langBeschrijving)
#?locatie (LANG(?locatie) AS ?langLocatie)
#?lat ?long
#?periode (LANG(?periode) AS ?langPeriode)
#(COUNT(DISTINCT (?voorwerp)) AS ?aantalObjecten)
?voorwerp
WHERE {
  SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/Rijksmuseum/collection/services/collection/sparql>{
  ?linkRijksmuseum dc:creator ?ontwerper ;
                   dc:title ?voorwerp ;
                   dc:identifier ?id ;
                   dct:isPartOf ?collectie ;
                   dct:spatial ?spat .
    
  # Rietveld.
                   
    
    FILTER(LANG(?voorwerp) = "nl")
  OPTIONAL{?linkRijksmuseum dc:description ?beschrijving .} 
 # ?spat skos:prefLabel ?locatie ;  #check beschrijving
  #      wgs84:lat ?lat ;
   #     wgs84:long ?long.
  ?ontwerper skos:prefLabel ?ontwerperNaam .

  #OPTIONAL{?linkRijksmuseum dct:created ?periode .} 

    
    
    FILTER(regex(str(?ontwerperNaam), "Riet", "i"))
  
  }
 
}
#GROUP BY ?ontwerperNaam
