#+ name: rm-op-jaar
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>


SELECT ?rijksmonument ?rm ?datumInschrijving ?jaarInschrijvings

WHERE {
  ?rijksmonument a ceo:Rijksmonument .
  ?rijksmonument ceo:rijksmonumentnummer ?rm.
   ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
          ?rijksmonument ceo:heeftJuridischeStatus/skos:prefLabel ?grm.
    FILTER (regex(?grm, "^rijksmonument") || contains(?grm, "voorbeschermd"))
  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving) 
  FILTER (?jaarInschrijving >= "1990"^^<http://www.w3.org/2001/XMLSchema#integer> && ?jaarInschrijving <="1995"^^<http://www.w3.org/2001/XMLSchema#integer>)
    bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)

  } 
ORDER BY ?jaarInschrijving
