#+ name: rm-per-jaar-tellen-1
#+ description: The query retrieves the number of registered monuments per year from the given endpoint. It counts the occurrences of registered monuments and groups the results by the year of registration, displaying the years in ascending order.
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

#+ description: The query retrieves the number of registered monuments per year from the given endpoint. It counts the occurrences of registered monuments and groups the results by the year of registration, displaying the years in ascending order.
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT ?jaarInschrijvings (COUNT(?rijksmonument) AS ?aantal)
# The query selects the variable ?jaarInschrijvings to represent the year of registration and COUNT(?rijksmonument) as ?aantal to count the number of registered monuments.

WHERE {
  GRAPH graph:instanties-rce {
  ?rijksmonument a ceo:Rijksmonument . 
  # Matches ?rijksmonument that is of type ceo:Rijksmonument.
  
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving. 
  # Matches ?rijksmonument that has the property ceo:datumInschrijvingInMonumentenregister with value ?datumInschrijving.
  
  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
  # Extracts the year from ?datumInschrijving and assigns it to ?jaarInschrijving using BIND and the year() function.
  
  bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
  # Converts ?jaarInschrijving to a string and binds it to ?jaarInschrijvings using BIND and the str() function.
  
  bind(concat(str(?aantal)) as ?aantals)
  # Converts ?aantal to a string and binds it to ?aantals using BIND and the str() function.
  
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
  # Excludes ?rijksmonument that has the property ceo:heeftJuridischeStatus with the specified value.
}
}
GROUP BY ?jaarInschrijvings
# Groups the results by ?jaarInschrijvings.

ORDER BY ?jaarInschrijvings
# Orders the results in ascending order of ?jaarInschrijvings.
