#+ name: rm-telling-per-provincie-jaar-2-1
#+ description: DO NOT DELETE
#- Deze query telt rijksmonumenten per provincie, gemeente, gemeentecode, monumentaard en hoofdcategorie voor een opgegeven jaar. Een rijksmonument telt mee wanneer het in dat jaar geldig was. Dat betekent:
#- 
#- het is in of vóór het gekozen jaar ingeschreven;
#- 
#- het heeft de juridische status “rijksmonument”;
#- 
#- of het is pas na het gekozen jaar afgevoerd.
#- 
#- U kunt extern filteren op jaar, provincie, gemeentecode en monumentaard. De query past deze filters toe op de onderliggende gegevens.
#- 
#- Het resultaat toont per combinatie van provincie, gemeente, gemeentecode, monumentaard en hoofdcategorie het aantal rijksmonumenten dat in het gekozen jaar geldig was.
#- 
#- NB dit zijn de gemeenten van > 01-01-2025
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/sparql

prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix ceo:   <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix owms:  <http://standaarden.overheid.nl/owms/terms/>
prefix tooi:  <https://identifier.overheid.nl/tooi/def/ont/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select
  ?provincie
  ?monumentAard
  ?gemeente
  ?gemeentecode
  ?hoofdcategorie
  (count(?rijksmonument) as ?aantal)

where {

  ######################################################################
  # 1. Rijksmonumenten (CEO)
  ######################################################################
  graph graph:instanties-rce {

    ?rijksmonument a ceo:Rijksmonument ;
      ceo:heeftBasisregistratieRelatie ?basisrel ;
      ceo:datumInschrijvingInMonumentenregister ?datumInschrijving ;
      ceo:heeftJuridischeStatus ?juridischeStatus ;
      ceo:registratiedatum ?datumRegistratie ;
      ceo:heeftOorspronkelijkeFunctie ?functie ;
      ceo:heeftMonumentAard ?monumentAard_ .

    
    ?functie ceo:hoofdfunctie true ;
      ceo:heeftFunctieNaam ?uri .

    ?monumentAard_ skos:prefLabel ?monumentAard .

    bind(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
    bind(year(xsd:dateTime(?datumRegistratie))  as ?jaarRegistratie)

  #  ?basisrel ceo:heeftProvincie ?prov .
    ?basisrel ceo:heeftProvincie ?provOud .
      ?basisrel ceo:heeftGemeente ?gemOud .
    bind(str(?gemOud) as ?gemOudUri)
       bind(str(?provOud) as ?provOudUri)
    filter(
      (?jaarInschrijving <= ?jaar) &&
      (
        ?juridischeStatus = <https://data.cultureelerfgoed.nl/term/id/rn/2/b2d9a59a-fe1e-4552-9a05-3c2acddff864>
        || (?jaarRegistratie > ?jaar)
      )
    )
  }

  ######################################################################
  # 2. Hoofdcategorie
  ######################################################################
  graph graph:bebouwdeomgeving {

    values (?hoofdcategorie ?narrow) {
      ("Archeologie (N)" <https://data.cultureelerfgoed.nl/term/id/rn/2/d60159d2-8b55-47b7-8301-5ac82b0f2d7f>)
      ("Bestuursgebouwen, rechtsgebouwen en overheidsgebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/2/74a847b5-1e0f-4f66-b910-90d2c8d9fa04>)
      ("Boerderijen, molens en bedrijven" <https://data.cultureelerfgoed.nl/term/id/rn/2/b8077035-db8f-47f1-ae1d-e64f75344fcf>)
      ("Cultuur, gezondheid en wetenschap" <https://data.cultureelerfgoed.nl/term/id/rn/2/0be0a6c9-0738-41cc-aaac-550d258c4261>)
      ("Handelsgebouwen, opslag- en transportgebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/2/e88ccbf4-e41d-49bf-9876-0f71db0e6646>)
      ("Kastelen, landhuizen en parken" <https://data.cultureelerfgoed.nl/term/id/rn/2/b2511baf-3b70-4667-98dd-1b850c7ea53f>)
      ("Religieuze gebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/2/25fac0f1-77a2-4587-ab04-dfcb66959dd8>)
      ("Sport, recreatie, vereniging en horeca" <https://data.cultureelerfgoed.nl/term/id/rn/2/b797b89c-1e0a-4ce7-869b-817cd98259b0>)
      ("Uitvaartcentra en begraafplaatsen" <https://data.cultureelerfgoed.nl/term/id/rn/2/1680dfc0-666a-4a01-9781-59e9af26ec51>)
      ("Verdedigingswerken en militaire gebouwen" <https://data.cultureelerfgoed.nl/term/id/rn/2/5013dcbc-1090-42e9-bc22-92de47e43783>)
      ("Voorwerpen op pleinen en dergelijke" <https://data.cultureelerfgoed.nl/term/id/rn/2/92cda3e4-8c6a-41dc-9a81-02f8aba88b25>)
      ("Weg- en waterbouwkundige werken" <https://data.cultureelerfgoed.nl/term/id/rn/2/11c897ed-d35e-4191-9254-7ab95d9d63bc>)
      ("Woningen en woningbouwcomplexen" <https://data.cultureelerfgoed.nl/term/id/rn/2/5b7dd16c-fa8d-4d68-984a-9ec0efc650d4>)
    }

    ?narrow skos:narrower+ ?uri .
  }

  filter(!bound(?hoofdcategorieFilter) || ?hoofdcategorie = ?hoofdcategorieFilter)

  ######################################################################
  # 3. Provincie via OWMS
  ######################################################################
  graph <https://linkeddata.cultureelerfgoed.nl/graph/owms> {
   ?provOud skos:prefLabel ?provincie .
  }

  ######################################################################
  # 4. Gemeente via TOOI (FEDERATIEF)
  ######################################################################
  service <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/tooi/sparql> {

  # gemeenten
  graph <https://linkeddata.cultureelerfgoed.nl/rce/tooi/graph/gemeenten> {
    ?gemActueel
      tooi:owmsId ?gemOudUri ;
      tooi:voorkeursnaamExclSoort ?gemeente ;
      tooi:gemeentecode ?gemeentecode .

    filter not exists {
      ?gemActueel tooi:einddatum ?einddatumGemeente
    }
  }

  # provincies (zelfde truc!)
  graph <https://linkeddata.cultureelerfgoed.nl/rce/tooi/graph/provincies> {
    ?provActueel
      tooi:owmsId ?provOudUri ;
      rdfs:label ?provincie .
  }
}
}
group by
  ?provincie
  ?gemeente
  ?gemeentecode
  ?monumentAard
  ?hoofdcategorie

order by
  ?provincie
  ?gemeente
  ?monumentAard
  ?hoofdcategorie