#+ name: staafgrafiek-aanwijzingsbesluit
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX schema: <https://schema.org/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?jaar ?geslacht (COUNT(?actor) AS ?aantal) {
     SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql>  
{  
  ?rm ceo:heeftGebeurtenis/ceo:heeftActorEnRol ?actor ;
      ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
    }
   ?actor schema:gender ?geslacht ;
     #     FILTER (!CONTAINS(?geslacht, "n.v.t."))

  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
  FILTER (?jaarInschrijving >= "1960"^^<http://www.w3.org/2001/XMLSchema#integer> && ?jaarInschrijving <= "2022"^^<http://www.w3.org/2001/XMLSchema#integer>)
  bind(concat(str(?jaarInschrijving)) as ?jaar)
  bind(concat(str(?aantal)) as ?aantals)

  } 
GROUP BY ?jaar ?geslacht 
order by ?jaar
#LIMIT 1000