#+ name: stinsrm-bb-1
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix edm: <http://www.europeana.eu/schemas/edm/>

select distinct ?stinscomplex ?wkt ?wktColor ?wktLabel ?depiction ?tekst ?rmnummer ?beeldbank ?mapEndpoint
where {
  {
    # geef me alle objecten in de CHO die overeenkomen met de ingevoerde term
    ?stinscomplex rdf:type ?type ;
                  ceo:rijksmonumentnummer ?rmnummer ;
                  ceo:heeftKennisregistratie ?omschrijving .
    ?omschrijving ceo:omschrijving ?tekst ;
                  ceox:heeftOmschrijvingOnderwerp ?stinsterm .

    # Voeg de gewenste termen hier toe
    values (?stinsterm ?type_label) {
      (<https://data.cultureelerfgoed.nl/term/id/cht/1130e375-3469-4e63-a8d4-5fcb339f7536> "stinzen")
      (<https://data.cultureelerfgoed.nl/term/id/cht/c615eaa4-85a7-4f2b-9a96-02aa766e8331> "dijken")
      (<https://data.cultureelerfgoed.nl/term/id/cht/97ff463f-06cf-49cd-aa33-08e3c2688f5a> "kazematten")
    }

    # Filter de ingevoerde term
    filter(?type_label = ?inputLabel)

    ?stinscomplex ceo:heeftGeometrie/geo:asWKT ?wkt .
    bind("black" as ?wktColor)
  }

  {
    # Selecteer slechts één afbeelding per stinscomplex
    ?afbeelding ceo:rijksmonumentnummer ?rmnummer ;
                foaf:depiction ?depiction ;
                edm:isShownAt ?beeldbank .
    filter(regex(?beeldbank, "beeldbank"))
  }

  # Gebruik SAMPLE om een willekeurige afbeelding te selecteren
  # Als je de eerste afbeelding wilt, kun je MAX gebruiken in plaats van SAMPLE
  # SAMPLE(?afbeelding)
  
  bind(
    strdt(
      concat(
        "<h4>Rijksmonumentnummer:", str(?rmnummer), "</h4>",
        "<center><img src='", COALESCE(str(?depiction), ''), "' style='max-width:200px'></center>",
        "<ul>",
        "<li>Omschrijving: ",
        str(
          if(strlen(str(?tekst)) > 250, 
            concat(substr(str(?tekst), 1, 250), "... <a href='https://monumentenregister.cultureelerfgoed.nl/monumenten/", str(?rmnummer), "' target='_blank'>lees hier verder</a>"), 
            str(?tekst)
          )
        ),
        "</li>",
        "<li>Rijksmonument: <a href='https://monumentenregister.cultureelerfgoed.nl/monumenten/", str(?rmnummer), "' target='_blank'>", str(?rmnummer), "</a></li>",
        "<li>Beeldbank: <a href='", str(?beeldbank), "' target='_blank'>klik hier</a></li>",
        "</ul>"
      ), rdf:HTML
    ) as ?wktLabel
  )

  bind(<https://services.rce.geovoorziening.nl/liniesenstellingen/wms?request=GetCapabilities> as ?mapEndpoint)

}
    group by ?stinscomplex ?wkt ?wktColor ?wktLabel ?depiction ?tekst ?rmnummer ?beeldbank ?mapEndpoint
limit 10000
