#+ name: structuuroverzicht-met-labels-in-nl-1
#+ description: Structuuroverzicht met labels in @nl
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/thesauri/oorlogsbronnen/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept ?prefLabel ?broader ?broaderLabel WHERE {
  ?concept a skos:Concept ;
           skos:prefLabel ?prefLabel .
  FILTER (lang(?prefLabel) = "nl")

  OPTIONAL {
    ?concept skos:broader ?broader .
    ?broader skos:prefLabel ?broaderLabel .
    FILTER (lang(?broaderLabel) = "nl")
  }
}
