#+ name: Tel-de-eigenschappen-die-elk-type-gebrui
#+ description: SELECT DISTINCT ?type (COUNT(DISTINCT ?p) AS ?c)
#- WHERE {
#-    ?s a ?type . 
#-    ?s ?p ?o . 
#- }
#- GROUP BY ?type
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql

SELECT DISTINCT ?type (COUNT(DISTINCT ?p) AS ?c)
WHERE {
   ?s a ?type . 
   ?s ?p ?o . 
}
GROUP BY ?type