#+ name: Tellen-monumenten2
#+ description: Het tellen van Archeologische Complextypen en tonen in een tabel
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select ?complextype (count(?i) as ?aantal) {
  ?i a ceo:ArcheologischComplex.
  ?i ceo:heeftType ?c.
  ?c ceo:heeftTypeNaam/skos:prefLabel ?complextype.
}
group by ?complextype
order by desc(?aantal)
#LIMIT 10