#+ name: training-material-query
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/thesaurus-inprogress/services/thesaurus-inprogress/sparql

prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix text: <http://jena.apache.org/text#>

select * where
{
  ?uri text:query (?predicate ?query).
  ?uri ?predicate ?label.
  ?uri a skos:Concept.
  ?uri skos:broader+ <https://data.cultureelerfgoed.nl/term/id/cht/aa872ce6-a74c-4f81-96ec-6ee0e717f92a> .


  values ?predicate {
  skos:prefLabel skos:altLabel
}
}
limit 5