PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?type_concept (count(?type_concept) as ?n) WHERE {
  
 GRAPH   <https://data.cultureelerfgoed.nl/term/id/cht/thesaurus> {
  
?concept a skos:Concept .
    ?concept rdf:type ?type_concept .

  
}
} ORDER BY DESC (?n)