#+ name: Unieke-classes-per-graph
SELECT (REPLACE(STR(?g), "^urn:graph:", "") AS ?graphNaam)
       ?class
       (COUNT(*) AS ?gebruik)
WHERE {
  GRAPH ?g {
    ?s a ?class .
  }
}
GROUP BY ?g ?class
ORDER BY ?g DESC(?gebruik)
