#+ name: vind-sekse
#+ description: Query om d.m.v. de voornaam in de Nederlandse Burgerlijke Stand uit de 19e eeuw een sekse (m/v) te koppelen aan een persoon. Vul simpelweg de naam in bij het veld `name` (onder `Variables`). Let op: hoofdlettergevoelig!
#- 
#- De kolom `gn_male_ratio` geeft aan hoe vaak deze naam procentueel aan een man is toegewezen als eerste voornaam. Hoe dichter deze waarde ligt bij de 100 of 0, hoe zekerder een naam is toe te wijzen aan respectievelijk een man of vrouw. De `n` geeft de absolute aantallen uit de dataset.
#- 
#- N.B.: wil je regular expressions toepassen op een naam, dan dien je de query te openen d.m.v. `View populated query` en vervolgens zelf te bewerken. Meer hierover in deze  [wiki](https://en.wikibooks.org/wiki/SPARQL/Expressions_and_Functions#Functions_on_strings).
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/CLARIAH-Given-Names/sparql

PREFIX schema: <https://schema.org/>
PREFIX names: <https://linkeddata.cultureelerfgoed.nl/clariahnames/vocab/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?name ?gender ?gn_male_ratio ?n WHERE {
 
  
  ?id names:gn ?name.
  ?id schema:gender ?gender .
  ?id names:gn_male_ratio ?gn_male_ratio .
  ?id names:gn_tokens_firstname ?n
  
  
} order by desc (?n)