PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select ?vondsttype (count(?i) as ?aantal) {
  ?i a ceo:Vondsten.
  ?i ceo:heeftType ?c.
  ?c ceo:heeftTypeNaam/skos:prefLabel ?vondsttype.

} 
group by ?vondsttype
order by desc(?aantal)

