#+ name: Vrouwelijke-kunstenaars-in-RKDa
#+ service: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rkdo: <http://data.rkd.nl/def#>
PREFIX schema: <http://schema.org/>

SELECT ?RKDa ?id ?naam ?gender
{
   SERVICE <https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql>
{
  ?RKDa a schema:Person .
  ?RKDa schema:identifier ?id .
  ?RKDa schema:name ?naam .
  ?RKDa schema:gender ?gender.
  FILTER (regex(?gender, "Female", "i")) 
}
}
ORDER BY ?id
