#+ name: Vuurtorens-als-rijksmonument-in-Wikidata
#+ description: Zoeken in Wikidata
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT * WHERE {

  SELECT DISTINCT ?rijksmonument (sample(?geografische_locatie) As ?wikiloco) ?rijksmonumentnummer  WHERE {
SERVICE <https://query.wikidata.org/sparql>
    {
  ?rijksmonument wdt:P1435 wd:Q916333.
  ?rijksmonument wdt:P31 wd:Q39715.
 ?rijksmonument wdt:P625 ?geografische_locatie. 
 ?rijksmonument wdt:P359 ?rijksmonumentnummer. 
    }}
}
ORDER BY ?rijksmonumentnummer
LIMIT 100  
