PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?property
WHERE {
  ?s a ceo:Rijksmonument;
     ?property ?o .
}

