#+ name: werelderfgoed-hvdl-3
#+ description: - werelderfgoednummer, ex: 1349
#- - cultuurfistorischObjectnummer, ex: 10134675
#- - heeftNaam, ex: Hollandse Waterlinies
#- - registratiedatum, ex: 2021-11-22
#- - werelderfgoedstatus, ex: werelderfgoed
#- </p>
#- Date: dd. 2024-03-05</br>
#- Version: 1.0
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
prefix geo: <http://www.opengis.net/ont/geosparql#>

select (concat('{ "type": "FeatureCollection", "features": [', group_concat(?feature; separator=','), ']}') as ?geojson)
where {
  graph graph:instanties-rce {
    ?werelderfgoed a ceo:Werelderfgoed ;
                   ceo:heeftWerelderfgoedstatus/skos:prefLabel ?werelderfgoedstatus ;
                   ceo:werelderfgoednummer ?werelderfgoednummer ;
                   ceo:cultuurhistorischObjectnummer ?cultuurhistorischObjectnummer ;
                   ceo:registratiedatum ?registratiedatum ;
                   ceo:heeftNaam/ceo:naam ?heeftNaam ;
                   ceo:heeftKennisregistratie ?kennisregistratie ;
                   ceo:heeftGeometrie ?geometrie .
    ?kennisregistratie ceo:formeelStandpunt ?formeelStandpunt .
    ?kennisregistratie ceo:huidigeNaam ?huidigeNaam .
    ?kennisregistratie ceo:registratiedatum ?registratiedatum_naam.
    ?geometrie ceo:asWKT-RD ?geometrie_rd.
    ?geometrie geo:asWKT ?geometrie_WGS84.
    ?geometrie ceo:heeftGeometrieKwaliteit/skos:prefLabel ?geometriekwaliteit.
    ?geometrie ceo:heeftGeometrieType/skos:prefLabel ?geometrietype.

    # Creating URL based on the UNESCO list
    bind(concat('https://whc.unesco.org/en/list/', str(?werelderfgoednummer)) as ?url)

    # Including the 'werelderfgoed_hvdl' graph in the query
    graph graph:werelderfgoed_hvdl {
      ?werelderfgoed ceo:jaarVanInschrijving ?jaarvaninschrijving.
      ?werelderfgoed ceo:heeftWerelderfgoedType/skos:prefLabel ?werelderfgoedtype.
      ?geometrie ceo:oppervlakteInHectare ?oppervlakteinhectare.
      ?geometrie ceo:oppervlakteInVierkanteKilometers ?oppervlakteinvierkantekilometers.
      ?geometrie ceo:oppervlakteInVierkanteMeters ?oppervlakteinvierkantemeters.
    }

    # Process the geometry into a valid JSON object
    bind(replace(?geometrie_WGS84, "^MULTIPOLYGON\\(\\(\\(", "[[[") as ?cleanGeom1)
    bind(replace(?cleanGeom1, "\\)\\)\\)$", "]]]") as ?cleanGeom2)
    bind(replace(?cleanGeom2, "\\)\\s*,\\s*\\(", "]],[[") as ?cleanGeom3)
    bind(replace(?cleanGeom3, ",\\s*", "],[") as ?cleanGeom4)
    bind(replace(?cleanGeom4, "\\s+", ",") as ?cleanGeom5)

    # Handle empty geometries
    bind(if(?cleanGeom5 = "", "[[]]", concat("[", ?cleanGeom5, "]")) as ?coordinates)

    # Generate GeoJSON feature for each result
    bind(
      concat(
        '{ "type": "Feature", "properties": { ',
        '"werelderfgoed": "', str(?werelderfgoed), '", ',
        '"cultuurhistorischObjectnummer": "', str(?cultuurhistorischObjectnummer), '", ',
        '"werelderfgoedstatus": "', str(?werelderfgoedstatus), '", ',
        '"werelderfgoedtype": "', str(?werelderfgoedtype), '", ',
        '"werelderfgoednummer": "', str(?werelderfgoednummer), '", ',
        '"registratiedatum": "', str(?registratiedatum), '", ',
        '"jaarvaninschrijving": "', str(?jaarvaninschrijving), '", ',
        '"heeftNaam": "', str(?heeftNaam), '", ',
        '"huidigeNaam": "', str(?huidigeNaam), '", ',
        '"registratiedatum_naam": "', str(?registratiedatum_naam), '", ',
        '"formeelStandpunt": "', str(?formeelStandpunt), '", ',
        '"url": "', str(?url), '", ',
        '"geometrietype": "', str(?geometrietype), '", ',
        '"geometriekwaliteit": "', str(?geometriekwaliteit), '" }, ',
        '"geometry": { "type": "MultiPolygon", "coordinates": ', ?coordinates, ' }',
        ' }'
      ) 
      as ?feature
    )
  }
}
