#+ name: Wikidata-objecten-collectie-Rietveld
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX pqv: <http://www.wikidata.org/prop/qualifier/value/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT DISTINCT ?item ?eventLabel (MIN(?image) AS ?eventMedia) (MIN(?jaar) AS ?eventDate) 
 WHERE {
   SERVICE <https://query.wikidata.org/sparql> {
   ?item p:P170|p:P287 ?statement0.
   ?statement0 (ps:P170|ps:P287/(wdt:170*)) wd:Q160435. # wd:Q160435 = Gerrit Rietveld 
   
# ------------------------------------------eventLabel---------------------------------------
   OPTIONAL { ?item (p:31|rdfs:label) ?eventLabel . FILTER(LANG(?eventLabel) = "nl")} 
#----------------------------------------------image-----------------------------------------   
# filter alleen image format dat werkt met de tijdlijn visualisatie.
   OPTIONAL { ?item wdt:P18 ?image . FILTER(REGEX(str(?image), "(?i)\\.(jpg|gif|jpeg|png)", "i"))}
   OPTIONAL{?item (wdt:P571|wdt:P276/(pqv:P580*)|wdt:P1619|wdt:P1319|ps:P580) ?periode .
   BIND(YEAR(?periode) AS ?jaar)}
  }
}
   GROUP BY ?item ?eventLabel ?eventMedia ?eventDate
