#+ The query selects datatype properties in the specified namespace, while excluding object properties. Change the # for object properties.
#+ endpoint: https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/cho/services/cho/sparql

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?p WHERE { 
    ?p a owl:DatatypeProperty .
    # The variable ?p is being queried as a datatype property.
    
    #?p a owl:ObjectProperty .
    # This line is commented out, indicating that object properties are not being included in the results.
    
    FILTER (strstarts(str(?p), "https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
    # The FILTER clause is used to restrict the results to properties that have URIs starting with the specified namespace.
}

