PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# CEO classes
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?class ?comment
WHERE
{
?class a owl:Class.
?class rdfs:comment ?comment.

  FILTER
    (strstarts(str(?class), "https://linkeddata.cultureelerfgoed.nl/def/ceo#"))}