prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?klasse {
  ?klasse a owl:Class.
  # We willen alleen klassen die de CEO namespace hebben.
  filter(strstarts(str(?klasse),str(ceo:)))
  # Alleen klassen die niet gebruikt worden (zogenaamde 'lege' klassen).
  filter not exists { [] a/rdfs:subClassOf* ?klasse. }
}
order by ?klasse