PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>


SELECT  *  WHERE {
   OPTIONAL { ?rijksmonument ceox:rijksmonumentnummer ?eventDescription. }
  ?rijksmonument ceox:heeftNaam/ceox:naam ?eventLabel.
  ?rijksmonument ceox:heeftGebeurtenis ?gebeurtenis.
  ?gebeurtenis ceox:heeftDatering ?eventDate .
  ?eventDate ceox:jaar ?eventStart .
  ?eventDate ceox:jaar ?eventEnd .
  ?rijksmonument ceox:heeftGeometrie/wgs84:asWKT ?destination.


{ select ?eventDescription ?eventMedia where { SERVICE <https://query.wikidata.org/sparql> {
  #?item wdt:P1435 wd:Q916333 . 
        ?item wdt:P359  ?eventDescription 
        ; wdt:P18 ?eventMedia .
      }}limit 1000 offset 100}
bind(?destination as ?eventLocation)  }
order by ?eventStart


