PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rn: <https://data.cultureelerfgoed.nl/term/id/rn#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>  
prefix wde: <http://www.wikidata.org/entity/>

SELECT ?geometrie ?geometrieLabel (COUNT(?rijksmonument) AS ?aantal)  WHERE {
  ?rijksmonument a ceo:Rijksmonument.
  ?rijksmonument ceo:heeftJuridischeStatus/skos:prefLabel ?grm.
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
  ?rijksmonument ceo:rijksmonumentnummer ?rmn.
  OPTIONAL {?rijksmonument ceo:heeftGeometrie/geo:asWKT ?geometrie .}
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
    ?functie ceo:heeftFunctieNaam ?uri.
    ?uri skos:prefLabel ?bovenuri.
  BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
  FILTER (?jaarInschrijving >= "1960"^^<http://www.w3.org/2001/XMLSchema#integer> && ?jaarInschrijving <= "2022"^^<http://www.w3.org/2001/XMLSchema#integer>)
  bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
  ?rijksmonument ceo:heeftMonumentAard <https://data.cultureelerfgoed.nl/term/id/rn/fc966a68-8863-4970-a83e-110f96006c21>.
  ?rijksmonument ceo:heeftGebeurtenis ?gebeurtenis.
  ?gebeurtenis ceo:heeftGebeurtenisNaam/skos:prefLabel ?gebeurtenisNaam.
  ?gebeurtenis ceo:heeftDatering ?datering.
  ?datering ceo:heeftBeginDatering ?beginDatering.
  ?datering ceo:heeftEindDatering ?eindDatering.
  ?beginDatering ceo:datum ?beginDatum.
    BIND(year(xsd:dateTime(?beginDatum)) as ?beginBouwjaar)
  bind(concat(str(?beginBouwjaar)) as ?beginBouwjaars)
  ?eindDatering ceo:datum ?eindDatum .
    BIND(year(xsd:dateTime(?eindDatum)) as ?eindBouwjaar)
  bind(concat(str(?eindBouwjaar)) as ?eindBouwjaars)
  FILTER (CONTAINS(?gebeurtenisNaam, "vervaardiging"))
  MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
   BIND(strdt(concat(?bovenuri, " - ", ?eindBouwjaars, " Rm: ",'<a href="https://monumentenregister.cultureelerfgoed.nl/monumenten/',uri(?rmn),'" target="_blank">',str(?rmn),'</a>'),rdf:HTML) AS ?geometrieLabel)
}

LIMIT 100  