PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hg: <http://rdf.histograph.io/> 

select *
#?vd ?naam ?voor ?reden ?geometrie ?bron (concat("Het dorp ", ?naam, " is verdwenen vóór ", ?voor, " De redenen waren: ", group_concat(?redenen; separator="; "), ". Dit is na te lezen in " ,?bron) AS ?geometrieLabel)

WHERE {

  ?vd a hg:PlaceInTime.
  ?vd dc:title ?naam .
  ?vd dc:date ?date.
  BIND(year(xsd:dateTime(?date)) as ?voor)
  ?vd dc:subject/skos:prefLabel ?reden .
  BIND(xsd:string(STR(?reden)) AS ?redenen)
  ?vd dc:source ?bron.
  ?vd gsp:asWKT ?geometrie.   

  BIND(concat("Het dorp ", ?naam, " is verdwenen vóór ", ?voor, " De redenen waren: ", ?redenen, ". Dit is na te lezen in " ,?bron) AS ?geometrieLabel)
  BIND(if(?redenen="concurrentie", "red", if(?redenen="industrie en infrastructuur", "purple", if(?redenen="onbekend", "maroon", if(?redenen="ontvolking", "darksalmon", if(?redenen="oorlogen", "orange", if(?redenen="overstromingen", "gray", if(?redenen="overstuivingen", "white", if(?redenen="verplaatsing", "aqua", "black")))))))) as ?geometrieColor)

}
#GROUP BY ?naam ?voor ?bron ?redenen ?vd ?geometrie ?reden