PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rn: <https://data.cultureelerfgoed.nl/term/id/rn/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>

SELECT DISTINCT * {
  GRAPH graph:instanties-rce {
#{ SELECT (COUNT(DISTINCT ?aantalRijksmonumenten) as ?Rijksmonumenten) 
#    {?aantalRijksmonumenten a ceo:Rijksmonument. }
#  }
#{ SELECT (COUNT(DISTINCT ?beschermde) AS ?Beschermd)
#    { ?beschermde a ceo:Rijksmonument ; ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/b2d9a59a-fe1e-4552-9a05-3c2acddff864> .}
# }
# { SELECT (COUNT(DISTINCT ?nietbeschermde) AS ?NietBeschermd)
#    { ?nietbeschermde a ceo:Rijksmonument ; ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227> .}
# }
# { SELECT (COUNT(DISTINCT ?voorbeschermde) AS ?VoorBeschermd)
#    { ?voorbeschermde a ceo:Rijksmonument ; ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/2e93edd1-098f-4f31-ae7e-72cb77f4d2ca> .}
# }
# { SELECT (COUNT(DISTINCT ?aantalComplexen) AS ?Complexen)
#    {?aantalComplexen a ceo:Complex.}
#  }
#  { SELECT (COUNT(DISTINCT ?aantalRMinComplexen) AS ?RMinComplexen)
#    {?rmincomplexen a ceo:Complex.
#    ?rmincomplexen ceo:heeftRijksmonument ?aantalRMinComplexen}
#  }
#  { SELECT (COUNT(DISTINCT ?aantalGezichten) AS ?Gezichten) 
#    {?aantalGezichten a ceo:Gezicht. }
#  }
#  { SELECT (COUNT(DISTINCT ?aantalWerelderfgoed) AS ?Werelderfgoed)
#    { ?aantalWerelderfgoed a ceo:Werelderfgoed. }
#  }
  { SELECT (COUNT(DISTINCT ?aantalVondsten) as ?Vondsten)
{?aantalVondsten a ceo:Vondsten.}
  }
{ SELECT (COUNT(DISTINCT ?aantalGrondsporen) AS ?Grondsporen)
    { ?aantalGrondsporen a ceo:Grondsporen.}
  }
{ SELECT (COUNT(DISTINCT ?aantalVondstlocaties) AS ?Vondstlocaties)
    { ?aantalVondstlocaties a ceo:Vondstlocatie. }
  }
{ SELECT (COUNT(DISTINCT ?aantalArcheologischeComplexen) as ?Arch_Complexen)
    { ?aantalArcheologischeComplexen a ceo:ArcheologischComplex .}
  }
{ SELECT (COUNT(DISTINCT ?aantalArcheologischeTerreinen) AS ?Terreinen)
    { ?aantalArcheologischeTerreinen a ceo:ArcheologischTerrein. }
  }
{ SELECT (COUNT(DISTINCT ?aantalArcheologischOnderzoeksgebied) AS ?Onderzoeksgebied)
    {?aantalArcheologischOnderzoeksgebied a ceo:ArcheologischOnderzoeksgebied.}
  }
    { SELECT (COUNT(DISTINCT ?aantalRijksmonumenten) as ?Rijksmonumenten) 
    {?aantalRijksmonumenten a ceo:Rijksmonument. }
  }
}
}