PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?objectProperty ?label 
       (GROUP_CONCAT(DISTINCT ?subPropertyOf; SEPARATOR=" | ") AS ?subProperty) 
       (GROUP_CONCAT(DISTINCT ?domain; SEPARATOR=" | ") AS ?domain) 
       (GROUP_CONCAT(DISTINCT ?range; SEPARATOR=" | ") AS ?range) 
       (GROUP_CONCAT(DISTINCT ?creation; SEPARATOR=" | ") AS ?creations) 
       (GROUP_CONCAT(DISTINCT ?modified; SEPARATOR=" | ") AS ?modifieds) 
       (GROUP_CONCAT(DISTINCT ?comment; SEPARATOR=" | ") AS ?comments) 
       (GROUP_CONCAT(DISTINCT ?description; SEPARATOR=" | ") AS ?descriptions) 
       (GROUP_CONCAT(DISTINCT ?note; SEPARATOR=" | ") AS ?notes) 
       (GROUP_CONCAT(DISTINCT ?example; SEPARATOR=" | ") AS ?examples)
WHERE {
  ?objectProperty a owl:ObjectProperty .
  ?objectProperty rdfs:label ?label.
  OPTIONAL {?objectProperty rdfs:subPropertyOf ?subPropertyOf . }
  OPTIONAL {?objectProperty rdfs:domain ?domain .}
  OPTIONAL {?objectProperty rdfs:range ?range .}
  OPTIONAL {?objectProperty dct:created ?creation .}
  OPTIONAL {?objectProperty dct:modified ?modified .}
  OPTIONAL {?objectProperty rdfs:comment ?comment .}
  OPTIONAL {?objectProperty dct:description ?description .}
  OPTIONAL {?objectProperty skos:editorialNote ?note.}
  OPTIONAL {?objectProperty skos:example ?example.}  
}
GROUP BY ?objectProperty ?subPropertyOf ?label
ORDER BY ?objectProperty ?label ?subPropertyOf
#LIMIT 10
