PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select  (Count(distinct ?class1) as ?ceoClass) (Count(distinct ?class2) as ?choClass)
WHERE
{
SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo/services/ceo/sparql>
{
?class1 a owl:Class
FILTER (strstarts(str(?class1),"https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}

?class2 a owl:Class
FILTER (strstarts(str(?class2),"https://linkeddata.cultureelerfgoed.nl/def/ceo#"))
}


