PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX lxr: <https://linkeddata.cultureelerfgoed.nl/def/lxr#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

# wdt:P31 = instance of
# wd:Q916333 = Rijksmonument
# wdt:P359 = rijksmonumentnummer
# wdt:P17 = country
# wdt:P18 = image
# wd:Q55 = Nederland
# wd:Q694 = Zuid-Holand
# wd:Q701 = Noord-Holland
# wd:Q1093 = Limburg



SELECT distinct ?rijksmonumentUri ?rijksmonumentnummer ?datumInschrijving ?startdatumOplevering ?einddatumOplevering

WHERE {

  SERVICE <https://query.wikidata.org/sparql> {?rm_wiki wdt:P1435 wd:Q916333 ; wdt:P359 ?rijksmonumentnummer 
    ; wdt:P131 ?plaats . ?plaats wdt:P131 wd:Q1093 . 
    optional {?rm_wiki wdt:P571  ?startdatumOplevering  . }
    optional {?rm_wiki wdt:P1619 ?einddatumOplevering . }
    optional {?rm_wiki rdfs:label ?label_wiki } 
    
      
  }
  
  GRAPH <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce> {?rijksmonumentUri ceo:rijksmonumentnummer ?rijksmonumentnummer 
  ; ceo:datumInschrijvingInMonumentenregister ?datumInschrijving 
  } 
} 
order by ?rijksmonumentnummer



 