PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX sdo: <https://schema.org/>


SELECT distinct ?woonplaats ?rmnr ?naam ?eventMedia WHERE {
  ?reliGebouw ceox:heeftAdresgegevens/ceox:woonplaats ?woonplaats.
  ?reliGebouw ceox:rijksmonumentnummer ?rmnr.
  ?reliGebouw ceox:heeftNaam/ceox:naam ?naam.
  ?reliGebouw ceox:heeftGeometrie/wgs84:asWKT ?destination.
  
  #{ select ?rmnr ?eventMedia where { SERVICE <https://query.wikidata.org/sparql> {
  #     ?item  wdt:P31 wd:Q16970 . 
  #      ?item wdt:P359  ?rmnr 
  #      ; wdt:P5775 ?eventMedia .
  #    }}
  #}
  
  {select ?woonplaats ?naam2 ?eventMedia where{ SERVICE <https://cat.apis.beeldengeluid.nl/sparql>{
  ?item sdo:name ?title ;
        sdo:about <http://data.beeldengeluid.nl/gtaa/28215>;
        sdo:location/skos:prefLabel ?w;
        sdo:mentions/sdo:mentions/skos:prefLabel ?n;
        sdo:associatedMedia [
      sdo:encodingFormat ?encoding ;
      sdo:contentUrl ?eventMedia
    ] ;
      }
      bind(str(?n) as ?naam2)
    bind(str(?w) as ?woonplaats)
      
    }
  }
       Filter regex(?naam, ?naam2, "i")
       


} 
