#benodigde prefixen
#resultaat is een kaart
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
PREFIX schema: <http://schema.org/>
PREFIX ceox: <https://linkeddata.cultureelerfgoed.nl/def/ceox#>
PREFIX lxr: <https://linkeddata.cultureelerfgoed.nl/def/lxr#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
prefix gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

#selecteer voorlopig alles
SELECT ?eventStart ?date ?tijd ?diepte ?magnitude ?rmn (GROUP_CONCAT(?abs; SEPARATOR=" en ") as ?eventLabel) ?abs 
{
#start de service naar de dataset aardbevingen  
  SERVICE <https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/aardbeving/services/aardbeving/sparql> {  
    ?event a schema:Event.
    ?event schema:name ?name.
    ?event schema:startDate ?eventStart.
    ?event schema:date ?date. 
    ?event schema:startTime ?tijd.
    ?event gsp:asWKT ?shape.  
    ?event lxr:diepte ?diepte.
    ?event lxr:magnitude ?magnitude.
    ?event ceox:woonplaatsnaam ?plaatsnaam .
  }
BIND(concat(?name," op ",?eventStart) AS ?abs)
  #einde service
#vraag nu met ceox:woonplaatsnaam ?plaatsnaam de vergelijkbare monumenten op in de cho database  
?rm a ceo:Rijksmonument.
?rm ceo:heeftBasisregistratieRelatie/ceo:heeftBAGRelatie/ceo:woonplaatsnaam ?plaatsnaam.
?rm ceo:rijksmonumentnummer ?rmn.
?rm ceo:heeftGeometrie/gsp:asWKT ?geo.

#hier volgen enkele binds en filters voor het eindresultaat  
bind(concat("https://monumentenregister.cultureelerfgoed.nl/monumenten/",uri(?rmn)) as ?link)
Bind(?afstandinmeters as ?afstand)
FILTER((geof:distance(?geo,?shape, uom:meter)) < ?afstand )
bind ("black" as ?geoColor)
bind ("red" as ?shapeColor)
#de date is amerikaans dus die zetten we ff om naar "normale" weergave  
BIND(concat(substr(str(?date), 9, 2), "-", substr(str(?date), 6, 2), "-", substr(str(?date), 1, 4)) AS ?new_date)

}
GROUP BY ?shape ?eventStart ?geo ?geoColor ?shapeColor ?geoLabel ?rmn ?abs ?date ?tijd ?diepte ?magnitude
ORDER BY ?eventStart
