PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX graph: <https://linkeddata.cultureelerfgoed.nl/graph/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rn: <https://data.cultureelerfgoed.nl/term/id/rn/>

SELECT  ?rijksmonument ?datumInschrijving ?rijksmonumentnummer ?jaarInschrijvings ?uriSubs
#?subFunctie (COUNT(?uri) AS ?labelSub) (COUNT(?rijksmonument) AS ?aantal) ?jaarInschrijvings ?shape

WHERE 
{
  GRAPH graph:instanties-rce {
  ?rijksmonument ceo:datumInschrijvingInMonumentenregister ?datumInschrijving.
   MINUS {?rijksmonument ceo:heeftJuridischeStatus <https://data.cultureelerfgoed.nl/term/id/rn/3e79bb7c-b459-4998-a9ed-78d91d069227>}
  ?rijksmonument ceo:heeftOorspronkelijkeFunctie ?functie.
  ?rijksmonument ceo:rijksmonumentnummer ?rijksmonumentnummer.
   
  ?functie ceo:heeftFunctieNaam ?uri.

 BIND(year(xsd:dateTime(?datumInschrijving)) as ?jaarInschrijving)
# BIND(year(xsd:dateTime(?jaarInschrijving)) as ?beginJaarInschrijving)
#   BIND(year(xsd:dateTime(?beginInschrijving)) as ?eindJaarInschrijving)
 
  FILTER (?jaarInschrijving >= ?beginJaarInschrijving && ?jaarInschrijving <= ?eindJaarInschrijving)
    bind(concat(str(?jaarInschrijving)) as ?jaarInschrijvings)
    BIND(concat(str(?beginJaarInschrijving)," - ", ?eindJaarInschrijving) AS ?periode)
  }
{
  GRAPH graph:bebouwdeomgeving {
  {<https://data.cultureelerfgoed.nl/term/id/rn/fea024ba-83a0-4418-afbe-3b7b4588797e> skos:broader ?uri.}
  UNION{  
  {<https://data.cultureelerfgoed.nl/term/id/rn/a3dbebf9-a237-4caa-9ee6-347c9d30dd9e> skos:narrower ?uri . }
      }
     ?uri skos:prefLabel ?uriSub.
     
      bind(replace(?uriSub, "\\s\\(.*\\)|\\(.*\\)", "") AS ?uriSubs) 
    }
    } 
  
  Bind(concat(str(?uriSubs), " ", ?periode) AS ?subFunctie)
} 
#GROUP BY ?subFunctie ?aantal ?jaarInschrijvings 