PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX vbw: <https://data.verkeersborden-wegen.nl/def/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?verkeersbord ?type ?naam ?locatie ?geometry {
  ?verkeersbord rdf:type vbw:Verkeersbord;
               vbw:HasBordType ?type;
               vbw:HeeftWegNaam ?naam;
               vbw:IsGelegenAan ?locatie.

  ?verkeersbord geo:hasGeometry ?geometryData.
  ?geometryData geo:asWKT ?geometry.
}
order by ?naam

