# Alle properties van een monument.
prefix ceo: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select distinct ?s ?p ?o {
  graph <https://linkeddata.cultureelerfgoed.nl/graph/instanties-rce> {
    ?s ceo:rijksmonumentnummer '1'.
    {
      ?s ?p ?x.
  #    filter(strstarts(str(?p),str(ceo:)))
    } union {
      ?s ?q ?y.
      ?y ?p ?x.
 #     filter(strstarts(str(?q),str(ceo:)) && strstarts(str(?p),str(ceo:)))
    }
    optional { ?x skos:prefLabel ?z. }
    bind(if(bound(?z),?z,?x) as ?o)
  }
}
order by ?s ?p ?o